"""Read-only edge strain decomposition; no exports, poses or source edits."""
from pathlib import Path
import importlib.util,hashlib,json,numpy as np
ROOT=Path('/Users/raynos/projects/games/rockhop'); BASE=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');OUT=ROOT/'docs/evidence/hero-remaster/one-rider-v2/source-rig188/read-only'
p=ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py';sp=importlib.util.spec_from_file_location('source_reader',p);m=importlib.util.module_from_spec(sp);sp.loader.exec_module(m)
h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
source=BASE/'source-preserving-garment185/operator/rider.glb';g=m.GLB(source);d=g.j;world=np.array(m.worlds(d));skin=d['skins'][0];rest=world[skin['joints']];ib=g.array(skin['inverseBindMatrices']).reshape(19,4,4).transpose(0,2,1);names=[d['nodes'][i]['name'].removeprefix('fresh.')for i in skin['joints']];centres=rest[:,:3,3];fixturepath=BASE/'basic-pose-gate158/fixture-v4-asymmetric-halfsteps.json';f=json.loads(fixturepath.read_text());assert names==f['jointNames']
parts=[]
for mi,mesh in enumerate(d['meshes']):
 for pi,p in enumerate(mesh['primitives']):
  pos=g.array(p['attributes']['POSITION']).astype(float);j=g.array(p['attributes']['JOINTS_0']);raw=g.array(p['attributes']['WEIGHTS_0']);w=(raw.astype(float)/np.abs(raw.astype(float)).sum(1,keepdims=True)).astype('f4').astype(float);W=np.zeros((len(pos),19));
  for k in range(4):np.add.at(W,(np.arange(len(pos)),j[:,k]),w[:,k])
  parts.append((mi,pi,pos,W,g.array(p['indices']).reshape(-1,3)))
mi,pi,P,W,T=parts[0];E=np.unique(np.sort(np.concatenate([T[:,[0,1]],T[:,[1,2]],T[:,[2,0]]]),axis=1),axis=0);delta=P[E[:,1]]-P[E[:,0]];L=np.linalg.norm(delta,axis=1);mid=P[E].mean(1);rows=[]
for family in ['overhead.L','overhead.R','forward.L','horizontal.L','elbow.L','forearm_twist.L','sit','squat','lean']:
 frames=[x for x in f['frames']if x['family']==family];frame=frames[len(frames)//2];D=np.array(frame['deformationWorldColumnMajor']).reshape(19,4,4).transpose(0,2,1);M=D@rest@ib;Q=np.einsum('vj,jab,vb->va',W,M[:,:3,:],np.c_[P,np.ones(len(P))],optimize=True);diff=Q[E[:,1]]-Q[E[:,0]];ratio=np.linalg.norm(diff,axis=1)/np.maximum(L,1e-15)
 # Exact algebra: Qb-Qa = sum(avgWeight * linearBone * restEdge) + sum(deltaWeight * bone(midpoint)).
 average=(W[E[:,0]]+W[E[:,1]])*.5;gradient=W[E[:,1]]-W[E[:,0]];a=np.einsum('ej,jab,eb->ea',average,M[:,:3,:3],delta,optimize=True);b=np.einsum('ej,jab,eb->ea',gradient,M[:,:3,:],np.c_[mid,np.ones(len(mid))],optimize=True);assert np.max(abs(a+b-diff))<1e-12
 mask=(L>=.002)&(mid[:,1]>.69)&(mid[:,1]<1.08)&(abs(mid[:,2])<.245)if family in ['sit','squat','lean']else (L>=.002)&(mid[:,1]>.94)&(mid[:,1]<1.49)&(abs(mid[:,2])>.09)&(abs(mid[:,2])<.36)
 ids=np.flatnonzero(mask);witness=[]
 for ei in ids[np.argsort(ratio[ids])[-5:][::-1]]:
  u,v=map(int,E[ei]);witness.append({'vertexIDs':[u,v],'sourcePosition':[P[u].tolist(),P[v].tolist()],'incidentFaceIDs':np.flatnonzero(((T==u).any(1))&((T==v).any(1))).tolist(),'restEdgeM':float(L[ei]),'deformedEdgeM':float(np.linalg.norm(diff[ei])),'ratio':float(ratio[ei]),'averagedBoneLinearTermM':float(np.linalg.norm(a[ei])),'weightGradientTermM':float(np.linalg.norm(b[ei])),'sourceWeightsByJoint':[{names[k]:float(W[q,k])for k in range(19)if W[q,k]>0}for q in [u,v]],'warning':'Terms are vectors; magnitudes do not add or establish blame. ROI is broad geometric envelope, not anatomical labels.'})
 rows.append({'family':family,'frame':frame['frame'],'timeSeconds':frame['timeSeconds'],'edgesInGeometricROI':len(ids),'maxRatio':float(ratio[ids].max()),'p99Ratio':float(np.percentile(ratio[ids],99)),'witnesses':witness})
seams=[]
for a,b,label in [(parts[0],parts[1],'body/glove'),(parts[0],parts[2],'body/hood')]:
 lookup={tuple(p):i for i,p in enumerate(b[2])};pairs=[(i,lookup[tuple(p)])for i,p in enumerate(a[2])if tuple(p)in lookup];gap=max((float(abs(a[3][i]-b[3][j]).max())for i,j in pairs),default=0);seams.append({'name':label,'attributeAliasPairs':len(pairs),'uniqueExactPositionPairs':len({tuple(a[2][i])for i,j in pairs}),'runtimeNormalizedWeightMaxDifference':gap,'limits':'Exact alias equality and LBS same-joint field prevent seam separation at these points; not glove cuff intersection, visual shape, normals or surface grip coverage acceptance.'})
external=Path('/Users/raynos/Documents/Codex/2026-10-01/task-3/hoodie-repair02');pins=[source,BASE/'rig-adapter01/body-bind34/rider.glb',BASE/'garment-rebuild01/physical-v5-control157/rider.glb',fixturepath,ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py',ROOT/'src/render/hero/gltfRider.ts',ROOT/'src/render/hero/sleeveSkin.ts',ROOT/'harness/hero-remaster/basic-pose-gate/protocol.ts',ROOT/'docs/evidence/hero-remaster/one-rider-v2/rig-foundation167/raw-foundation.json',ROOT/'docs/evidence/hero-remaster/one-rider-v2/physical-surface168/contact-report.json',external/'rig-lane/weights.py',external/'rig-lane/weights-ls-source-gate.json',external/'rig-lane/weights-ls-corrected-gate.json',external/'qa-lane/results/v7-export-motion-manifest-gate.json']
report={'status':'READ_ONLY_DIAGNOSTIC_NO_CANDIDATE','pins':[{'path':str(x),'SHA256':h(x)}for x in pins],'jointRestCentresM':dict(zip(names,centres.tolist())),'restInverseBindMaxResidual':float(abs(rest@ib-np.eye(4)).max()),'source185ExactRestVs34':bool(np.array_equal(rest,np.array(m.worlds(m.GLB(pins[1]).j))[m.GLB(pins[1]).j['skins'][0]['joints']])),'seams':seams,'strainDecomposition':rows,'limits':['Nine midpoint fixture samples only, independently computed CPU LBS; no new motion or rendered acceptance.','Rest matrices and source weights frozen; neither pivots nor anatomy approved.','No collision/coplanar analysis, no grip/sole contacts, no shader/mobile measurement.','No head/neck bending fixture coverage; head alignment requires moving landmarks.','No borrowed V5/V7 weights, shape targets or seams transplanted.']};OUT.joinpath('report.json').write_text(json.dumps(report,indent=2)+'\n');assert h(source)==report['pins'][0]['SHA256'];print(json.dumps({'seams':seams,'rows':[{k:r[k]for k in ['family','maxRatio','p99Ratio']}for r in rows]}))
