"""Frozen edge-only transition audit; no rendering, edits or candidate output."""
import runpy,json,numpy as np,hashlib
from pathlib import Path
x=runpy.run_path(str(Path(__file__).with_name('audit_source.py')));g=x['g'];P=x['P'];W=x['W'];T=x['T'];f=x['f'];rest=x['rest'];ib=x['ib'];names=x['names'];c=x['centres'];ids=np.array([2030,2172]);p4=np.c_[P[ids],np.ones(2)];delta=P[ids[1]]-P[ids[0]];L=np.linalg.norm(delta);detail={'vertexIDs':ids.tolist(),'sourcePositionsM':P[ids].tolist(),'rawFourLanes':{},'normalizedWeights19':W[ids].tolist(),'incidentFaces':{},'aliases':{},'segmentProximity':{},'morphs':[],'frames':[]}
a=g.j['meshes'][0]['primitives'][0]['attributes'];rawJ=g.array(a['JOINTS_0']);rawW=g.array(a['WEIGHTS_0'])
for i in ids:
 i=int(i);detail['rawFourLanes'][str(i)]={'joints':rawJ[i].tolist(),'weights':rawW[i].tolist(),'normalization':'Float64 absolute sum then Float32 lanes matching foundation167 loader prediction; direct actual Three witness not run here.'};tri=np.flatnonzero((T==i).any(1));detail['incidentFaces'][str(i)]=[{'faceID':int(k),'vertexIDs':T[k].tolist()}for k in tri];detail['aliases'][str(i)]=np.flatnonzero((P==P[i]).all(1)).tolist();dist=[]
 for n,ch in [('chest','neck'),('shoulder.L','upperArm.L'),('upperArm.L','forearm.L'),('forearm.L','hand.L')]:
  q,r=c[names.index(n)],c[names.index(ch)];v=r-q;t=float(np.clip((P[i]-q)@v/(v@v),0,1));dist.append({'segment':n+'->'+ch,'projectedFraction':t,'distanceM':float(np.linalg.norm(P[i]-(q+t*v)))})
 detail['segmentProximity'][str(i)]=dist
for target in g.j['meshes'][0]['primitives'][0].get('targets',[]):
 detail['morphs'].append({k:g.array(v)[ids].tolist()for k,v in target.items()})
for family in ['overhead.L','overhead.R','forward.L','elbow.L','forearm_twist.L']:
 for fr in [z for z in f['frames']if z['family']==family]:
  D=np.array(fr['deformationWorldColumnMajor']).reshape(19,4,4).transpose(0,2,1);M=D@rest@ib;Q=np.einsum('vj,jab,vb->va',W[ids],M[:,:3,:],p4);edge=Q[1]-Q[0];avg=(W[ids[0]]+W[ids[1]])*.5;grad=W[ids[1]]-W[ids[0]];mean=P[ids].mean(0);a=np.einsum('j,jab,b->a',avg,M[:,:3,:3],delta);b=np.einsum('j,jab,b->a',grad,M[:,:3,:],np.r_[mean,1]);assert abs(a+b-edge).max()<1e-12
  detail['frames'].append({'family':family,'frame':fr['frame'],'timeSeconds':fr['timeSeconds'],'worldPositionsM':Q.tolist(),'worldDisplacementsVsSourceM':(Q-P[ids]).tolist(),'edgeVectorM':edge.tolist(),'ratio':float(np.linalg.norm(edge)/L),'averageLinearTermM':a.tolist(),'weightGradientTermM':b.tolist(),'gradientDotFinalEdgeDirectionM':float(b@(edge/np.linalg.norm(edge)))})
detail['summaries']=[{'family':family,'samples':sum(r['family']==family for r in detail['frames']),'maxRatio':max(r['ratio']for r in detail['frames']if r['family']==family),'maxRatioFrame':max((r for r in detail['frames']if r['family']==family),key=lambda r:r['ratio'])['frame']}for family in sorted(set(r['family']for r in detail['frames']))];detail['limits']=['Literal distinct adjacent vertices; this is not duplicate seam separation.','Nearest inferred rig segments locate inner sleeve/elbow vicinity, not skin landmark proof or ownership labels.','Half-step frames included in full193-family samples; none trained or edited, so no claimed successful holdout generalization.','Left witness only; unaffected right control is same leftedge during overhead.R, not entire right garment.','Actual Three getVertexPosition and current adapter are pending parentGo; this audit is independent affine CPU only.']
out=Path('docs/evidence/hero-remaster/one-rider-v2/source-rig188/read-only/witness-detail.json');out.write_text(json.dumps(detail,indent=2)+'\n');print(json.dumps({'summaries':detail['summaries'],'segmentProximity':detail['segmentProximity'],'morphs':detail['morphs'],'distinctPositions':bool(np.any(P[ids[0]]!=P[ids[1]]))}))
b=out.parent;files=[Path(__file__),Path(__file__).with_name('audit_source.py'),b/'report.json',b/'README.md',out];freeze=json.loads((b/'freeze.json').read_text());freeze['files']=[{'path':str(p.resolve()),'SHA256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}for p in files];(b/'freeze.json').write_text(json.dumps(freeze,indent=2)+'\n')
