"""Verify every matched frame and encode six complete inclusive family films."""
from pathlib import Path
import json,hashlib,struct,subprocess
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');S=B/'source-preserving-garment187';E=R/'docs/evidence/hero-remaster/one-rider-v2/source-preserving-garment187';A=R/'assets/blender/hero-remaster/rider/one-rider-v2/source-preserving-garment187';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();digest=lambda b:hashlib.sha256(b).hexdigest();save=lambda p,x:p.write_text(json.dumps(x,indent=2)+'\n');attempt=json.loads((E/'attempt.json').read_text())
def flat(x):
 if isinstance(x,list):return [z for y in x for z in flat(y)]
 return [x]
try:
 process=json.loads((E/'process.json').read_text());assert process['status']=='FROZEN_BOTH_MATCHED_CAPTURES_COMPLETE';prep=json.loads((E/'preparation.json').read_text());fixture=json.loads((S/'fixture-three-families.json').read_text());reports={label:json.loads((S/label/'report.json').read_text())for label in ['candidate','baseline']};sourcePaths={'candidate':B/'candidate-handoff170/hood-fixed185-187/rider.glb','baseline':B/'rig-adapter01/body-bind34/rider.glb'};world=[];films=[];frameHashes={};worldhash={};maxError=0;maxMatchedDifference=0
 for label,rep in reports.items():
  assert len(rep['frames'])==579 and rep['loaded']==[sha(sourcePaths[label])]and rep['sourceSHA256']==sha(sourcePaths[label])and not rep['errors']and'failure'not in rep;assert rep['fixtureSHA256']==sha(S/'fixture-three-families.json');frameHashes[label]=[]
  for i,(row,actual)in enumerate(zip(fixture['frames'],rep['frames'])):
   assert row['family']==actual['family']and row['frame']==actual['frame'];maxError=max(maxError,actual['matrixError']);assert actual['matrixError']<1e-8;p=S/label/'frames'/f'{i:04d}.png';b=p.read_bytes();assert b[:8]==b'\x89PNG\r\n\x1a\n'and struct.unpack_from('>II',b,16)==(1440,960);frameHashes[label].append({'captureIndex':i,'family':row['family'],'familyFrame':row['frame'],'timeSeconds':row['timeSeconds'],'path':str(p),'sha256':digest(b),'jointMatricesSha256':digest(json.dumps(actual['jointMatrices'],separators=(',',':')).encode()),'trianglesPerView':actual['trianglesPerView'],'callsPerView':actual['callsPerView']})
  worldhash[label]=digest(json.dumps([x['jointMatrices']for x in rep['frames']],separators=(',',':')).encode());save(E/f'{label}-capture-report.json',rep)
 for i,(ca,ba)in enumerate(zip(reports['candidate']['frames'],reports['baseline']['frames'])):
  delta=max(abs(a-b)for a,b in zip(flat(ca['jointMatrices']),flat(ba['jointMatrices'])));maxMatchedDifference=max(maxMatchedDifference,delta);assert delta<1e-12 and ca['trianglesPerView']==ba['trianglesPerView']and ca['callsPerView']==ba['callsPerView'];world.append({'captureIndex':i,'family':ca['family'],'familyFrame':ca['frame'],'maximumWorldMatrixDifference':delta,'worldHashEqual':frameHashes['candidate'][i]['jointMatricesSha256']==frameHashes['baseline'][i]['jointMatricesSha256']})
 save(E/'all-frame-identity-matrix-comparison.json',{'actualLoadedSourceHashes':{k:reports[k]['loaded']for k in reports},'allFrameCount':579,'maximumFixtureWorldParityError':maxError,'maximumMatchedWorldDifference':maxMatchedDifference,'aggregateWorldHashes':worldhash,'aggregateWorldHashesEqual':worldhash['candidate']==worldhash['baseline'],'rows':world});save(S/'frozen-frame-registry.json',frameHashes)
 for label in ['candidate','baseline']:
  for offset,family in [(0,'overhead.L'),(193,'forward'),(386,'sit')]:
   selected=reports[label]['frames'][offset:offset+193];assert len(selected)==193 and all(x['family']==family for x in selected)and[x['frame']for x in selected]==list(range(193));out=E/f'{label}-{family}.mp4';assert not out.exists();cmd=['/opt/homebrew/bin/ffmpeg','-hide_banner','-loglevel','error','-framerate','48','-start_number',str(offset),'-i',str(S/label/'frames/%04d.png'),'-frames:v','193','-an','-c:v','libx264','-threads','2','-crf','19','-pix_fmt','yuv420p','-movflags','+faststart',str(out)];subprocess.run(cmd,check=True);probe=json.loads(subprocess.check_output(['/opt/homebrew/bin/ffprobe','-v','error','-count_frames','-show_streams','-show_format','-of','json',str(out)],text=True));assert len(probe['streams'])==1;v=probe['streams'][0];assert v['codec_type']=='video'and int(v['nb_read_frames'])==193 and v['r_frame_rate']=='48/1'and(v['width'],v['height'])==(1440,960)and abs(float(v['duration'])-193/48)<1e-6;films.append({'label':label,'family':family,'path':str(out),'sha256':sha(out),'frames':193,'fps':48,'durationRational':'193/48','durationSeconds':193/48,'containerDurationSeconds':float(probe['format']['duration']),'audioStreams':0,'firstCaptureIndex':offset,'lastCaptureIndex':offset+192,'encodingCommand':cmd})
 for path,d in prep['inputs'].items():assert sha(Path(path))==d['sha256']
 report={'status':'FROZEN_1158_MATCHED_STOCK_THREE_FRAMES_PENDING_PARENT_PLAYBACK','candidateSHA256':sha(sourcePaths['candidate']),'baselineSHA256':sha(sourcePaths['baseline']),'fixtureSHA256':sha(S/'fixture-three-families.json'),'images':1158,'viewsPerFrame':6,'viewCells':6948,'filmCount':6,'films':films,'maximumFixtureWorldParityError':maxError,'maximumMatchedWorldDifference':maxMatchedDifference,'aggregateWorldMatrixHashes':worldhash,'maximumAnonymousGB':max(x['anonymousGB']for x in process['memorySamples']),'captureSeconds':process['seconds'],'noGeometryWeightsPoseShaderChange':True,'mapperUnmodified':True,'metadataDifferences':prep['declaredMetadataDifferences'],'limits':['Authored stress fixture, not native clip playback, Garage/physics/contact/device acceptance','All finite transition frames retained, no continuous-time collision guarantee','Six-view stock gray/PBR matching, parent sole appearance judge','Only eight hood face-slot geometry differences against source baseline, original normals retained']};save(E/'report.json',report);attempt['status']=report['status'];save(E/'attempt.json',attempt)
 files=[p for p in E.iterdir()if p.is_file()and p.name!='freeze.json']+list(A.glob('*.py'))+[p for p in S.rglob('*')if p.is_file()]+[sourcePaths['candidate'],sourcePaths['candidate'].parent/'mapping-report.json'];freeze={'status':report['status'],'files':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(files)]};save(E/'freeze.json',freeze);print(json.dumps({'status':report['status'],'frames':1158,'films':6,'maxMatchedWorldDifference':maxMatchedDifference,'worldHashes':worldhash,'freezeSHA256':sha(E/'freeze.json')}))
except Exception as e:
 attempt['status']='FROZEN_FILM_OR_FINAL_RECEIPT_FAILURE';attempt['failures'].append({'stage':'film/full-frame identity freeze','type':type(e).__name__,'error':str(e)});save(E/'attempt.json',attempt);raise
