const scenes={
  first:{tag:'NEW COURSE CLEAR',small:'FIRST FINISH',headline:'YOU FOUND THE LINE',medal:'DIAMOND',medalClass:'diamond',time:'0:31.025',pb:'0:31.025',pbCopy:'FIRST PERSONAL BEST',faults:'0',goal:'YOUR NEXT LINE',hint:'Try the opening brake gate with a slower entry and chase a cleaner split.'},
  best:{tag:'NEW PERSONAL BEST',small:'TIME IMPROVED',headline:'FASTER THROUGH THE GATE',medal:'DIAMOND',medalClass:'diamond',time:'0:29.421',pb:'− 0:01.604',pbCopy:'BEAT PREVIOUS BEST',faults:'0',goal:'YOUR NEXT LINE',hint:'The turn after the pallet ramp is the next place to carry speed.'},
  medal:{tag:'MEDAL UPGRADED',small:'GOLD → DIAMOND',headline:'THE CLEAN LINE PAID OFF',medal:'DIAMOND',medalClass:'diamond',time:'0:31.025',pb:'− 0:06.797',pbCopy:'BEAT PREVIOUS BEST',faults:'0',goal:'YOUR NEXT LINE',hint:'Diamond is yours. Replay the run or take this control to Crane Hop.'},
  same:{tag:'COURSE CLEARED',small:'RESULT RECORDED',headline:'ONE MORE RUN?',medal:'GOLD',medalClass:'gold',time:'0:42.015',pb:'0:39.412',pbCopy:'PERSONAL BEST STANDS',faults:'2',goal:'NEXT MEDAL: DIAMOND',hint:'Clear with zero bails and a faster line. Brake before the pallet ramp.'}
};
const $=id=>document.getElementById(id);
function setScenario(key){const s=scenes[key];if(!s)return;for(const b of document.querySelectorAll('[data-scenario]'))b.setAttribute('aria-pressed',String(b.dataset.scenario===key));$('action-state').hidden=true;$('report-tag').textContent=s.tag;$('title-small').textContent=s.small;$('headline').textContent=s.headline;$('medal').className=`medal ${s.medalClass}`;$('medal').setAttribute('aria-label',`${s.medal} medal`);$('medal-label').textContent=s.medal;$('run-time').textContent=s.time;$('pb-copy').textContent=s.pbCopy;$('pb-value').textContent=s.pb;$('faults').textContent=s.faults;$('goal-title').textContent=s.goal;$('goal-copy').textContent=s.hint;document.querySelector('.hero-picture').style.animation='none';void document.querySelector('.hero-picture').offsetWidth;document.querySelector('.hero-picture').style.animation='';}
for(const b of document.querySelectorAll('[data-scenario]'))b.addEventListener('click',()=>setScenario(b.dataset.scenario));
const actionCopy={retry:['RUN RESET','BACK ON THE START LINE','The real game would resume immediately; this study only demonstrates the one-tap route.'],next:['NEXT COURSE','CRANE HOP','The next course would load from the result without another menu.'],map:['WORLD MAP','PICK YOUR NEXT STOP','The 12-stop 3D selector would open here.'],replay:['RUN REPLAY','WATCH THE FINISH LINE','A real deterministic recording would play here. This bar only demonstrates transport space.']};
for(const b of document.querySelectorAll('[data-action]'))b.addEventListener('click',()=>{const [over,heading,detail]=actionCopy[b.dataset.action];$('action-overline').textContent=over;$('action-heading').textContent=heading;$('action-detail').textContent=detail;$('replay-progress').hidden=b.dataset.action!=='replay';$('action-state').hidden=false;$('back').focus();});
$('back').addEventListener('click',()=>{$('action-state').hidden=true;document.querySelector('[data-action="retry"]').focus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('action-state').hidden){$('back').click();}});
setScenario('first');
