"""Conserved-source six-state A/B; volume quantities are explicitly proxies."""
from pathlib import Path
import json,hashlib,sys
import numpy as np
from common import OUT,RUN,load,accessor
out=Path(sys.argv[1]) if len(sys.argv)>1 else OUT
def read(folder,rec,n):
 p=folder/rec['file'];p=p if p.exists() else RUN/folder.name/rec['file'];assert hashlib.sha256(p.read_bytes()).hexdigest()==rec['sha256'];return np.fromfile(p,dtype='<f8').reshape(-1,n)
a=json.loads((out/'baseline11-cpu/report.json').read_text());b=json.loads((out/'candidate-cpu/report.json').read_text());am=json.loads((out/'baseline11-cpu/pose-manifest.json').read_text());bm=json.loads((out/'candidate-cpu/pose-manifest.json').read_text());raw,j,bin,p,_=load();rest,_,_=accessor(j,bin,p['attributes']['POSITION']);ix,_,_=accessor(j,bin,p['indices']);tri=ix.reshape(-1,3);roi=(rest[:,1]>=.78*1.015)&(rest[:,1]<=1.0*1.015);vmasks={'hip-height':roi,'posterior-hip-height':roi&(rest[:,0]<.634775)};rows=[]
for ar,br in zip(am['rows'],bm['rows']):
 assert ar['i']==br['i'];assert ar['bonePoints']==br['bonePoints'];assert ar['debug']==br['debug'];assert ar['contacts']==br['contacts'];assert ar['lean']==br['lean']
 ap=read(out/'baseline11-cpu',ar['dump'][0]['positions'],3);bp=read(out/'candidate-cpu',br['dump'][0]['positions'],3);ad=read(out/'baseline11-cpu',ar['dump'][0]['skinLinearDeterminants'],1)[:,0];bd=read(out/'candidate-cpu',br['dump'][0]['skinLinearDeterminants'],1)[:,0];metrics=[]
 for region,mask in vmasks.items():
  metric={'region':region,'vertices':int(mask.sum()),'baselineMinSkinLinearDeterminant':float(ad[mask].min()),'candidateMinSkinLinearDeterminant':float(bd[mask].min()),'baselineSkinLinearDeterminantPercentiles':np.percentile(ad[mask],[0,1,5,50,95,100]).tolist(),'candidateSkinLinearDeterminantPercentiles':np.percentile(bd[mask],[0,1,5,50,95,100]).tolist(),'baselineVerticesDetBelowQuarter':int((ad[mask]<.25).sum()),'candidateVerticesDetBelowQuarter':int((bd[mask]<.25).sum()),'baselineAABBVolumeProxyM3':float(np.prod(ap[mask].max(0)-ap[mask].min(0))),'candidateAABBVolumeProxyM3':float(np.prod(bp[mask].max(0)-bp[mask].min(0))),'maximumPointDisplacementM':float(np.linalg.norm(ap[mask]-bp[mask],axis=1).max())};metrics.append(metric)
 local=[]
 for x,y in zip(a['poses'],b['poses']):
  assert x['sample']==y['sample'] and x['region']==y['region'] and x['triangles']==y['triangles']
  if x['sample']!=ar['i']:continue
  local.append({'region':x['region'],'triangles':x['triangles'],'baselineFolds':x['newFaceAgainstSkinnedNormalTriangles'],'candidateFolds':y['newFaceAgainstSkinnedNormalTriangles'],'baselineAreaBelowQuarterTriangles':x['areaBelowQuarterTriangles'],'candidateAreaBelowQuarterTriangles':y['areaBelowQuarterTriangles'],'baselineMaximumEdgeStretch':x['maximumEdgeStretch'],'candidateMaximumEdgeStretch':y['maximumEdgeStretch'],'baselineFoldWitness':x['worst'][0],'candidateFoldWitness':y['worst'][0],'baselineStretchWitness':x['maximumEdgeStretchWitness'],'candidateStretchWitness':y['maximumEdgeStretchWitness']})
 rows.append({'sample':ar['i'],'lean':ar['lean'],'bonePointsExact':True,'debugExact':True,'retainedPlayedHandSolePointParityExact':True,'regions':local,'volumeProxies':metrics})
summary={'baselineSHA256':am['sourceSHA256'],'candidateSHA256':bm['sourceSHA256'],'singleWeightTrial':True,'sourceGeometryBytesExact':json.loads((out/'build-report.json').read_text())['geometryNormalsUVIndicesMorphImagesMaterialsAnimationBindsSocketsExact'],'allSixPhysicalTargetsBonesDebugAndRetainedContactErrorsExact':True,'candidateSourceUnchanged':bm['sourceUnchanged'],'sourceUnchanged':am['sourceUnchanged'],'maximumRetainedPlayedPointErrorM':b['maximumCPUvsRetainedPlayedContactErrorM'],'maximumCandidateHipEdgeStretch':max(x['candidateMaximumEdgeStretch'] for r in rows for x in r['regions'] if x['region']=='hip-seat'),'maximumBaselineHipEdgeStretch':max(x['baselineMaximumEdgeStretch'] for r in rows for x in r['regions'] if x['region']=='hip-seat'),'numericalFinding':'Fewer hip fold indicators but increased upper-leg folds, collapsed hip faces and worst edge stretch; not a coherent improvement. Stop this trial rather than tune another strip. Parent judgment remains authority.','rows':rows,'limits':['No GPU, rendered appearance score, promoted asset, physics change or moving adoption.','Weighted bone-matrix determinant is local fixed-weight affine skin-volume proxy; it omits spatial weight gradients and cannot certify anatomical volume.','AABB is an extent proxy, not closed mesh volume. Source-region triangle contraction/stretch and actual fold witnesses provide complementary limits.','Read-only physical replay-state reconstruction matches retained actual surface points; actual moving judgment belongs to parent.']};(out/'comparison.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps({k:v for k,v in summary.items() if k not in ['rows','limits']}))
