"""Strict rest gate of ONE routed panel, no geometry changes."""
from pathlib import Path
import ast,json,hashlib,time
import numpy as np
from scipy.spatial import cKDTree
REPO=Path('/Users/raynos/projects/games/rockhop');ROOT=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');RUN=ROOT/'garment-rebuild01/routed-panels157';OUT=REPO/'docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/routed-panels157'
f=np.load(RUN/'routed-instrument.npz');P=f['positions'];T=f['triangles'];N=f['normals'];W=f['weights'];HP=f['protectedHoodPositions'];HT=f['protectedHoodTriangles'];ring=f['protectedRingIDs'];alias=f['protectedHoodAliases'];combined=np.concatenate([P,HP]);combinedT=np.concatenate([T,HT+len(P)]);_,inv=np.unique(combined,axis=0,return_inverse=True);ids=inv[combinedT];transitionIDs=f['newTriangleIDs'];changedMask=np.zeros(len(combinedT),bool);changedMask[transitionIDs]=True
prior=REPO/'assets/blender/hero-remaster/rider/one-rider-v2/garment-rebuild01/shoulder-transition155/audit.py';tree=ast.parse(prior.read_text());code='\n'.join(ast.unparse(x) for x in tree.body if isinstance(x,ast.FunctionDef) and x.name in ['segment_triangle','intersections']);code=code.replace('(candidates < transitionIDs[0]) | (candidates > i)','(~changedMask[candidates]) | (candidates > i)');assert '(~changedMask[candidates])' in code;exec(compile(code,str(prior),'exec'),globals());start=time.monotonic();result=intersections(combined)
cross=np.cross(P[T[:,1]]-P[T[:,0]],P[T[:,2]]-P[T[:,0]]);area=np.linalg.norm(cross,axis=1)/2;dots=np.einsum('ij,ij->i',cross/np.maximum(np.linalg.norm(cross,axis=1,keepdims=True),1e-20),N[T].mean(1));c=np.load(ROOT/'garment-rebuild01/cage04/fit04.npz');np.testing.assert_array_equal(P[:len(c['positions'])],c['positions']);np.testing.assert_array_equal(W[:len(c['weights'])],c['weights']);np.testing.assert_array_equal(P[ring],HP[alias]);np.testing.assert_array_equal(N[ring],f['protectedHoodNormals'][alias]);np.testing.assert_array_equal(W[ring],f['protectedHoodWeights'][alias]);q=c['quads'][f['nativeRetainedQuadIDs']];uv=c['uvLoops'].reshape(-1,4,2)[f['nativeRetainedQuadIDs']];nativeT=np.array([face[k] for face in q for k in [[0,1,2],[0,2,3]]]);nativeUV=np.array([u[k] for u in uv for k in [[0,1,2],[0,2,3]]]);np.testing.assert_array_equal(T[:len(nativeT)],nativeT);np.testing.assert_array_equal(f['triangleUV'][:len(nativeT)],nativeUV)
restClear=result['strictNoncoplanarCrossings']==0 and int((area<1e-12).sum())==0 and int((dots[transitionIDs]<0).sum())==0
report={'status':'Rest geometric evidence, parent judges; no appearance/rig gate','sourceSHA256':json.loads((OUT/'build-report.json').read_text())['sourceSHA256'],'instrumentSHA256':hashlib.sha256((RUN/'routed-instrument.npz').read_bytes()).hexdigest(),'priorVerifierSourceSHA256':hashlib.sha256(prior.read_bytes()).hexdigest(),'newYokeTriangles':len(transitionIDs),'strictIntersectionAudit':result,'minimumAreaM2':float(area.min()),'zeroAreaTriangles':int((area<1e-12).sum()),'negativeCandidateNormalDotsNewYoke':int((dots[transitionIDs]<0).sum()),'nativePositionsWeightsRetainedTopologyUVExact':True,'protectedSeamPositionNormalWeightsExact':True,'restClearForMotionProbe':restClear,'motionRun':False,'seconds':time.monotonic()-start,'limits':['Intersection counts cover every new yoke triangle against all nonadjacent yoke/native/hood triangles at rest.','Strict noncoplanar crossings only; coplanar overlap and shared exact-rest vertex pairs excluded.','Immutable source head is outside the collision query.','No complete GLB, textures, visual appearance/rig score or moving contact evidence.']}
(OUT/'rest-audit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='strictIntersectionAudit'}|{'intersections':{k:v for k,v in result.items() if k!='literalTrianglePairs'}},indent=2))
