"""Freeze read-only receipts and dependency provenance; no asset promotion."""
from pathlib import Path
import json,hashlib,subprocess,datetime,struct
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');A=R/'assets/blender/hero-remaster/rider/one-rider-v2/rig-foundation167';O=R/'docs/evidence/hero-remaster/one-rider-v2/rig-foundation167';S=B/'rig-foundation167';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();raw=json.loads((O/'raw-foundation.json').read_text());actual=json.loads((O/'actual-three-foundation.json').read_text());ind=json.loads((O/'independent-affine.json').read_text());fixture=json.loads((S/'raw-input.json').read_text())
for x in raw['sources']:assert sha(Path(x['source']))==x['SHA256']
assert sha(Path(fixture['fixture']))==fixture['fixtureSHA256'];assert actual['frames']==5404;assert len(actual['bindings'])==5;assert all(x['maximumCoreMotionVsNeutralM']==0 for x in actual['families'] if '.' in x['family']);assert actual['maximumActualVsRawAffineErrorM']<1e-8;assert ind['maximumPerFrameMotionDifferenceFromActualThreeM']<1e-8
paths=list(A.glob('*'))+[R/p for p in ['src/render/hero/gltfTestUtils.ts','src/render/hero/lod.ts','src/render/hero/gltfRider.ts','src/render/hero/sleeveSkin.ts','harness/hero-remaster/basic-pose-gate/protocol.ts','harness/hero-remaster/new-rider-fresh-c19-adapter.mts','harness/hero-remaster/new-rider-private-adapter.mts','docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/body-bind34/mapping-report.json']]
c19=Path(raw['sources'][0]['source']).read_bytes();g34=Path(raw['sources'][1]['source']).read_bytes()
def binchunk(x):n=struct.unpack_from('<I',x,12)[0];return x[20+n:]
report={'scope':'One bounded read-only exported rig foundation diagnostic167; no repairs, GPU, browser or source mutations','frozenUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourceFiles':[{'path':x['source'],'SHA256':x['SHA256']}for x in raw['sources']],'fixture':{'path':fixture['fixture'],'SHA256':fixture['fixtureSHA256']},'C19Source34BINChunkExact':binchunk(c19)==binchunk(g34),'recipeAndInspectedDependencies':[{'path':str(p),'SHA256':sha(p)}for p in paths],'evidenceFiles':[{'path':str(p),'SHA256':sha(p)}for p in O.glob('*')if p.name!='freeze.json'],'privateInputs':[{'path':str(p),'SHA256':sha(p)}for p in S.glob('*')],'runtime':{'node':subprocess.check_output(['node','--version'],text=True).strip(),'threads':'OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 UV_THREADPOOL_SIZE=2','Three':'installed stock loader via repository pnpm; see pnpm-lock dependency hash','pnpmLockSHA256':sha(R/'pnpm-lock.yaml')},'gates':{'sourceRestAndInverseBindRetention':'MEASURED EXACT','actualAttachedBindingAndSkinOrder':'MEASURED','actualRawAttributesAndExplicitLoaderNormalization':'MEASURED','centralCoreUnilateralMotion':'MEASURED ZERO in explicit ROI','anatomicalPivotAcceptance':'UNMEASURED','visibleMovingArtContact':'UNMEASURED','productionPhysicsReplay':'UNMEASURED','gameReady':'NOT ACCEPTED'},'parentOwnsJudgment':True}
(O/'freeze.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'evidence':len(report['evidenceFiles']),'recipes':len(list(A.glob('*'))),'privateInputs':len(report['privateInputs']),'C19Source34BINExact':report['C19Source34BINChunkExact']}))
