"""Read-only continuous triangle/cylinder and played vertex-buffer witnesses."""
import hashlib,json,math
from pathlib import Path
import numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
ROOT=Path('/Users/raynos/projects/games/rockhop');BASE=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');OUT=ROOT/'docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/native-grip01';RUN=BASE/'rig-adapter01/native-grip01';LAND=OUT.parent/'native-landmarks'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
p=RUN/'native-hand-animation.npz';d=np.load(p);rest=d['sourcePositions'];frames=d['framePositions'];tris=d['triangleIndices'];centre=d['cylinderCentre'];axis=d['cylinderAxis'];radius=float(d['cylinderRadius']);wrist=d['wristLoopLocalIds'];ids=d['sourceCompleteVertexIds'];h=json.loads((LAND/'report.json').read_text())['hands'][0];normal=-np.array(h['sourceCanonicalNormalMapped']);length=np.array(h['palmLongAxisWristToMCP']);weights=json.loads((LAND/'native-weight-transfer-map.json').read_text())['matches'][0]['nativeWeights']
basiscross=np.cross(rest[tris[:,1]]-rest[tris[:,0]],rest[tris[:,2]]-rest[tris[:,0]]);basearea=np.linalg.norm(basiscross,axis=1);result=[]
def continuous(p):
 q=p-centre;axial=q@axis;projected=np.stack([q@normal,q@length],axis=1);t=projected[tris];a=t;b=np.roll(t,-1,axis=1);edge=b-a;cross=a[:,:,0]*b[:,:,1]-a[:,:,1]*b[:,:,0];inside=(cross.min(1)>=-1e-15)|(cross.max(1)<=1e-15);u=np.clip(-np.sum(a*edge,axis=2)/np.maximum(np.sum(edge*edge,axis=2),1e-18),0,1);nearest=a+u[:,:,None]*edge;dist=np.linalg.norm(nearest,axis=2).min(1);dist[inside]=0;included=(np.max(np.abs(axial[tris]),axis=1)<=.08);return dist,included
for fi,p in enumerate(frames):
 rad=p-centre;rad-=np.outer(rad@axis,axis);r=np.linalg.norm(rad,axis=1);dist,included=continuous(p);penetration=np.maximum(radius-dist,0)*included;cross=np.cross(p[tris[:,1]]-p[tris[:,0]],p[tris[:,2]]-p[tris[:,0]]);area=np.linalg.norm(cross,axis=1);cos=np.sum(cross*basiscross,axis=1)/np.maximum(area*basearea,1e-18)
 result.append({'frame':fi,'finite':bool(np.isfinite(p).all()),'maximumWristRimDeltaM':float(np.linalg.norm(p[wrist]-rest[wrist],axis=1).max()),'minimumTriangleAreaRatio':float((area/np.maximum(basearea,1e-18)).min()),'restNormalOppositionCountDiagnosticOnly':int((cos<0).sum()),'maximumContinuousTriangleCylinderPenetrationM':float(penetration.max()),'trianglesPenetratingCylinderOver1mm':int((penetration>.001).sum()),'maximumVertexCylinderPenetrationM':float(np.maximum(radius-r,0).max()),'allHandTrianglesWithinFiniteCylinderAxialLength':bool(included.all())})
p=frames[16];contact=[]
for finger in range(1,6):
 indices=[vi for vi,gs in enumerate(weights) if sum(w for n,w in gs if n.startswith(f'finger{finger}-') and n.endswith('.L'))>.5];q=p[indices]-centre;q-=np.outer(q@axis,axis);gap=np.linalg.norm(q,axis=1)-radius;nearest=np.argsort(np.abs(gap))[:5];contact.append({'finger':finger,'nativeSurfaceWitnesses':[{'completeVertexId':int(ids[indices[i]]),'point':p[indices[i]].tolist(),'radialGapM':float(gap[i])} for i in nearest],'minimumAbsoluteGapM':float(np.abs(gap).min()),'surfaceVerticesWithin1mmOfCylinder':int((np.abs(gap)<=.001).sum())})
def overlaps(p):
 b=BVHTree.FromPolygons([Vector(v) for v in p],tris.tolist(),all_triangles=True);pairs=[(a,c) for a,c in b.overlap(b) if a<c and not(set(tris[a])&set(tris[c]))];return pairs
restpairs=overlaps(rest);wrappairs=overlaps(frames[16]);sources={p:sha(Path(p)) for p in json.loads((LAND/'report.json').read_text())['sourceHashesBefore'] if p.endswith('rider.blend') or p.endswith('fresh-anatomical-source.blend')};old=json.loads((LAND/'report.json').read_text())['sourceHashesBefore'];assert all(sources[p]==old[p] for p in sources)
report={'status':'Actualbuffergeometryaudit; buildendedafterbufferexportwithmetadataTypeError; notacceptedgrip','sourceHashesAfter':sources,'frameBufferSHA256':sha(RUN/'native-hand-animation.npz'),'candidateMorphDeltaSHA256':hashlib.sha256(d['morphDelta'].tobytes()).hexdigest(),'mappedCompleteVertices':len(ids),'restByteExact':bool(np.array_equal(frames[0],rest)),'lastOpenMaximumDeltaM':float(np.linalg.norm(frames[-1]-rest,axis=1).max()),'cylinderCentre':centre.tolist(),'cylinderAxis':axis.tolist(),'radiusM':radius,'nativeJointAnglesDegrees':dict(zip(d['parameterNames'].tolist(),np.degrees(d['anglesRadians']).tolist())),'frameChecks':result,'wrappedFingerContacts':contact,'nonadjacentTriangleBVH':{'restPairs':len(restpairs),'wrappedPairs':len(wrappairs),'newPairs':len(set(wrappairs)-set(restpairs)),'wrappedExamples':wrappairs[:50],'status':'BVH triangle overlap diagnostic excludes shared-vertex pairs; requires inspection, notanacceptedselfintersectioncertificate'},'recipeSHA256':sha(Path(__file__)),'limits':['Independent actualskinpoints and continuousprojectedtrianglecircledistances measured, not invented sockets.','Projectedtriangle distances only certify finitecylinder where entiretriangle lies within80mmaxialbound; reportedperframe.','Against-rest normal opposition reflects fingerrotation too; it is explicitly not a foldpass/fail.','No game/19bone/contact acceptance claim.']}
(OUT/'buffer-audit.json').write_text(json.dumps(report,indent=2)+'\n');print('ACTUAL_NATIVE_BUFFER_AUDIT_FROZEN',flush=True)
