"""Gate one four-boundary yoke before motion. No repair or candidate export."""
from pathlib import Path
import ast,hashlib,json,time
import numpy as np
from scipy.spatial import cKDTree
REPO=Path('/Users/raynos/projects/games/rockhop');ROOT=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');RUN=ROOT/'garment-rebuild01/upper-yoke156';OUT=REPO/'docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/upper-yoke156'
f=np.load(RUN/'yoke-instrument.npz');P=f['positions'];T=f['triangles'];HP=f['protectedHoodPositions'];HT=f['protectedHoodTriangles'];ring=f['protectedRingIDs'];aliases=f['protectedHoodAliases'];free=f['freeDeformedNativeVertexIDs'];N=f['normals'];W=f['weights']
# Same explicitly scoped strict crossing verifier as155, adapted to noncontiguous
# upper-yoke changed-face IDs. Does not execute or mutate the prior recipe.
prior=REPO/'assets/blender/hero-remaster/rider/one-rider-v2/garment-rebuild01/shoulder-transition155/audit.py';tree=ast.parse(prior.read_text());code='\n'.join(ast.unparse(x) for x in tree.body if isinstance(x,ast.FunctionDef) and x.name in ['segment_triangle','intersections']);code=code.replace('(candidates < transitionIDs[0]) | (candidates > i)', '(~changedMask[candidates]) | (candidates > i)')
assert '(~changedMask[candidates])' in code
combined=np.concatenate([P,HP]);combinedT=np.concatenate([T,HT+len(P)]);_,inv=np.unique(combined,axis=0,return_inverse=True);ids=inv[combinedT];changedMask=np.r_[np.isin(T,np.r_[free,ring]).any(1),np.zeros(len(HT),bool)];transitionIDs=np.where(changedMask)[0];exec(compile(code,str(prior),'exec'),globals());start=time.monotonic();result=intersections(combined)
cross=np.cross(P[T[:,1]]-P[T[:,0]],P[T[:,2]]-P[T[:,0]]);area=np.linalg.norm(cross,axis=1)/2;norm=np.linalg.norm(cross,axis=1,keepdims=True);unit=cross/np.maximum(norm,1e-20);dot=np.einsum('ij,ij->i',unit,N[T].mean(1));reference=f['sourceReferencePositions'];initialCross=np.cross(reference[T[:,1]]-reference[T[:,0]],reference[T[:,2]]-reference[T[:,0]]);initialDots=np.einsum('ij,ij->i',unit,initialCross/np.maximum(np.linalg.norm(initialCross,axis=1,keepdims=True),1e-20))
c=np.load(ROOT/'garment-rebuild01/cage04/fit04.npz');outside=f['nativeUnchangedVertexIDs'];np.testing.assert_array_equal(P[outside],c['positions'][outside]);np.testing.assert_array_equal(W[outside],c['weights'][outside]);np.testing.assert_array_equal(P[ring],HP[aliases]);np.testing.assert_array_equal(N[ring],f['protectedHoodNormals'][aliases]);np.testing.assert_array_equal(W[ring],f['protectedHoodWeights'][aliases]);
report={'status':'Rest gate failure evidence; no model/appearance/rig acceptance','instrumentSHA256':hashlib.sha256((RUN/'yoke-instrument.npz').read_bytes()).hexdigest(),'priorVerifierSourceSHA256':hashlib.sha256(prior.read_bytes()).hexdigest(),'changedYokeTriangles':len(transitionIDs),'crossingScope':'Every triangle incident to deformed upper native vertices or new protected-boundary vertices against all nonadjacent native/new/hood triangles, deduplicated pairs','strictIntersectionAudit':result,'minimumAreaM2':float(area.min()),'zeroAreaTriangles':int((area<1e-12).sum()),'negativeTriangleDotToScaffold':int((initialDots<0).sum()),'negativeTriangleDotToCandidateVertexNormals':int((dot<0).sum()),'protectedSeamAndNativeOutsideExact':True,'motionProbeRun':False,'motionDecision':'Do not proceed to480 motion after rest crossings/opposition already fail. One construction archived, no refinement sweep.','seconds':time.monotonic()-start,'limits':['Strict noncoplanar crossings only; coplanar overlap and exact-rest shared-vertex pairs excluded.','Source head immutable reference, not included in these intersection queries.','No complete GLB, PBR bake, movie or face/body score.']}
(OUT/'rest-audit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='strictIntersectionAudit'}|{'crossings':{k:v for k,v in result.items() if k!='literalTrianglePairs'}},indent=2))
