"""Publish only parent-reviewed actual clips, retaining the existing comparison."""
from pathlib import Path
import json,shutil,hashlib
from PIL import Image
repo=Path('/Users/raynos/projects/games/rockhop');base=repo/'docs/evidence/hero-remaster/one-rider-v2/rig-adapter01';site=repo/'harness/out/hero-remaster/rider-review-site';media=site/'dist/media';recipe=repo/'assets/blender/hero-remaster/rider/one-rider-v2/rig-adapter01/body-bind11/sitting-multiangle01/review.html';rows=[];cards=[]
for angle,label in [('side','Side'),('rear-three-quarter','Rear three-quarter')]:
 for surface in ['textured','gray']:
  folder=base/'body-bind19/morph01/played'/angle/surface;r=json.loads((folder/'report.json').read_text());assert r['sourceSHA256']=='a43e64471671877cf4a9c9b98e04a8c2172298f61e923241618d273f1b9bbd91' and r['hipReviewDriver'] and len(r['samples'])==264
  stem=f'hip19-{angle}-{surface}';shutil.copy2(folder/'played.mp4',media/f'{stem}.mp4');a=json.loads((folder/'frames-archive.json').read_text());Image.open(Path(a['privateDecodedFrames'])/'0076.png').convert('RGB').save(media/f'{stem}.jpg',quality=94);shutil.copy2(folder/'decoded-003.jpg',media/f'{stem}-frames.jpg')
  cards.append(f'<article class="card"><div class="label"><h3>{label} · {surface}</h3></div><video controls muted playsinline loop preload="metadata" poster="media/{stem}.jpg" src="media/{stem}.mp4"></video><div class="links"><a href="media/{stem}.mp4">Open video</a><a href="media/{stem}-frames.jpg">Landing sequence</a></div></article>');rows.append({'source':str(folder/'played.mp4'),'sourceSHA256':r['sourceSHA256'],'video':stem+'.mp4','videoSHA256':hashlib.sha256((media/f'{stem}.mp4').read_bytes()).hexdigest()})
section='<section id="latest-comparison"><h2>New hip correction · still in progress</h2><p>The rear silhouette is rounder and the collapsed strip is reduced. Tight folds at the groin and thighs remain. Compare these clips with the existing rider below: same input, poses, camera and lighting.</p><section class="gameplay">'+''.join(cards)+'</section>'
cards=[]
for surface in ['textured','gray']:
 folder=base/'body-bind20/played01'/surface;r=json.loads((folder/'report.json').read_text());r['sourceSHA256']='1f5035eeb5de708d70c889af89e574a0b7be10bcdc73beed7d1e4393fb21dd28';assert any(x['sha256']==r['sourceSHA256'] for x in r['loaded']) and len(r['samples'])==72
 stem='eye20-'+surface;shutil.copy2(folder/'played.mp4',media/f'{stem}.mp4');a=json.loads((folder/'frames-archive.json').read_text());Image.open(Path(a['privateMovieDecodedFrames'])/'0019.png').convert('RGB').save(media/f'{stem}.jpg',quality=94);shutil.copy2(base/f'body-bind20/played01/actual-before-after-{surface}.jpg',media/f'{stem}-comparison.jpg')
 cards.append(f'<article class="card"><div class="label"><h3>Eye graft · {surface}</h3></div><video controls muted playsinline loop preload="metadata" poster="media/{stem}.jpg" src="media/{stem}.mp4"></video><div class="links"><a href="media/{stem}.mp4">Open video</a><a href="media/{stem}-comparison.jpg">Before / after closeup</a></div></article>');rows.append({'source':str(folder/'played.mp4'),'sourceSHA256':r['sourceSHA256'],'video':stem+'.mp4','videoSHA256':hashlib.sha256((media/f'{stem}.mp4').read_bytes()).hexdigest()})
section+='<h2>Eye graft · appearance rejected</h2><p>The new eyelids fit without intersecting the eyes, but the textured closeup still has a dark mottled ring. Face score:6.3/10, below the7/10 minimum. This test is preserved so you can see why it needs further work.</p><section class="gameplay">'+''.join(cards)+'</section></section>'
html=recipe.read_text();assert 'id="latest-comparison"' not in html;html=html.replace('<h2>Hip deformation during riding</h2>',section+'<h2>Existing rider · hip deformation during riding</h2>');recipe.write_text(html);(site/'dist/index.html').write_text(html)
out=base/'body-bind19/gallery122';out.mkdir(parents=True,exist_ok=True);(out/'site-media.json').write_text(json.dumps(rows,indent=2)+'\n');print(json.dumps({'newClips':len(rows),'totalVideos':html.count('<video ')}))
