"""Test actual garment-wall crossings along four anatomical wearer paths."""
import argparse, collections, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','field','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,field,out=[Path(getattr(a,k)).resolve() for k in ['source','field','out']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,field]};assert pins[str(source)]=='86b85d476b13f709ba832e11dfcd14a17f071f5af69f3ebbbaf7dd1dbe6f58f9';f=np.load(field);bpy.ops.wm.open_mainfile(filepath=str(source));g=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];rig=bpy.data.objects['Independent anatomical foundation rig'];g.data.calc_loop_triangles();p=np.array([v.co[:] for v in g.data.vertices]);tri=np.array([t.vertices[:] for t in g.data.loop_triangles]);assert np.array_equal(p,f['finalNativeXYZ']) and np.array_equal(tri,f['triangles']);a0=p[tri[:,0]];e1=p[tri[:,1]]-a0;e2=p[tri[:,2]]-a0
head=lambda n:np.array(rig.data.bones[n].head_local,dtype=float);tail=lambda n:np.array(rig.data.bones[n].tail_local,dtype=float)
paths={'hem': [('pelvis.head',head('pelvis')),('spine.head',head('spine')),('spine.tail',tail('spine')),('chest.head',head('chest')),('chest.tail',tail('chest'))], 'neck':[('chest.tail',tail('chest')),('neck.head',head('neck')),('neck.tail',tail('neck')),('head.tail',tail('head'))]}
for side in ['R','L']:paths['cuff.'+side]=[('hand.'+side+'.tail',tail('hand.'+side)),('hand.'+side+'.head',head('hand.'+side)),('forearm.'+side+'.head',head('forearm.'+side)),('upperArm.'+side+'.head',head('upperArm.'+side)),('chest.tail',tail('chest'))]
reports={};epsilon=1e-9
for name,path in paths.items():
    segments=[];allhits=[]
    for k in range(len(path)-1):
        label,start=path[k];endlabel,end=path[k+1];d=end-start;cross=np.cross(np.broadcast_to(d,e2.shape),e2);det=np.einsum('ij,ij->i',e1,cross);valid=np.abs(det)>1e-12;safe=np.where(valid,det,1);s=start-a0;u=np.einsum('ij,ij->i',s,cross)/safe;q=np.cross(s,e1);v=q@d/safe;t=np.einsum('ij,ij->i',e2,q)/safe;hit=np.flatnonzero(valid&(u>=-epsilon)&(v>=-epsilon)&(u+v<=1+epsilon)&(t>=-epsilon)&(t<=1+epsilon));witnesses=[]
        for i in hit:
            witness={'garmentTriangle':int(i),'segmentFraction':float(t[i]),'intersectionXYZ':(start+t[i]*d).tolist(),'barycentric':[float(1-u[i]-v[i]),float(u[i]),float(v[i])],'garmentXYZ':p[tri[i]].tolist(),'originalDonorPolygon':int(g.data.attributes['simplified_donor_polygon'].data[g.data.loop_triangles[int(i)].polygon_index].value)};witnesses.append(witness);allhits.append(witness)
        segments.append({'startLabel':label,'endLabel':endlabel,'startXYZ':start.tolist(),'endXYZ':end.tolist(),'lengthM':float(np.linalg.norm(d)),'wallHits':witnesses})
    reports[name]={'wallHits':len(allhits),'segments':segments,'finitePathClear':not allhits}
result={'status':'UNACCEPTED native wearer centreline air-path audit','pins':pins,'recipeSHA256':sha(__file__),'paths':reports,'allFourFinitePathsClear':all(x['finitePathClear'] for x in reports.values()),'bodyPairs':len(f['bodyTrianglePairs']),'selfPairs':len(f['selfTrianglePairs']),'method':'Double-precision Moller-Trumbore intersection of every specified finite anatomical centreline segment against all24359saved native triangles; explicit barycentric/parameter witnesses. Four outside cuff/hem/neck paths connect to chest, no source rewrite.','limits':['A clear centreline proves only that specified zero-radius polyline misses garment walls. It is not a full finite-radius wearer capsule, coverage/containment or continuous-volume air-port proof.','Near-parallel/coplanar segment cases are excluded by determinant threshold; no exact robust-predicate theorem. Anatomical bones need not represent every body cross-section centre.','Rest0body/0self does not authorize rig/motion/playedappearance/M0-M5/mobile acceptance. No source save/capture/body-head-51bind change/inference/worker/Library/player promotion.']};assert pins=={x:sha(x) for x in pins};out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(result,indent=2)+'\n');print('NATIVE_AIR_PATHS', {k:v['wallHits'] for k,v in reports.items()},flush=True)
