"""Apply unchanged historical body coverage mask to the actual donor fit."""
import argparse, collections, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','field','historical-recipe','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,field,recipe,out=[Path(getattr(a,k.replace('-','_'))).resolve() for k in ['source','field','historical-recipe','out']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,field,recipe]};assert pins[str(source)]=='86b85d476b13f709ba832e11dfcd14a17f071f5af69f3ebbbaf7dd1dbe6f58f9';f=np.load(field);bpy.ops.wm.open_mainfile(filepath=str(source));garment=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];garment.data.calc_loop_triangles();p=np.array([v.co[:] for v in garment.data.vertices]);tri=np.array([t.vertices[:] for t in garment.data.loop_triangles]);assert np.array_equal(p,f['finalNativeXYZ']) and np.array_equal(tri,f['triangles']);gt=BVHTree.FromPolygons([Vector(v) for v in p],tri.tolist(),all_triangles=True)
# Execute exact historical mask and ray test; do not narrow misses away.
code=recipe.read_text();start=code.index('coverage=[]');exec(compile(code[start:code.index('report={',start)],str(recipe),'exec'));classes=collections.Counter();misses=[];allRows=[]
for row in coverage:
    vertex=body.data.vertices[row['bodyVertex']];weights={body.vertex_groups[g.group].name:g.weight for g in vertex.groups};deform={n:w for n,w in weights.items() if n in bpy.data.objects['Independent anatomical foundation rig'].data.bones};dominant=max(deform,key=deform.get);classes[dominant]+=1;item=dict(row,dominantRawBone=dominant,bodyXYZ=list(vertex.co),bodyNormal=list(body.data.vertex_normals[vertex.index].vector),weights=weights);allRows.append(item)
    if not row['hit']:misses.append(item)
result={'status':'UNACCEPTED actual donor unchanged-mask rest coverage audit','pins':pins,'recipeSHA256':sha(__file__),'exactHistoricalMaskAndRayCodeReused':True,'coverageRays':len(coverage),'coverageMisses':len(misses),'testedDominantRawBoneClasses':dict(classes),'allCoverageMissWitnesses':misses,'allCoverageRays':allRows,'mask':'(sum upperArm+forearm weights >.8 OR sum spine/chest/pelvis >.8) AND nativeZ>1.04; start bodyvertex+normal1um, normal ray maximum0.20m. Exact historical source13 verification recipe fragment.','bodyPairs':len(f['bodyTrianglePairs']),'selfPairs':len(f['selfTrianglePairs']),'limits':['A hit within0.20m is a directional coverage proxy, not correct inner-wall nesting, fullbody containment,wearer ease or moving wearing proof. Exact mask excludes intended bare head/hands/lower body through weight/Z proxies; no new exclusions.','No source save/body-head-51bind mutation, capture/rig/motion/inference/worker/Library/player promotion or art/M0-M5/mobile acceptance.']};assert pins=={x:sha(x) for x in pins};out.write_text(json.dumps(result,indent=2)+'\n');print('ACTUAL_DONOR_COVERAGE','rays',len(coverage),'misses',len(misses),flush=True)
