"""Reproduce saved compact-flow native contacts and actual inverse closure."""
import argparse, collections, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','field','report','recipe','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,field,report,recipe,out=[Path(getattr(a,k)).resolve() for k in ['source','field','report','recipe','out']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,field,report,recipe]};f=np.load(field);r=json.loads(report.read_text());assert pins[str(source)]==r['candidateSHA256'] and pins[str(field)]==r['fieldSHA256'];controls=[]
for name,c in r['controls'].items():
    head=np.array(c['headM']);axis=np.array(c['axis']);projection=np.eye(3)-np.outer(axis.astype(np.float32),axis.astype(np.float32));controls.append((head,axis,c['lengthM'],projection,np.array(c['bodyCentreLineCoefficientsM']),np.log(c['measuredUniformScale']),c['axialCoreStations'],c['axialFadeWidthStations'],c['radialCoreM'],c['radialFadeM']))
code=recipe.read_text();start=code.index('def taper(');exec(compile(code[start:code.index('proposed=integrate(',start)],str(recipe),'exec'));ideal=integrate(f['previousNativeXYZ']);idealDifference=np.linalg.norm(ideal-f['idealIntegratedXYZ'],axis=1);assert idealDifference.max()<1e-10;inverse=integrate(f['finalNativeXYZ'],-1);inverseError=np.linalg.norm(inverse-f['previousNativeXYZ'],axis=1);assert inverseError.max()<1e-6
bpy.ops.wm.open_mainfile(filepath=str(source));g=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];g.data.calc_loop_triangles();body.data.calc_loop_triangles();p=np.array([v.co[:] for v in g.data.vertices]);tri=np.array([t.vertices[:] for t in g.data.loop_triangles]);bp=np.array([v.co[:] for v in body.data.vertices]);bt=np.array([t.vertices[:] for t in body.data.loop_triangles]);assert np.array_equal(p,f['finalNativeXYZ']) and np.array_equal(tri,f['triangles']);gt=BVHTree.FromPolygons([Vector(v) for v in p],tri.tolist(),all_triangles=True);bvh=BVHTree.FromPolygons([Vector(v) for v in bp],bt.tolist(),all_triangles=True);contacts=sorted(gt.overlap(bvh));sp=sorted((i,j) for i,j in gt.overlap(gt) if i<j and not set(tri[i])&set(tri[j]));assert contacts==sorted(map(tuple,f['bodyTrianglePairs'])) and sp==sorted(map(tuple,f['selfTrianglePairs']));edges=collections.Counter(tuple(sorted((ids[k],ids[(k+1)%len(ids)]))) for poly in g.data.polygons for ids in [list(poly.vertices)] for k in range(len(ids)));free=sorted({v for e,n in edges.items() if n==1 for v in e});assert np.array_equal(p[free],f['previousNativeXYZ'][free]);assert np.all(f['sampledJacobianDeterminants']>0)
result={'status':'UNACCEPTED saved compact interior-flow reproduction','pins':pins,'recipeSHA256':sha(__file__),'savedNativePositionsTrianglesContactArraysExact':True,'serializedControlIdealForwardClosureMaxM':float(idealDifference.max()),'actualSavedNativeInverseClosureMaxM':float(inverseError.max()),'bodyPairs':len(contacts),'selfPairs':len(sp),'allActualBoundaryVerticesExact':len(free),'sampledJacobiansPositive':len(f['sampledJacobianDeterminants']),'projectorPrecision':'Reproduce executed float32 bone-axis outer product before float64 identity subtraction; serialized scalar controls preserved.','limits':['Zero rest contact pairs are native surface gates only; no whole-volume injectivity,4mmclearance,body containment,actual wearer air ports,rig/motion/playedappearance/M0-M5/mobile acceptance.','No native save, source/body-head-51bind mutation/capture/inference/worker/Library/player promotion.']};assert pins=={x:sha(x) for x in pins};out.write_text(json.dumps(result,indent=2)+'\n');print('SAVED_COMPACT_INTERIOR_EXACT','body',len(contacts),'self',len(sp),'inverseM',float(inverseError.max()),flush=True)
