"""Encode actual native-four FK proof from three fixed camera views."""
import argparse, hashlib, json, subprocess, tempfile
from pathlib import Path
ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--review',required=True);ap.add_argument('--out',required=True);a=ap.parse_args();review=Path(a.review).resolve();output=Path(a.out).resolve();assert not output.exists();r=json.loads(review.read_text());root=review.parent;temp=Path(tempfile.mkdtemp(prefix='rockhop-agent1-review85-'));sequence=r['movieFrameSequence'];fps=r['sourceFramesPerSecond'];duration=len(sequence)/fps;manifests=[]
assert len(r['variants'])==3
for key in [v['key'] for v in r['variants']]:
    lines=['ffconcat version 1.0']
    for index in sequence:
        png=root/key/f'{index:04d}.png';assert png.exists();lines.extend([f"file '{png.as_posix()}'",f'duration {1/fps:.17g}'])
    last=root/key/f'{sequence[-1]:04d}.png';lines.append(f"file '{last.as_posix()}'");manifest=temp/(key+'.ffconcat');manifest.write_text('\n'.join(lines)+'\n');manifests.append(manifest)
command=['/opt/homebrew/bin/ffmpeg','-v','warning']
for manifest in manifests:command.extend(['-safe','0','-f','concat','-i',str(manifest)])
command.extend(['-filter_complex','[0:v]fps=24[a];[1:v]fps=24[b];[2:v]fps=24[c];[a][b][c]hstack=inputs=3[v]','-map','[v]','-t',f'{duration:.17g}','-an','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',str(output)]);encoded=subprocess.run(command,check=True,capture_output=True,text=True);probe=json.loads(subprocess.check_output(['/opt/homebrew/bin/ffprobe','-v','error','-show_streams','-show_format','-of','json',str(output)],text=True));streams=probe['streams'];assert len(streams)==1 and streams[0]['codec_type']=='video';video=streams[0];assert video['width']==1920 and video['height']==640 and video['avg_frame_rate']=='24/1';assert abs(float(video['duration'])-duration)<.05;assert int(video['nb_frames'])==round(duration*24);decoded=subprocess.run(['/opt/homebrew/bin/ffmpeg','-v','error','-i',str(output),'-f','null','-'],check=True,capture_output=True,text=True);assert not decoded.stderr.strip();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();result={'status':'UNACCEPTED failed native-four FK proof movie encode/decode','recipeSHA256':sha(Path(__file__).resolve()),'reviewSHA256':sha(review),'movieSHA256':sha(output),'movie':str(output),'bytes':output.stat().st_size,'durationS':duration,'video':video,'audioStreams':0,'decodedExitCode':decoded.returncode,'decodedErrors':decoded.stderr,'encoderWarnings':encoded.stderr,'timing':'Every fourth48HzFK sample at12sourceframes/sec, no pose holds; H26424fps duplicates intentionally, no motion interpolation.','limits':['Rest appearance evidence only; parent must play and judge.24coverage misses/rig/motion/M0-M5/mobile remain open. No source save/promotion/publication.']};(root/'movie.json').write_text(json.dumps(result,indent=2)+'\n');print('NATIVE_FOUR_PROOF_MOVIE_READY',result['movieSHA256'],result['bytes'],duration,flush=True)
