"""Apply one compact ambient dilation per measured interior contact region."""
import argparse, collections, gzip, hashlib, json, math, sys
from pathlib import Path
import bpy, numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','field','sections','localization','radial-recipe','previous-report','out','evidence']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,field,sections,localization,rr,previous,out,evidence=[Path(getattr(a,k.replace('-','_'))).resolve() for k in ['source','field','sections','localization','radial-recipe','previous-report','out','evidence']];out.mkdir(parents=True,exist_ok=True);evidence.mkdir(parents=True,exist_ok=True);assert not (out/'compact-interior.blend').exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,field,sections,localization,rr,previous]};assert pins[str(source)]=='aa12937cf5897591bfd9f69c7ee5080e9e96cf2e3495fe2f8c3fb891049d762b';f=np.load(field);rows=json.loads(gzip.decompress(sections.read_bytes()));lr=json.loads(localization.read_text());code=rr.read_text();start=code.index('def frame(');exec(compile(code[start:code.index('rows=[]',start)],str(rr),'exec'))
bpy.ops.wm.open_mainfile(filepath=str(source));old=bpy.data.objects['Actual selected donor, actual wrist cuff recut, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];rig=bpy.data.objects['Independent anatomical foundation rig'];native=np.array([v.co[:] for v in old.data.vertices]);assert np.array_equal(native,f['nativeXYZ']);old.data.calc_loop_triangles();oldtri=np.array([t.vertices[:] for t in old.data.loop_triangles]);g=old.copy();g.data=old.data.copy();bpy.context.collection.objects.link(g);g.name='Actual selected donor, compact interior flow, unaccepted';controls=[];reports={}
for part in ['upperArm.L','forearm.R']:
    data=sorted([x for x in rows if x['part']==part],key=lambda x:x['station']);assert all(x['usableBodyCenteredPair'] for x in data);b=rig.data.bones[part];head=np.array(b.head_local);axis=np.array(b.tail_local)-head;length=np.linalg.norm(axis);axis/=length;projection=np.eye(3)-np.outer(axis,axis);stations=np.array([x['station'] for x in data]);centres=np.array([x['bodyCentroidM'] for x in data]);coeff=np.linalg.lstsq(np.column_stack([np.ones(3),stations]),centres,rcond=None)[0];ratios=[];maxContourRadius=0.;fitCentres=[]
    for x in data:
        c=coeff[0]+coeff[1]*x['station'];fitCentres.append(c);air=dict(x['garmentSection']['contours'][x['selectedGarmentContourIndex']],centroidXYZ=c.tolist());outer=dict(x['bodySection']['contours'][x['selectedBodyContourIndex']],centroidXYZ=c.tolist());ar=radial(air,axis);br=radial(outer,axis);assert ar['centroidInsideContour'] and br['centroidInsideContour'];assert all(z is not None and z>1e-5 for z in ar['firstRadiusM']+br['firstRadiusM']);ratios.extend(((np.array(br['firstRadiusM'])+.004)/np.array(ar['firstRadiusM'])).tolist());maxContourRadius=max(maxContourRadius,float(np.linalg.norm(np.array(air['XYZ'])-c,axis=1).max()))
    scale=max(1.,max(ratios));edgeLengths=[]
    oldContactXYZ=[np.array(x['garmentXYZ']) for x in json.loads(previous.read_text())['allBodyWitnesses'] if x['dominantRawBone']==part]
    q=np.concatenate(oldContactXYZ);u=(q-head)@axis/length;core=[float(u.min()),float(u.max())]
    for t in oldContactXYZ:edgeLengths.extend(np.linalg.norm(t-np.roll(t,-1,axis=0),axis=1).tolist())
    medianEdge=float(np.median(edgeLengths));assert medianEdge>0;pad=medianEdge/length;support=[core[0]-pad,core[1]+pad];pointStations=(q-head)@axis/length;pointCentres=coeff[0]+pointStations[:,None]*coeff[1];maxContourRadius=max(maxContourRadius,float(np.linalg.norm((q-pointCentres)@projection,axis=1).max()));radialCore=scale*maxContourRadius+.004;radialSupport=radialCore+medianEdge;mid=(support[0]+support[1])/2;ballCenter=coeff[0]+coeff[1]*mid;ballRadius=float(np.linalg.norm(coeff[1])*(support[1]-support[0])/2+radialSupport)
    controls.append((head,axis,length,projection,coeff,math.log(scale),core,pad,radialCore,medianEdge));reports[part]={'headM':head.tolist(),'axis':axis.tolist(),'lengthM':length,'bodyCentreLineCoefficientsM':coeff.tolist(),'bodyCentreLineResidualMaxM':float(np.linalg.norm(np.array(fitCentres)-centres,axis=1).max()),'measuredUniformScale':scale,'directionSectionConstraints':len(ratios),'axialCoreStations':core,'axialFadeWidthStations':pad,'axialSupportStations':support,'radialCoreM':radialCore,'radialFadeM':medianEdge,'localMedianContactTriangleEdgeM':medianEdge,'supportBoundingBallCentreM':ballCenter.tolist(),'supportBoundingBallRadiusM':ballRadius,'scope':'Fixed actual-contact triangle extent, one measured median-edge fade, actual section outer radius times measured scale plus4mm; no tuning loop.'}
values=list(reports.values());separation=float(np.linalg.norm(np.array(values[0]['supportBoundingBallCentreM'])-values[1]['supportBoundingBallCentreM'])-sum(x['supportBoundingBallRadiusM'] for x in values));assert separation>0,'Control supports must be disjoint'
def taper(t):
    t=np.clip(t,0,1);return 1-10*t**3+15*t**4-6*t**5
# Velocity is a world-space function, with compact C2 kernels and no source-ID weights.
def velocity(points):
    total=np.zeros_like(points)
    for head,axis,length,projection,coeff,kappa,core,pad,radialCore,radialFade in controls:
        s=(points-head)@axis/length;c=coeff[0]+s[:,None]*coeff[1];d=(points-c)@projection;radius=np.linalg.norm(d,axis=1);axial=taper(np.maximum(core[0]-s,s-core[1])/pad);weight=axial*taper((radius-radialCore)/radialFade);total+=weight[:,None]*kappa*d
    return total
def integrate(points,sign=1):
    p=points.copy();h=sign/32
    for step in range(32):
        k1=velocity(p);k2=velocity(p+h*k1/2);k3=velocity(p+h*k2/2);k4=velocity(p+h*k3);p+=h*(k1+2*k2+2*k3+k4)/6
    return p
proposed=integrate(native);back=integrate(proposed,-1);error=np.linalg.norm(back-native,axis=1);assert error.max()<1e-6;epsilon=1e-5;jacobian=np.stack([(integrate(native+np.eye(3)[k]*epsilon)-integrate(native-np.eye(3)[k]*epsilon))/(2*epsilon) for k in range(3)],axis=2);det=np.linalg.det(jacobian);assert np.all(np.isfinite(det))
for v,q in zip(g.data.vertices,proposed):v.co=q
g.data.update();g.data.calc_loop_triangles();p=np.array([v.co[:] for v in g.data.vertices]);tri=np.array([t.vertices[:] for t in g.data.loop_triangles]);assert [x.vertices[:] for x in g.data.polygons]==[x.vertices[:] for x in old.data.polygons];assert [[v.uv[:] for v in x.data] for x in g.data.uv_layers]==[[v.uv[:] for v in x.data] for x in old.data.uv_layers];assert g.data.materials[0] is old.data.materials[0]
edges=collections.Counter(tuple(sorted((ids[k],ids[(k+1)%len(ids)]))) for poly in old.data.polygons for ids in [list(poly.vertices)] for k in range(len(ids)));boundary=sorted({v for e,n in edges.items() if n==1 for v in e});assert np.array_equal(p[boundary],native[boundary]),'Actual wearer boundaries must remain fixed'
body.data.calc_loop_triangles();bp=np.array([v.co[:] for v in body.data.vertices]);bt=np.array([t.vertices[:] for t in body.data.loop_triangles])
def tree(q,t):return BVHTree.FromPolygons([Vector(v) for v in q],t.tolist(),all_triangles=True)
def selfpairs(b,t):return sorted((i,j) for i,j in b.overlap(b) if i<j and not set(t[i])&set(t[j]))
gt=tree(p,tri);bvh=tree(bp,bt);fixed=tree(p,oldtri);contacts=sorted(gt.overlap(bvh));sp=selfpairs(gt,tri);fixedContacts=sorted(fixed.overlap(bvh));fixedSelf=selfpairs(fixed,oldtri);old.hide_set(True);old.hide_render=True;g.hide_set(False);g.hide_render=False;g['accepted']=False;g['constructionStage']='One measured compact interior flow; unrigged/unaccepted';bpy.ops.wm.save_as_mainfile(filepath=str(out/'compact-interior.blend'),compress=True);np.savez_compressed(out/'compact-interior.npz',previousNativeXYZ=native,finalNativeXYZ=p,idealIntegratedXYZ=proposed,triangles=tri,previousTriangles=oldtri,bodyTrianglePairs=np.array(contacts),selfTrianglePairs=np.array(sp),fixedBodyTrianglePairs=np.array(fixedContacts),fixedSelfTrianglePairs=np.array(fixedSelf),sampledJacobians=jacobian,sampledJacobianDeterminants=det,idealRoundtripErrorsM=error)
result={'status':'UNACCEPTED measured compact donor interior-flow construction','pins':pins,'recipeSHA256':sha(__file__),'candidateSHA256':sha(out/'compact-interior.blend'),'fieldSHA256':sha(out/'compact-interior.npz'),'controls':reports,'supportBoundingBallSeparationM':separation,'vertices':len(p),'triangles':len(tri),'bodyPairs':len(contacts),'selfPairs':len(sp),'fixedPreviousTessellationBodyPairs':len(fixedContacts),'fixedPreviousTessellationSelfPairs':len(fixedSelf),'changedLoopTriangles':int(np.any(tri!=oldtri,axis=1).sum()),'changedVerticesAbove1um':int((np.linalg.norm(p-native,axis=1)>1e-6).sum()),'maximumDeltaM':float(np.linalg.norm(p-native,axis=1).max()),'allActualBoundaryVerticesExact':len(boundary),'polygonCyclesUVExactOriginalMaterial':True,'idealForwardInverseMaxM':float(error.max()),'sampledJacobianDeterminantPercentiles':np.percentile(det,[0,50,95,100]).tolist(),'nonPositiveSampledJacobians':int((det<=0).sum()),'limits':['Measured six planes/64directions derive one local dilation, not whole-surface4mm/containment/capsule/actual-air-port guarantee. Independent native contacts remain gates.','Compact C2 ambient flow and disjoint support bounding balls motivate coherence; finite RK4/inverse/Jacobian samples do not prove global numerical injectivity or rendered-triangle contact freedom.','No rig/motion/capture/body-head-51bind mutation/inference/worker/Library/player promotion or art/M0-M5/mobile acceptance; original-data scoped preservation needs independent audit.']};assert pins=={x:sha(x) for x in pins};(evidence/'construction.json').write_text(json.dumps(result,indent=2)+'\n');print('COMPACT_INTERIOR_FLOW_READY','body',len(contacts),'self',len(sp),'scales',{k:v['measuredUniformScale'] for k,v in reports.items()},'jacmin',float(det.min()),flush=True)
