"""Locate all unchanged-mask coverage misses, without excusing or removing any."""
import argparse, collections, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','coverage','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,coverage,out=[Path(getattr(a,k)).resolve() for k in ['source','coverage','out']];assert not out.exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,coverage]};assert pins[str(source)]=='86b85d476b13f709ba832e11dfcd14a17f071f5af69f3ebbbaf7dd1dbe6f58f9';cr=json.loads(coverage.read_text());assert cr['coverageMisses']==24;bpy.ops.wm.open_mainfile(filepath=str(source));g=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];rig=bpy.data.objects['Independent anatomical foundation rig'];g.data.calc_loop_triangles();body.data.calc_loop_triangles();p=np.array([v.co[:] for v in g.data.vertices]);tri=np.array([t.vertices[:] for t in g.data.loop_triangles]);bp=np.array([v.co[:] for v in body.data.vertices]);bt=np.array([t.vertices[:] for t in body.data.loop_triangles]);gt=BVHTree.FromPolygons([Vector(v) for v in p],tri.tolist(),all_triangles=True);bvh=BVHTree.FromPolygons([Vector(v) for v in bp],bt.tolist(),all_triangles=True);counts=collections.Counter(tuple(sorted((ids[k],ids[(k+1)%len(ids)]))) for poly in g.data.polygons for ids in [list(poly.vertices)] for k in range(len(ids)));free=np.array([e for e,n in counts.items() if n==1]);ea=p[free[:,0]];eb=p[free[:,1]];ed=eb-ea;ed2=(ed*ed).sum(1);records=[]
def ray(tree,origin,normal):
    location,n,index,distance=tree.ray_cast(Vector(origin),Vector(normal),2.);return {'hit':location is not None,'distanceM':distance if location is not None else None,'triangle':index if location is not None else None,'XYZ':list(location) if location is not None else None}
for x in cr['allCoverageMissWitnesses']:
    vertex=body.data.vertices[x['bodyVertex']];q=np.array(vertex.co);normal=np.array(body.data.vertex_normals[vertex.index].vector);assert np.array_equal(q,np.array(x['bodyXYZ'])) and np.array_equal(normal,np.array(x['bodyNormal']));origin=q+normal*1e-6;clothing=ray(gt,origin,normal);again=ray(bvh,origin,normal);short=gt.ray_cast(Vector(origin),Vector(normal),.20);assert short[0] is None;u=np.clip(np.einsum('ij,ij->i',q-ea,ed)/np.maximum(ed2,1e-20),0,1);nearest=ea+u[:,None]*ed;dist=np.linalg.norm(nearest-q,axis=1);i=int(dist.argmin());near=gt.find_nearest(Vector(q));b=rig.data.bones[x['dominantRawBone']];head=np.array(b.head_local);axis=np.array(b.tail_local)-head;length=np.linalg.norm(axis);axis/=length;station=float((q-head)@axis/length);reentry=again['hit'] and (not clothing['hit'] or again['distanceM']<clothing['distanceM']);records.append({'bodyVertex':x['bodyVertex'],'dominantRawBone':x['dominantRawBone'],'bodyXYZ':x['bodyXYZ'],'normal':x['bodyNormal'],'normalRayGarmentUpTo2m':clothing,'normalRayBodyReentryUpTo2m':again,'bodyReentryBeforeAnyGarment':reentry,'nearestActualFreeEdgeDistanceM':float(dist[i]),'nearestActualFreeEdgeVertexIDs':free[i].tolist(),'nearestActualFreeEdgeXYZ':nearest[i].tolist(),'nearestGarmentSurfaceDistanceM':near[3],'nativeDominantBoneStation':station})
summary={}
for part in sorted({x['dominantRawBone'] for x in records}):
    rows=[x for x in records if x['dominantRawBone']==part];summary[part]={'misses':len(rows),'bodyReentryBeforeGarment':sum(x['bodyReentryBeforeAnyGarment'] for x in rows),'garmentHitWithin2m':sum(x['normalRayGarmentUpTo2m']['hit'] for x in rows),'freeEdgeDistanceMRange':[min(x['nearestActualFreeEdgeDistanceM'] for x in rows),max(x['nearestActualFreeEdgeDistanceM'] for x in rows)],'nativeBoneStationRange':[min(x['nativeDominantBoneStation'] for x in rows),max(x['nativeDominantBoneStation'] for x in rows)]}
result={'status':'UNACCEPTED readonly localization of all24historical coverage misses','pins':pins,'recipeSHA256':sha(__file__),'unchangedHistoricalMisses':24,'summary':summary,'allMissWitnesses':records,'limits':['Extended2m rays and body reentry locate proxy behavior; they do not change20cm historical test, excuse exposure or establish whole body garment containment. All24misses remain open.','Bone stations and nearest free edge describe wrist/neck/underarm context only; intentional bare skin or adequate wearing appearance require parent judgment, not automated relabeling.','No source save/native fit/rig/motion/newcapture/body-head-51bind mutation/inference/worker/Library/player promotion or art/M0-M5/mobile acceptance.']};assert pins=={x:sha(x) for x in pins};out.write_text(json.dumps(result,indent=2)+'\n');print('COVERAGE_MISSES_LOCALIZED',json.dumps(summary),flush=True)
