"""Native full/FOUR loss on recorded chassis; first-seed physical failure gate."""
import hashlib,json,time
from pathlib import Path
import bpy,numpy as np
from mathutils import Vector,Matrix
from mathutils.bvhtree import BVHTree
root=Path(__file__).resolve().parents[6];owned=Path(__file__).resolve().parent;ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';out=ev/'hand-grip107';out.mkdir(parents=True,exist_ok=True);assert not (out/'measurements.json').exists();author=owned/'author_bounded_hand_grip.py';scopepath=ev/'hand-grip104/scope.json';scope=json.loads(scopepath.read_text());n=np.load(ev/'hand-grip104/source-fields.npz');f=np.load(ev/'hand-grip106/candidate-fields.npz');receipt=json.loads((ev/'hand-grip106/authoring.json').read_text());serial=json.loads((ev/'hand-grip106/scale-serialization.json').read_text());native=root/serial['native'];driverpath=ev/'hand-grip105/actual-driver.json';driver=json.loads(driverpath.read_text());finitepath=root/scope['physicalChecks']['actualSurfaceSource'];exportfield=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/grip74/export-hand-fields.npz';queryrecipe=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/grip74/measure-grip.py';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(native)==serial['nativeSHA256'];assert sha(author)==receipt['executedAuthoringRecipeSHA256'];assert sha(ev/'hand-grip106/candidate-fields.npz')==receipt['fieldsSHA256'];names=n['boneNames'].tolist();allowed=[names.index(s) for s in scope['scope']['weightBoneNames']];outside=np.setdiff1d(np.arange(51),allowed);P=n['gloveXYZ'].astype(float)
qt=queryrecipe.read_text();qh=dict(np=np);exec(compile(qt[qt.index('def point_query('):qt.index('# Native rest ancestry:')],str(queryrecipe),'exec'),qh);query=qh['point_query'];a=author.read_text();exec(compile(a[a.index('C=np.array('):a.index('B,first,first_targets=pose(')],str(author),'exec'),globals());inputs=[native,author,scopepath,ev/'hand-grip104/source-fields.npz',ev/'hand-grip106/authoring.json',ev/'hand-grip106/candidate-fields.npz',ev/'hand-grip106/scale-serialization.json',driverpath,finitepath,exportfield,queryrecipe]+[root/c['file'] for c in driver['cases']];pins={str(p.relative_to(root)):sha(p) for p in inputs};bpy.ops.wm.open_mainfile(filepath=str(native));rig=bpy.data.objects[receipt['newRig']];original=bpy.data.objects['Independent anatomical foundation rig'];objects=[bpy.data.objects[x] for x in receipt['newObjects']];scale0={b.name:tuple(original.pose.bones[b.name].scale) for b in rig.pose.bones};assert all(tuple(b.scale)==scale0[b.name] for b in rig.pose.bones)
# Source triangle identity and real barycentric palm/finger witnesses, not centroids.
gt=n['gloveTriangles'];sideids={};fingerpoints={}
for side in ['L','R']:
 columns=[i for i,s in enumerate(names) if s.endswith('.'+side) and (s.startswith('hand.') or '_' in s)];other=[i for i,s in enumerate(names) if s.endswith('.'+('R' if side=='L' else 'L')) and (s.startswith('hand.') or '_' in s)];sideids[side]=np.flatnonzero(f['fullWeights'][:,columns].sum(1)>f['fullWeights'][:,other].sum(1))
 fingerpoints[side]={}
 for finger in angles:
  cols=[names.index(finger+'_'+seg+'.'+side) for seg in ['01','02','03']];ids=np.flatnonzero(f['fullWeights'][:,cols].sum(1)>0);tris=np.flatnonzero(np.isin(gt,ids).any(axis=1));tree=BVHTree.FromPolygons(gloveFile.tolist(),gt[tris].tolist(),all_triangles=True);tip=(C@n['rigWorld']@np.r_[n['tails'][names.index(finger+'_03.'+side)],1])[:3];q,normal,ti,dist=tree.find_nearest(Vector(tip));tid=int(tris[ti]);v=gloveFile[gt[tid]];uv=np.linalg.lstsq(np.column_stack([v[1]-v[0],v[2]-v[0]]),np.array(q)-v[0],rcond=None)[0];fingerpoints[side][finger]={'sourceGloveTriangleID':tid,'nativeVertexIDs':gt[tid].tolist(),'barycentric':[float(1-uv.sum()),float(uv[0]),float(uv[1])],'sourceTerminalTailToSelectedGlovePointM':float(dist),'positiveFingerNativeIDs':ids.tolist(),'distalPositiveRows':receipt['distalPositiveRows'][finger+'_03.'+side],'selection':'Nearest actual finite source glove triangle touching a positive ANY-segment finger membership to own semantic terminal tail; point proposal, not certified geometric fingertip.'}
propertext=(owned/'read_neck_displacement_path.py').read_text();ph=dict(np=np);exec(compile(propertext[propertext.index('def proper('):propertext.index('\ndef enumerate_pairs(')],str(owned/'read_neck_displacement_path.py'),'exec'),ph);proper=ph['proper'];gloveRestH=np.column_stack([P,np.ones(len(P))]);oldweights=n['gloveWeights'];nr=n['rigRest'];invnr=np.linalg.inv(nr);world0=n['rigWorld'];localn=np.array([np.linalg.inv(nr[int(parents[j])])@nr[j] if parents[j]>=0 else nr[j] for j in range(51)]);bodyids=np.flatnonzero(n['bodyWeights'][:,allowed].sum(1)>.5);bh=np.column_stack([n['bodyXYZ'][bodyids],np.ones(len(bodyids))]);bw=n['bodyWeights'][bodyids].astype(float)
matrices=[];bikes=[];metadata=[];lossrows=[];wristrows=[];maxloss=0.;worst=None;maxparity=0.;maxHandWorldDelta=0.;firstphysical=None;firstarchive={};start=time.monotonic()
def physical(points,side):
 g=grips[side];tri=np.array(g['trianglesBikeFrame']);ids=sideids[side];d,inside,which,near=query(points[ids],tri);imin=int(d.argmin());depth=np.where(inside,d,0);iw=int(depth.argmax());pointdata={'nativeVerticesChecked':len(ids),'insideVertices':int(inside.sum()),'maximumVertexPenetrationMm':float(depth.max()*1000),'deepestVertex':{'nativeID':int(ids[iw]),'pointBikeFrameM':points[ids[iw]].tolist(),'nearestSourceGripTriangleOrdinal':g['sourceTriangleOrdinals'][int(which[iw])],'closestFinitePointBikeFrameM':near[iw].tolist(),'distanceMm':float(d[iw]*1000),'inside':bool(inside[iw])},'minimumVertexFiniteDistanceMm':float(d[imin]*1000)}
 gv=BVHTree.FromPolygons(points.tolist(),gt.tolist(),all_triangles=True);gb=BVHTree.FromPolygons(tri.reshape(-1,3).tolist(),np.arange(len(tri)*3).reshape(-1,3).tolist(),all_triangles=True);pairs=[]
 for i,j in gv.overlap(gb):
  if proper(points[gt[i]],tri[j]):pairs.append([int(i),int(g['sourceTriangleOrdinals'][j])])
 pointdata['properGloveGripTrianglePairs']=pairs;pointdata['properGloveGripCrossings']=len(pairs)
 p=palms[side];palm=np.array(p['barycentric'])@points[p['nativeVertexIDs']];dd,inn,wh,nn=query([palm],tri);pointdata['actualPalmSurfaceWitness']={'sourceGloveTriangleID':p['sourceGloveTriangleID'],'nativeIDs':p['nativeVertexIDs'],'barycentric':p['barycentric'],'pointBikeFrameM':palm.tolist(),'finiteDistanceMm':float(dd[0]*1000),'inside':bool(inn[0]),'nearestSourceGripTriangleOrdinal':int(g['sourceTriangleOrdinals'][wh[0]]),'closestFinitePointBikeFrameM':nn[0].tolist()};pointdata['fingerSurfaceWitnesses']={}
 axis=unit(np.array(g['fit']['outwardAxisFileFrame']));inner=np.array(g['fit']['innerRingCenterBikeFrame']);length=g['fit']['axisLengthM'];u=unit(np.cross(axis,[0,1,0]));v=np.cross(axis,u)
 for finger,w in fingerpoints[side].items():
  point=np.array(w['barycentric'])@points[w['nativeVertexIDs']];dd,inn,wh,nn=query([point],tri);p=points[w['positiveFingerNativeIDs']]-inner;along=p@axis;window=p[(along>=0)&(along<=length)];theta=np.sort(np.mod(np.arctan2(window@v,window@u),2*np.pi));span=float(2*np.pi-np.diff(np.r_[theta,theta[0]+2*np.pi]).max()) if len(theta)>1 else 0.;pointdata['fingerSurfaceWitnesses'][finger]={'sourceGloveTriangleID':w['sourceGloveTriangleID'],'nativeIDs':w['nativeVertexIDs'],'barycentric':w['barycentric'],'pointBikeFrameM':point.tolist(),'finiteDistanceMm':float(dd[0]*1000),'inside':bool(inn[0]),'nearestSourceGripTriangleOrdinal':int(g['sourceTriangleOrdinals'][wh[0]]),'closestFinitePointBikeFrameM':nn[0].tolist(),'semanticPositiveVerticesInFiniteAxisExtent':len(window),'semanticAngularSpanDeg':float(np.degrees(span)),'spanLimit':'Angular occupancy of semantic positive-weight vertices, not a sealed enclosing surface or full geometric finger segmentation.'}
 return pointdata
for number,(case,row) in enumerate(rows):
 B,desired,targets=pose(row);WN=np.linalg.inv(C@world0)@desired
 for j,name in enumerate(names):
  base=np.linalg.inv(localn[j])@np.linalg.inv(WN[int(parents[j])])@WN[j] if parents[j]>=0 else np.linalg.inv(nr[j])@WN[j];loc,quat,scale=Matrix(base.tolist()).decompose();pb=rig.pose.bones[name];pb.location=loc;pb.rotation_quaternion=quat;pb.scale=scale0[name] if j in allowed else scale
 bpy.context.view_layer.update();deps=bpy.context.evaluated_depsgraph_get();MW=np.array([C@np.array(rig.matrix_world)@np.array(rig.pose.bones[name].matrix) for name in names]);K=np.array([np.array(rig.pose.bones[name].matrix)@invnr[j] for j,name in enumerate(names)]);points=[]
 for obj,w in zip(objects,[f['fullWeights'],f['fourWeights']]):
  evaluated=obj.evaluated_get(deps);mesh=evaluated.to_mesh();nativep=np.array([v.co[:] for v in mesh.vertices]);evaluated.to_mesh_clear();fileworld=(np.column_stack([nativep,np.ones(len(P))])@(C@np.array(obj.matrix_world)).T)[:,:3];points.append((np.column_stack([fileworld,np.ones(len(P))])@np.linalg.inv(B).T)[:,:3]);linear=np.einsum('vj,jab,vb->va',w,K,gloveRestH)[:,:3];maxparity=max(maxparity,float(np.linalg.norm(linear-nativep,axis=1).max()))
 delta=np.linalg.norm(points[0]-points[1],axis=1);maximum=float(delta.max());lossrows.append({'case':case,'inputTick':row['inputTick'],'phase':row['phase'],'maximumMm':maximum*1000,'p95Mm':float(np.percentile(delta,95)*1000),'worstNativeVertexID':int(delta.argmax())});matrices.append(MW);bikes.append(B);metadata.append((case,row['inputTick'],row['phase']));maxHandWorldDelta=max(maxHandWorldDelta,float(np.abs(MW[allowed]-desired[allowed]).max()))
 if maximum>maxloss:maxloss=maximum;worst={'case':case,'inputTick':row['inputTick'],'nativeVertexID':int(delta.argmax()),'fullPointBikeFrameM':points[0][delta.argmax()].tolist(),'fourPointBikeFrameM':points[1][delta.argmax()].tolist()}
 wr={'case':case,'inputTick':row['inputTick'],'phase':row['phase'],'anglesDeg':{}}
 for side in ['L','R']:
  fore=MW[names.index('forearm.'+side),:3,1];hand=MW[names.index('hand.'+side),:3,1];wr['anglesDeg'][side]=float(np.degrees(np.arccos(np.clip(unit(fore)@unit(hand),-1,1))))
 wristrows.append(wr)
 if number==0:
  physicals={label:{side:physical(p,side) for side in ['L','R']} for label,p in zip(['full','four'],points)};originalDesired=np.array([row['observation']['bones'][[x['name'] for x in row['observation']['bones']].index(name.replace('.',''))]['world'] for name in names]).reshape(51,4,4).transpose(0,2,1);oldK=np.linalg.inv(B)@originalDesired@ib;oldp=np.einsum('vj,jab,vb->va',oldweights,oldK,np.column_stack([gloveFile,np.ones(len(P))]))[:,:3];physicals['immutableNative26OnSource37ControlDriver']={side:physical(oldp,side) for side in ['L','R']};bodylinear=np.einsum('vj,jab,vb->va',bw,K,bh)[:,:3];bodyFile=(np.column_stack([bodylinear,np.ones(len(bodyids))])@(C@n['bodyWorld']).T)[:,:3];bodyBike=(np.column_stack([bodyFile,np.ones(len(bodyids))])@np.linalg.inv(B).T)[:,:3];bodyreport={}
  for side in ['L','R']:
   dd,inn,wh,nn=query(bodyBike,np.array(grips[side]['trianglesBikeFrame']));dep=np.where(inn,dd,0);i=int(dep.argmax());bodyreport[side]={'nativeBodyHandWeightMaskIDs':bodyids.tolist(),'insideVertices':int(inn.sum()),'maximumPenetrationMm':float(dep.max()*1000),'worstNativeBodyID':int(bodyids[i]),'pointBikeFrameM':bodyBike[i].tolist(),'nearestSourceGripTriangleOrdinal':int(grips[side]['sourceTriangleOrdinals'][wh[i]])}
  firstphysical={'case':case,'inputTick':row['inputTick'],'phase':row['phase'],'actualObservedBikeFrameWorld':B.tolist(),'nativeCandidateBoneWorldFile':MW.tolist(),'authoredTargets':targets,'fields':physicals,'underlyingImmutableCanonicalHandOnCandidateBones':bodyreport,'wristAxisProxyDeg':wr['anglesDeg'],'qualification':'FAIL: original missing5 distal influence fields remain; evaluate physical seed for explicit witnesses. No moving contact qualification/CCD/enclosing-shell claim follows.'};firstarchive={'firstFullGloveBikeFrameXYZ':points[0],'firstFourGloveBikeFrameXYZ':points[1],'firstControlGloveBikeFrameXYZ':oldp,'firstBodyHandBikeFrameXYZ':bodyBike,'bodyHandNativeIDs':bodyids};(out/'first-physical-seed.json').write_text(json.dumps(firstphysical,indent=2)+'\n');print('FIRST_SEED_PHYSICAL',{l:{s:(d['insideVertices'],d['properGloveGripCrossings'],d['actualPalmSurfaceWitness']['finiteDistanceMm']) for s,d in v.items()} for l,v in physicals.items()},flush=True)
 if number%120==0:print('NATIVE_HAND_LOSS_OBSERVATION',number+1,len(rows),case,row['inputTick'],flush=True)
np.savez_compressed(out/'native-replay-witnesses.npz',nativeCandidateBoneFileWorld=np.array(matrices),observedControlBikeFrameWorld=np.array(bikes),caseIDs=np.array([m[0] for m in metadata]),inputTicks=np.array([m[1] for m in metadata]),phases=np.array([m[2] for m in metadata]),**firstarchive);missing=[s for s,d in receipt['distalPositiveRows'].items() if d['four']==0];report={'status':'FAILED_DISTAL_COVERAGE_AND_FIRST_PHYSICAL_SEED_NO_CAPTURE','recipeSHA256':sha(__file__),'pins':pins,'elapsedS':time.monotonic()-start,'observations':len(rows),'cases':{c:sum(m[0]==c for m in metadata) for c in set(m[0] for m in metadata)},'sourceMatchedNativeFields':True,'actualBikeIndependentlyObserved':True,'candidateEngineConsumption':False,'actualFullFourDisplacementMaximumMm':maxloss*1000,'maximumFullFourWitness':worst,'fullFourLossByObservation':lossrows,'nativeEvaluationVsLinearSkinMaximumM':maxparity,'desiredHandWorldVsActualNativeMaximumElementDelta':maxHandWorldDelta,'wristAxisByObservation':wristrows,'wristAxisRangeDeg':{side:[min(r['anglesDeg'][side] for r in wristrows),max(r['anglesDeg'][side] for r in wristrows)] for side in ['L','R']},'missingDistalCoverageBoneNames':missing,'fingerSurfaceCorrespondences':fingerpoints,'physicalSeedSHA256':sha(out/'first-physical-seed.json'),'replayWitnessSHA256':sha(out/'native-replay-witnesses.npz'),'bodyMask':'Original canonical vertices with sum of admitted32 hand/finger bone weights>.5; explicit original IDs recorded. This mask is a localized hand diagnostic, not a whole actor collision certificate.','limits':['Physical qualification stops at first source-matched native seed failure; later1064 observations measure native full/FOUR loss and wrist frames only, not moving contact/penetration/enclosure/CCD pass.','Actual chassis is directly recorded source37 control; exact native26 glove field is replayed with explicit rest retarget and Blender Float32 decoding. This is not actual candidate export consumption or engine-art admission.','All finite surface correspondences are actual triangle points with original ordinals; finger labels use source memberships and skeletal-tail selection. No complete geometric finger segmentation/enclosing-shell certificate.','The fixed proposal keeps enforcing hand targets during crashed parent frames; it has no qualified grip-release/reacquisition policy. Crashed frames are reported separately and never a continuous contact pass.','No source save, fit/weight/angle retune, extra candidate/capture, normal edit, scope expansion or promotion. AllM0-M5 open/root sole judge.']};(out/'measurements.json').write_text(json.dumps(report,indent=2)+'\n');assert pins=={str(p.relative_to(root)):sha(p) for p in inputs};print(json.dumps({k:report[k] for k in ['status','observations','elapsedS','actualFullFourDisplacementMaximumMm','nativeEvaluationVsLinearSkinMaximumM','desiredHandWorldVsActualNativeMaximumElementDelta','wristAxisRangeDeg','missingDistalCoverageBoneNames']},indent=2))
