"""Measure actual body-centred air clearance at frozen interior contact planes."""
import argparse, collections, gzip, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','localization','section-recipe','radial-recipe','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,localization,sr,rr,out=[Path(getattr(a,k.replace('-','_'))).resolve() for k in ['source','localization','section-recipe','radial-recipe','out']];out.mkdir(parents=True,exist_ok=True);assert not (out/'clearance.json').exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,localization,sr,rr]};assert pins[str(source)]=='aa12937cf5897591bfd9f69c7ee5080e9e96cf2e3495fe2f8c3fb891049d762b';lr=json.loads(localization.read_text());bpy.ops.wm.open_mainfile(filepath=str(source));g=bpy.data.objects['Actual selected donor, actual wrist cuff recut, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];rig=bpy.data.objects['Independent anatomical foundation rig']
def arrays(obj):obj.data.calc_loop_triangles();return np.array([v.co[:] for v in obj.data.vertices]),np.array([t.vertices[:] for t in obj.data.loop_triangles])
gp,gt=arrays(g);bp,bt=arrays(body)
code=sr.read_text();exec(compile(code[code.index('def section('):code.index('rows=[]',code.index('def section('))],str(sr),'exec'));code=rr.read_text();exec(compile(code[code.index('def frame('):code.index('rows=[]',code.index('def frame('))],str(rr),'exec'));rows=[]
for part in ['upperArm.L','forearm.R']:
    witnesses=[x for x in lr['allContactWitnesses'] if x['dominantRawBone']==part];bone=rig.data.bones[part];head=np.array(bone.head_local);tail=np.array(bone.tail_local);axis=tail-head;length=np.linalg.norm(axis);axis/=length
    points=np.array([q for x in witnesses for q in x['crossingPointsXYZ']]);stations=(points-head)@axis/length
    # Exactly three descriptive planes from actual witnessed contacts, no fit sweep.
    for stationValue in np.percentile(stations,[0,50,100]):
        center=head+(tail-head)*stationValue;gr=section(gp,gt,center,axis);br=section(bp,bt,center,axis);air=[(i,c) for i,c in enumerate(gr['contours']) if c.get('orientation')=='airCavity'];outer=[(i,c) for i,c in enumerate(br['contours']) if c.get('orientation')=='materialOuter'];row={'part':part,'station':float(stationValue),'planeCenterM':center.tolist(),'planeNormal':axis.tolist(),'garmentSection':gr,'bodySection':br,'usableBodyCenteredPair':False}
        if air and outer:
            bi,b=min(outer,key=lambda x:x[1]['centroidOffsetFromReference']);gi,c=min(air,key=lambda x:np.linalg.norm(np.array(x[1]['centroidXYZ'])-np.array(b['centroidXYZ'])));bodyRays=radial(b,axis);aligned=dict(c,centroidXYZ=b['centroidXYZ']);airRays=radial(aligned,axis);local=bool(c['centroidOffsetFromReference']<=.10 and b['centroidOffsetFromReference']<=.05);usable=local and bodyRays['centroidInsideContour'] and airRays['centroidInsideContour'] and all(x is not None and x>1e-5 for x in bodyRays['firstRadiusM']+airRays['firstRadiusM']);row.update({'selectedGarmentContourIndex':gi,'selectedBodyContourIndex':bi,'actualAirCentroidM':c['centroidXYZ'],'bodyCentroidM':b['centroidXYZ'],'bodyCentredAirRays':airRays,'bodyCentredOuterRays':bodyRays,'localContourPair':local,'usableBodyCenteredPair':usable})
            if usable:
                ar=np.array(airRays['firstRadiusM']);radius=np.array(bodyRays['firstRadiusM']);row['clearanceByDirectionM']=(ar-radius).tolist();row['clearanceMPercentiles']=np.percentile(ar-radius,[0,50,95,100]).tolist();row['directionCountLessThan4mm']=int((ar-radius<.004).sum());row['bodyPlus4mmOverActualBodyCenteredAirRadius']=((radius+.004)/ar).tolist();row['proposedUniformScaleAroundBodyCentre']=float(((radius+.004)/ar).max())
        rows.append(row)
summary={}
for part in ['upperArm.L','forearm.R']:
    usable=[x for x in rows if x['part']==part and x['usableBodyCenteredPair']];summary[part]={'measuredPlanes':3,'usableBodyCenteredPairs':len(usable),'stations':[x['station'] for x in rows if x['part']==part],'minimumDirectionalClearanceM':[min(x['clearanceByDirectionM']) for x in usable],'proposedScale':[x['proposedUniformScaleAroundBodyCentre'] for x in usable]}
archive=out/'sections.json.gz';archive.write_bytes(gzip.compress(json.dumps(rows,separators=(',',':')).encode(),mtime=0));assert len(json.loads(gzip.decompress(archive.read_bytes())))==6
result={'status':'UNACCEPTED readonly body-centred interior source23 clearance','pins':pins,'recipeSHA256':sha(__file__),'archiveSHA256':sha(archive),'planes':6,'summary':summary,'radialDirections':64,'proposedClearanceM':.004,'method':'Contact-coordinate station min/median/max, six actual native oriented plane sections. Air and body rays share measured body area-centroid and basis; no recentering displacement assumed. Ambiguous/nonlocal contours retained and excluded.','limits':['Finite plane/direction probes are local geometric proposals, not entire surface, actual-air-port, containment or played appearance proof.','No geometry/source save, local fit, radius/time/density search, capture/rig/motion/body-head-51bind change or player promotion.31body/0self remain unaccepted; art/M0-M5/mobile open.']};assert pins=={x:sha(x) for x in pins};(out/'clearance.json').write_text(json.dumps(result,indent=2)+'\n');print('INTERIOR_BODY_CENTRED_CLEARANCE',json.dumps(summary),flush=True)
