"""Measure finite native air corridors using pinned exhaustive distance code."""
import argparse, hashlib, json, sys
from pathlib import Path
import bpy, numpy as np
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','field','paths','distance-recipe','donor-handoff','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,field,paths,recipe,handoff,out=[Path(getattr(a,k.replace('-','_'))).resolve() for k in ['source','field','paths','distance-recipe','donor-handoff','out']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,field,paths,recipe,handoff]};assert pins[str(source)]=='86b85d476b13f709ba832e11dfcd14a17f071f5af69f3ebbbaf7dd1dbe6f58f9';assert pins[str(recipe)]=='199bf90f5d0eb5bfaaf6ac546b25e4c4af9f19b54c184e5a0a47316701fa50e7';assert pins[str(handoff)]=='c766db594cdbd73b5858a9adcfac8f66d29d66f5dde090590c79c48e6070f8df'
code=recipe.read_text();exec(compile(code[code.index('def segment_hits('):code.index('def section(')],str(recipe),'exec'));controlCode=code[code.index('def controls():'):code.index('    s=section(',code.index('def controls():'))]+"    return {'annularAndRotatedClearanceExact':True,'expected':float(expected),'clearance':clearance,'rotated':rotated_clearance}\n";exec(compile(controlCode,str(recipe),'exec'));controlResult=controls();triangle=np.array([[-1,-1,0],[1,-1,0],[0,1,0]],dtype=float);test=segment_hits(triangle,np.array([[0,1,2]]),[0,0,-1],[0,0,1]);assert len(test['intersections'])==1 and not test['clearSegmentWitness'];coplanar=segment_hits(triangle,np.array([[0,1,2]]),[-.2,0,0],[.2,0,0]);assert coplanar['ambiguousCoplanar'] and not coplanar['clearSegmentWitness'];controlResult['intersectingCapRejected']=True;controlResult['coplanarRefusesClear']=True
f=np.load(field);r=json.loads(paths.read_text());assert r['allFourFinitePathsClear'];bpy.ops.wm.open_mainfile(filepath=str(source));g=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];g.data.calc_loop_triangles();p=np.array([v.co[:] for v in g.data.vertices]);tri=np.array([t.vertices[:] for t in g.data.loop_triangles]);assert np.array_equal(p,f['finalNativeXYZ']) and np.array_equal(tri,f['triangles']);reports={}
for name,record in r['paths'].items():
    segments=[]
    for s in record['segments']:
        hits=segment_hits(p,tri,s['startXYZ'],s['endXYZ']);assert hits['clearSegmentWitness'],(name,s['startLabel'],hits);distance=segment_clearance(p,tri,s['startXYZ'],s['endXYZ']);minimum=distance.pop('minimumDistanceNativeUnits');closest=distance.pop('closestOriginalTriangleRow');radius=distance.pop('estimatedOpenTubeRadiusAfterTolerance');total=distance.pop('allOriginalTrianglesBounded');distance['method']='Exhaustive segment-edge/endpoint-triangle distance on saved fitted native triangles, conservatively pruned by AABB bounds; primary implementation reused unchanged.';segments.append({'startLabel':s['startLabel'],'endLabel':s['endLabel'],'startXYZ':s['startXYZ'],'endXYZ':s['endXYZ'],'minimumDistanceM':minimum,'openTubeRadiusAfter1eMinus7MarginM':radius,'closestNativeTriangle':closest,'closestNativeTriangleXYZ':p[tri[closest]].tolist(),'allNativeTrianglesBounded':total,'distanceDetails':distance,'intersectionAudit':hits})
    reports[name]={'segments':segments,'minimumDistanceM':min(s['minimumDistanceM'] for s in segments),'minimumOpenTubeRadiusM':min(s['openTubeRadiusAfter1eMinus7MarginM'] for s in segments)}
result={'status':'UNACCEPTED finite native wearer air-corridor evidence','pins':pins,'recipeSHA256':sha(__file__),'nativeUnits':'Registered canonical Blender metres, distinct from original donor normalized generation units','controls':controlResult,'paths':reports,'allFourFiniteCorridorsPositive':all(x['minimumOpenTubeRadiusM']>0 for x in reports.values()),'bodyPairs':len(f['bodyTrianglePairs']),'selfPairs':len(f['selfTrianglePairs']),'limits':['Finite positive-radius connected corridors around these specified native polylines miss all garment triangles with numerical1e-7m margin. They are not full anatomical wearer capsules, body coverage,physical fabric thickness/ease or formal interval certificates.','Original donor air support handoff remains separately pinned; its uncalibrated units/topology/extra nested hood walls and unresolved outer-torso section are not promoted into wearer-metre proof.','No source save/rig/motion/capture/body-head-51bind change/inference/worker/Library/player promotion or playedart/M0-M5/mobile acceptance.']};assert pins=={x:sha(x) for x in pins};out.write_text(json.dumps(result,indent=2)+'\n');print('NATIVE_FINITE_AIR_CORRIDORS', {k:v['minimumDistanceM'] for k,v in reports.items()},flush=True)
