"""Read and declare exact hand/glove fields before construction. No edits/save."""
import hashlib,json
from pathlib import Path
import bpy,numpy as np
root=Path(__file__).resolve().parents[6];owned=Path(__file__).resolve().parent
ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';out=ev/'hand-grip104';out.mkdir(parents=True,exist_ok=True)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
source=owned/'selected-hoodie26/native-four-with-full-control.blend';qa=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/grip74'
inputs=[source,qa/'FINDING.md',qa/'native26.npz',qa/'finite-grips.json',root/'public/models/bike-rookie.glb',root/'public/models/bike-pro.glb',root/'public/models/bike-rookie-lod.glb',root/'public/models/bike-pro-lod.glb',root/'src/render/hero/gltfRider.ts',root/'src/render/hero/gltfBike.ts']
pins={str(p.relative_to(root)):sha(p) for p in inputs}
assert pins[str(source.relative_to(root))]=='4a0904b94a507f35590d1ec4ebfe763237fa5fb21fa189573842309cb776a0ad'
assert sha(qa/'FINDING.md')=='72c42c02f2508e3b397593dec12ec270d9cc91d0e7e5e526378801c249e821b8'
assert not (out/'scope.json').exists()
bpy.ops.wm.open_mainfile(filepath=str(source));rig=bpy.data.objects['Independent anatomical foundation rig'];names=list(rig.data.bones.keys());allowed=['hand.'+s for s in ['L','R']]+[f+'_'+g+'.'+s for s in ['L','R'] for f in ['index','middle','pinky','ring','thumb'] for g in ['01','02','03']]
assert len(names)==51 and len(allowed)==32 and all(x in names for x in allowed)
helper=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/neck62/read-native.py';text=helper.read_text();h=dict(bpy=bpy,np=np,hashlib=hashlib);exec(compile(text[text.index('def digest('):text.index('for label,path in paths.items():')],str(helper),'exec'),h)
control={'objects':{o.name:h['state'](o) for o in bpy.data.objects},'materials':h['materials'](),'images':{im.name:{'packed':sha(im.filepath) if not im.packed_file and Path(im.filepath).is_file() else hashlib.sha256(bytes(im.packed_file.data)).hexdigest() if im.packed_file else None,'colour':im.colorspace_settings.name,'size':list(im.size),'filepath':im.filepath} for im in bpy.data.images}}
(out/'immutable-control.json').write_text(json.dumps(control,indent=2)+'\n')
arrays={'boneNames':np.array(names),'rigRest':np.array([np.array(b.matrix_local) for b in rig.data.bones]),'rigWorld':np.array(rig.matrix_world),'heads':np.array([b.head_local[:] for b in rig.data.bones]),'tails':np.array([b.tail_local[:] for b in rig.data.bones]),'parents':np.array([names.index(b.parent.name) if b.parent else -1 for b in rig.data.bones])};objects={}
for key,oname in [('glove','Registered black leather gloves on own finger bind'),('body','Canonical anatomical body, baked adult hm08')]:
 o=bpy.data.objects[oname];m=o.data;m.calc_loop_triangles();weights=np.zeros((len(m.vertices),51),dtype=np.float32)
 for v in m.vertices:
  for g in v.groups:
   name=o.vertex_groups[g.group].name
   if name in names:weights[v.index,names.index(name)]=g.weight
 arrays[key+'XYZ']=np.array([v.co[:] for v in m.vertices],dtype=np.float32);arrays[key+'Triangles']=np.array([t.vertices[:] for t in m.loop_triangles],dtype=np.int32);arrays[key+'Weights']=weights;arrays[key+'World']=np.array(o.matrix_world);arrays[key+'TrianglePolygonIDs']=np.array([t.polygon_index for t in m.loop_triangles],dtype=np.int32)
 objects[key]={'object':oname,'vertices':len(m.vertices),'polygons':len(m.polygons),'triangles':len(m.loop_triangles),'shapeKeys':list(m.shape_keys.key_blocks.keys()) if m.shape_keys else [],'world':np.array(o.matrix_world).tolist()}
np.savez_compressed(out/'source-fields.npz',**arrays)
handmass=arrays['gloveWeights'][:,[names.index(n) for n in allowed]].sum(1);editable=np.flatnonzero(handmass>0);pinned=np.flatnonzero(handmass==0);g=objects['glove'];mesh=bpy.data.objects[g['object']].data
scope={'status':'PINNED_EXACT_SCOPE_BEFORE_HAND_CONSTRUCTION_NO_SOURCE_EDIT','recipeSHA256':sha(__file__),'pins':pins,'immutableControl':{'path':str(source.relative_to(root)),'sha256':sha(source),'allOriginalObjectStates':str((out/'immutable-control.json').relative_to(root)),'snapshotSHA256':sha(out/'immutable-control.json'),'preserveOriginalInputObjectsInDerivative':True},'sourceFieldsSHA256':sha(out/'source-fields.npz'),'objects':objects,'scope':{'geometryObject':g['object'],'geometryNativeVertexIDs':list(range(g['vertices'])),'geometryNativePolygonIDs':list(range(g['polygons'])),'geometryLoopTriangleIDs':list(range(g['triangles'])),'weightNativeVertexIDs':editable.tolist(),'weightBoneNames':allowed,'weightFields':'Only the listed32 hand/finger columns may redistribute existing hand/finger mass. Preserve all19 other bone columns and all auxiliary definitions/memberships exactly. Zero hand-mass rows remain pinned.','zeroHandMassPinnedNativeVertexIDs':pinned.tolist(),'existingPoseBoneNames':allowed,'poseFields':['rotation_quaternion','location'],'poseScaleAllowed':False,'restBindEditAllowed':False,'bodyGeometryOrWeightEditableIDs':[],'topologyEditAllowed':False,'UVPBRRawAttributeEditAllowed':False,'derivative':'One new unaccepted full/four glove pair and copied original51 rig; all original objects remain immutable controls.'},'physicalChecks':{'constructionBike':'bike-rookie.glb','actualSurfaceSource':str((qa/'finite-grips.json').relative_to(root)),'surfaceIdentity':'Actual detailed rookie node22/mesh8/primitive0 source triangle ordinals,44finite triangles per grip; no cylinder contact substitute.','movingStreamRequirement':'Record actual bike.frame and all51 bone transforms from a source-matched candidate stream; palm/finger finite-triangle correspondences/penetration/enclosure/wrist alignment required. Film50 implied chassis and numeric47/native99 streams remain separate controls, never actual-contact certificates.'},'outsidePreservation':['Every original object state, original51 rest/bind/saved pose, images/materials after save and reopen byte/state exact.','New glove topology, UV/PBR and non-position raw fields stay exact to source; no custom normal rewrite.','Outside listed mutable bone columns and rows, all51/auxiliary assignments stay exact; full-to-four retained mass and actual evaluated displacement loss must be reported.','No face, neck, hoodie, body size or unrelated geometry, handlebars, global body/head transform, masks or culling changes.'],'limits':['AllM0-M5/contact/art/engine/device/player gates open; root alone judges played result.','No construction, source mutation/save, solve, normal edit or render/capture occurred in this scope read.','If exact scope cannot cover proper binding/contact, stop with precise region/bone/field proposal; no widening.']}
(out/'scope.json').write_text(json.dumps(scope,indent=2)+'\n');assert pins=={str(p.relative_to(root)):sha(p) for p in inputs};print(json.dumps({'objects':objects,'weightMutableVertices':len(editable),'zeroHandMassPinned':len(pinned),'gloveHandMassMinimum':float(handmass.min()),'allOriginalObjects':len(control['objects']),'fieldsSHA256':scope['sourceFieldsSHA256']},indent=2))
