/** Independently record real bike.frame and bone worlds; no screenshots/pose edits. */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {preview} from 'vite';
import {webkit} from 'playwright';
import {decodeJSON,expandFrames} from '../../../../../../src/core/replay';
const root=process.cwd(),out=path.join(root,'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1/hand-grip105');
fs.mkdirSync(out,{recursive:true});assert(!fs.existsSync(path.join(out,'actual-driver.json')));
const build=path.join(root,'harness/out/user-agent3-2026-10-03/constructed38-build');
const sha=(b:any)=>crypto.createHash('sha256').update(b).digest('hex');
const manifestBytes=fs.readFileSync(path.join(build,'hero-review.json')),manifest=JSON.parse(manifestBytes.toString());
const model=manifest.models.find((m:any)=>m.logical==='models/rider-street-mustard.glb');assert.equal(model.sha256,'3ffd591d6872513646cab2384f8fe6b21f828ab57bdb5842cc1659fcd32face2');assert.equal(sha(fs.readFileSync(path.join(build,model.url))),model.sha256);
const fp=path.join(root,'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/split-fixtures01-inputs/manifest.json');const fixtureBytes=fs.readFileSync(fp),fixtures=JSON.parse(fixtureBytes.toString());
const ids=['rookie-maximum-backward-lean','rookie-front-landing-recovery','rookie-crash-instant-restart'];
const report:any={status:'RECORDING_ACTUAL_CONTROL_BIKE_NOT_CANDIDATE_CERTIFICATE',recipeSHA256:sha(fs.readFileSync(new URL(import.meta.url))),source37SHA256:model.sha256,manifestSHA256:sha(manifestBytes),fixtureManifestSHA256:sha(fixtureBytes),cases:[],loaded:[],errors:[],limits:['This records source37 actual controller parents and independent bike.frame. It is not film50/numeric47/native99 and not yet a candidate contact certificate.','A native26 glove derivative must explicitly match its own exact rest/bind/weights to this driver before claiming surface qualification. No inferred chassis.','No screenshot, render capture, geometry/weight/pose/controller edit or production admission.']};
const server=await preview({configFile:false,root,build:{outDir:build},preview:{host:'127.0.0.1',port:0},logLevel:'warn'});
const browser=await webkit.launch({headless:true}),context=await browser.newContext({viewport:{width:320,height:240}});await context.addInitScript(()=>{localStorage.setItem('rockhop.onboarded','1');(window as any).__audioCount=0;for(const n of ['AudioContext','webkitAudioContext'])(window as any)[n]=class{constructor(){(window as any).__audioCount++;throw Error('Silent numeric recording');}};});const page=await context.newPage(),responses:any[]=[];
page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.url().endsWith('.glb'))responses.push(r.body().then(b=>report.loaded.push({sha256:sha(b),status:r.status()})));});
try{
 await page.goto(server.resolvedUrls!.local[0]+'?harness=1&audio=0&sw=0&outfit=street-mustard&physics=v2&hz=120');await page.waitForFunction(()=>(window as any).__rockhop?.ready,null,{timeout:120000});
 for(const id of ids){const fixture=fixtures.cases.find((c:any)=>c.id===id);const rb=fs.readFileSync(path.join(path.dirname(fp),fixture.recording));assert.equal(sha(rb),fixture.sourceSHA256);const recording=decodeJSON(rb.toString()),inputs=expandFrames(recording).slice(0,fixture.window.endInputTick);
  await page.evaluate(async(h:any)=>{const t=(window as any).__rockhop,r=(window as any).__render;t.setBike('rookie');await r.whenReady();await t.loadTrack(h.trackId,h.seed);t.setQuality('high');await r.whenReady();t.skipCountdown();t.render(true);},recording.header);
  const samples:any[]=[],trace:any[]=[];let previous=0;
  while(previous<inputs.length){const end=Math.min(previous+120,inputs.length);const rows=await page.evaluate(({chunk,offset,start}:any)=>{const t=(window as any).__rockhop,r=(window as any).__render,d=r.debug;return chunk.map((input:any,i:number)=>{t.setInput(input);t.step(1);t.render(true);const s=t.getState(),tick=offset+i+1;const row:any={inputTick:tick,physicsTick:s.tick,hash:t.hashState(),phase:t.phase(),runTime:t.runTime(),events:s.events??[],riderBody:s.riderBody,webdriver:navigator.webdriver,audioContexts:(window as any).__audioCount};if(tick>=start){d.scene.updateMatrixWorld(true);const bones:any[]=[];d.rider.scene.traverse((o:any)=>{if(o.isBone)bones.push({name:o.name,world:o.matrixWorld.elements.slice(),local:o.matrix.elements.slice()});});row.observation={bikeFrameWorld:d.bike.frame.matrixWorld.elements.slice(),bikeRootWorld:d.bike.root.matrixWorld.elements.slice(),riderSceneWorld:d.rider.scene.matrixWorld.elements.slice(),bones,physicalPose:d.rider.debug.physicalPose};}return row;});},{chunk:inputs.slice(previous,end),offset:previous,start:id==='rookie-maximum-backward-lean'?1:fixture.window.startInputTick});for(const row of rows){assert(row.webdriver&&row.audioContexts===0);if(row.observation){assert.equal(row.observation.bones.length,51);samples.push(row);}trace.push({inputTick:row.inputTick,physicsTick:row.physicsTick,hash:row.hash,phase:row.phase});}previous=end;if(previous%600===0)console.log(JSON.stringify({id,inputTicks:previous}));}
  for(const old of fixture.matchedSamples){const row=trace.find(r=>r.inputTick===old.inputTick);assert.equal(row.hash,old.stateHash,`${id} tick${old.inputTick}`);assert.equal(row.phase,old.phase);}
  const file=path.join(out,id+'.json');fs.writeFileSync(file,JSON.stringify({id,source37SHA256:model.sha256,recordingSHA256:sha(rb),window:fixture.window,samples})+'\n');report.cases.push({id,inputTicks:inputs.length,observedSamples:samples.length,recordingSHA256:sha(rb),file:path.relative(root,file),sha256:sha(fs.readFileSync(file)),fixtureMatchedHashes:true,phaseCounts:Object.fromEntries(['riding','crashed','finished'].map(p=>[p,samples.filter(r=>r.phase===p).length]))});console.log(JSON.stringify(report.cases.at(-1)));
 }
 await Promise.all(responses);assert.deepEqual(report.errors,[]);assert(report.loaded.some((r:any)=>r.sha256===model.sha256&&r.status===200));assert(report.loaded.some((r:any)=>r.sha256==='e55919d60267849358ef5e97f4731f42fac6eb2835b9998e1d146d056c0f10f7'&&r.status===200));report.status='INDEPENDENT_ACTUAL_BIKE_AND_51_BONE_CONTROL_STREAM_RECORDED';
}catch(e){report.failure=String(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'actual-driver.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();await new Promise<void>(resolve=>server.httpServer!.close(()=>resolve()));console.log(JSON.stringify({status:report.status,failure:report.failure,cases:report.cases.length}));}
