"""One matched rest orbit of chosen donor/control and frozen actual fit24."""
import argparse, hashlib, json, math, sys, time
from pathlib import Path
import bpy, numpy as np
from mathutils import Vector, Matrix
ap=argparse.ArgumentParser(description=__doc__)
for k in ['source','registration-recipe','transfer-recipe','out']:ap.add_argument('--'+k,required=True)
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);source,recipe,transferRecipe,out=[Path(getattr(a,k.replace('-','_'))).resolve() for k in ['source','registration-recipe','transfer-recipe','out']];out.mkdir(parents=True,exist_ok=True);assert not (out/'review.json').exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(p):sha(p) for p in [source,recipe,transferRecipe]};assert pins[str(source)]=='86b85d476b13f709ba832e11dfcd14a17f071f5af69f3ebbbaf7dd1dbe6f58f9';bpy.ops.wm.open_mainfile(filepath=str(source));scene=bpy.context.scene;high=bpy.data.objects['Exact selected Hunyuan high-poly PBR donor, display frame only'];rig=bpy.data.objects['Independent anatomical foundation rig'];actual=bpy.data.objects['Actual selected donor, compact interior flow, unaccepted'];body=bpy.data.objects['Canonical anatomical body, baked adult hm08'];pattern=bpy.data.objects['Separate fitted sweatshirt control, hood not constructed'];definition=transferRecipe.read_text();start=definition.index('definition=recipe.read_text()');exec(compile(definition[start:definition.index('tree=BVHTree',start)],str(transferRecipe),'exec'))
raw=high.copy();raw.data=high.data.copy();bpy.context.collection.objects.link(raw);raw.name='Review original donor, uniform frame only';reg=high.copy();reg.data=high.data.copy();bpy.context.collection.objects.link(reg);reg.name='Review donor, frozen preferred61 registration';uniform=donor@display_to_native.T*height+[0,.007,up]
for obj,positions in [(raw,uniform),(reg,registered)]:
    obj.parent=None;obj.matrix_world=Matrix.Translation((.65,0,0));obj.data.vertices.foreach_set('co',np.asarray(positions,dtype=np.float32).ravel());obj.data.update()
    if obj.data.has_custom_normals:obj.data.normals_split_custom_set([(0,0,0)]*len(obj.data.loops))
variants=[('original','ORIGINAL DONOR / UNIFORM ONLY',raw),('registered','DONOR / PREFERRED61 REGISTRATION',reg),('fitted24','ACTUAL FIT24 / UNACCEPTED',actual)];assert all(obj.data.materials[0] is high.data.materials[0] for key,label,obj in variants)
for obj in scene.objects:
    if obj.type in ['MESH','LIGHT','FONT']:obj.hide_render=True
world=bpy.data.worlds.new('Actual donor matched neutral studio');world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.075,.075,.075,1);world.node_tree.nodes['Background'].inputs[1].default_value=.65;scene.world=world;target=Vector((.65,0,1.38))
for name,pos,energy in [('Key',(4,-4,5),700),('Fill',(-3,4,4),600),('Top',(.65,0,5),400)]:
    light=bpy.data.lights.new(name,'AREA');light.energy=energy;light.size=4;obj=bpy.data.objects.new(name,light);bpy.context.collection.objects.link(obj);obj.location=pos;obj.rotation_euler=(target-obj.location).to_track_quat('-Z','Y').to_euler()
cd=bpy.data.cameras.new('Actual donor matched rest camera');cd.type='ORTHO';cd.ortho_scale=1.72;camera=bpy.data.objects.new(cd.name,cd);bpy.context.collection.objects.link(camera);scene.camera=camera;white=bpy.data.materials.new('Actual donor comparison legend');white.use_nodes=True;nt=white.node_tree;nt.nodes.clear();em=nt.nodes.new('ShaderNodeEmission');em.inputs[0].default_value=(1,1,1,1);output=nt.nodes.new('ShaderNodeOutputMaterial');nt.links.new(em.outputs[0],output.inputs['Surface']);font=bpy.data.curves.new('Actual donor comparison legend','FONT');font.size=.028;font.materials.append(white);legend=bpy.data.objects.new(font.name,font);bpy.context.collection.objects.link(legend);legend.parent=camera;legend.location=(-.81,.78,-2)
scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=8;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=640;scene.render.resolution_y=640;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';scene.render.film_transparent=False;scene.view_settings.view_transform='AgX'
for key,label,obj in variants:(out/key).mkdir(exist_ok=True)
start=time.monotonic();frames=[]
for index in range(48):
    yaw=2*math.pi*index/48;camera.location=target+Vector((4*math.cos(yaw),4*math.sin(yaw),.30));camera.rotation_euler=(target-camera.location).to_track_quat('-Z','Y').to_euler();views=[]
    for key,label,obj in variants:
        obj.hide_render=False;obj.hide_set(False);font.body=label+'\nREST / MATCHED PBR+LIGHT / OPEN GATES';scene.render.filepath=str(out/key/f'{index:04d}.png');bpy.ops.render.render(write_still=True);views.append({'variant':key,'PNG_SHA256':sha(scene.render.filepath),'object':obj.name});obj.hide_render=True
    frames.append({'index':index,'yawRadians':yaw,'cameraWorldRows':[list(row) for row in camera.matrix_world],'views':views})
    if index%4==0:print('ACTUAL_DONOR_REST_REVIEW',index,'elapsedS',round(time.monotonic()-start,1),flush=True)
sequence=[]
for index in range(48):
    # Three-second front/rear and two-second side holds at3source frames/sec.
    count=9 if index in [0,24] else 6 if index in [12,36] else 1;sequence.extend([index]*count)
sequence.extend([0]*6)
report={'status':'UNACCEPTED root-requested actual donor24 matched rest orbit','pins':pins,'recipeSHA256':sha(__file__),'nativeCandidateSHA256':pins[str(source)],'renderedUniqueAngles':48,'variants':[{'key':k,'label':label,'object':obj.name,'vertices':len(obj.data.vertices)} for k,label,obj in variants],'frames':frames,'movieFrameSequence':sequence,'sourceFramesPerSecond':3,'durationS':len(sequence)/3,'sourceRegistrationMaxErrorM':registration_error,'originalMaterialSameIdentity':True,'render':'Matched native camera/orthographic1.72m/neutral studio/CyclesCPU2threads8samples/AgX/640square percolumn. Actual original UV/PBR, no diagnostic recolor.','authorization':'Root through authorized Bridge relay after source24rest contact/preservation/finite air audits; one matched rest orbit after coverage84, before broadrig/motion.','limits':['Not wearing motion or appearance acceptance; root sole played judge.24historical coverage misses(3chest/6upperarm/15forearm) retained. Rest0body/0self and finite native air are separate evidence.','Original column has only uniform0.472222scale/frame placement; registered column reproduces exact preferred61piecewise registration, not latest18measured map. Fit24 is actual frozen currentnative. Original donor units are uncalibrated/nested hood walls/outerbranch limits remain.','Raw/registered display-only clones recompute geometric normals after coordinate mapping, matching61presentation. Protected native/body/head/51bind/PBR/player source never saved or changed. No rig/inference/publication/promotion/M0-M5/mobile acceptance.']};assert pins=={p:sha(p) for p in pins};(out/'review.json').write_text(json.dumps(report,indent=2)+'\n');print('ACTUAL_DONOR_REST_REVIEW_READY','elapsedS',round(time.monotonic()-start,1),'durationS',report['durationS'],flush=True)
