"""Verify completed read-only archives after terminal-summary key failure."""
import ast,hashlib,json
from pathlib import Path
import numpy as np
root=Path(__file__).resolve().parents[6];owned=Path(__file__).resolve().parent;ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';out=ev/'hand-grip107';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();old=json.loads((out/'measurements.json').read_text());r=json.loads((out/'decoder-recheck/measurements.json').read_text());seed=json.loads((out/'decoder-recheck/first-physical-seed.json').read_text());a=np.load(out/'native-replay-witnesses.npz');b=np.load(out/'decoder-recheck/native-replay-witnesses.npz');assert set(a.files)==set(b.files);equal={k:np.array_equal(a[k],b[k]) for k in a.files};assert all(equal.values()),equal
for receipt,recipe,folder in [(old,'measure_bounded_hand_grip.py',out),(r,'recheck_bounded_hand_grip_decoder.py',out/'decoder-recheck')]:
 assert sha(owned/recipe)==receipt['recipeSHA256'];ast.parse((owned/recipe).read_text())
 for p,h in receipt['pins'].items():assert sha(root/p)==h,p
 assert sha(folder/'first-physical-seed.json')==receipt['physicalSeedSHA256'];assert sha(folder/'native-replay-witnesses.npz')==receipt['replayWitnessSHA256'];assert len(receipt['fullFourLossByObservation'])==1065;assert len(receipt['wristAxisByObservation'])==1065
assert old['fullFourLossByObservation']==r['fullFourLossByObservation'];assert old['wristAxisByObservation']==r['wristAxisByObservation'];assert r['observations']==1065
phase={}
for name in ['riding','crashed']:
 rows=[s for s in r['wristAxisByObservation'] if s['phase']==name];phase[name]={'samples':len(rows),'bySide':{side:{'minDeg':min(x['anglesDeg'][side] for x in rows),'maxDeg':max(x['anglesDeg'][side] for x in rows),'maxWitness':{k:v for k,v in max(rows,key=lambda x:x['anglesDeg'][side]).items() if k!='anglesDeg'}} for side in ['L','R']}}
report={'status':'ARCHIVES_COMPLETE_REPRODUCED_NATIVE_CONTACT_AND_COVERAGE_FAIL_PARITY_UNQUALIFIED','recipeSHA256':sha(__file__),'measurementsSHA256':sha(out/'decoder-recheck/measurements.json'),'allArchivesAndExecutedRecipeAndInputPinsValidated':True,'recheckArrayExactToFirstRead':equal,'1065NativeLossAndWristObservationsReproducedExactly':True,'firstContactAndSourceCorrespondencesReproduced':json.loads((out/'first-physical-seed.json').read_text())==seed,'wristAxisByPhase':phase,'normalizedLinearNativeParityMaximumM':r['nativeEvaluationVsNormalizedLinearSkinMaximumM'],'normalizedLinearNativeParityQualified':False,'parityLimit':'0.212346790mm moving native-v-normalized LBS discrepancy remains despite unhidden read-only evaluated rig recheck; no byte-identical replay/engine palette certificate. First-seed normalized LBS discrepancy independently measured<=0.300189um. Do not promote this source mapping.','terminalSummaryRecovery':'Recheck completed both JSON/NPZ writes and all immutable-pin assertions. Its final stdout summary referenced the renamed parity key and failed afterward. This verifier confirms complete records without reauthoring or rerunning motion. Terminal log preserved.','acceptance':{'distalCoverage':False,'firstPhysicalSeedContact':False,'movingContactEnclosureCCD':False,'candidateEngineConsumption':False,'playedProofAuthorizedByGate':False,'allM0M5Open':True}}
(out/'evidence-validation.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'archiveChecks':'PASS','nativeFrames':1065,'contactCoverage':'FAIL','normalizedNativeParityQualified':False,'wristAxisByPhase':phase},indent=2))
