"""Freeze actual failed texture trial and precise retirement handoff; no rerun."""
from pathlib import Path
from PIL import Image,ImageDraw
import numpy as np,json,hashlib,shutil,struct,ast
S=Path(__file__).resolve().parent
R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/A-new-head-audit')
O=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/A-new-head-audit/generation-evidence/h21-buzz-native01/cheek-dual-sheet03-correction01')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
report=json.loads((O/'repair-report.json').read_text());receipt=json.loads((O/'repair-process.json').read_text());source=R/'generation/h21-buzz-native01/model.glb';atlas=R/'cheek-dual-sheet03-correction01/cheek-skin-albedo.png'
pixels=np.array(Image.open(atlas).convert('RGBA'))/255.;valid=pixels[:,:,3]>.5;median=np.median(pixels[:,:,:3][valid],axis=0)
encode=lambda c:np.where(c<=.0031308,c*12.92,1.055*c**(1/2.4)-.055)
coefficients=[np.array(p['colorFitCoefficients'])[0] for p in report['patches'] if p['sheetSign']==-1]
diagnosis={'status':'Read-only diagnosis hypothesis, not a corrected render','atlasSHA256':sha(atlas),'atlasAlphaCoveredPixels':int(np.sum(valid)),'atlasEncodedRGBMedian':median.tolist(),'fittedExteriorColorIntercepts':[c.tolist() for c in coefficients],'sRGBEncodingOfFittedIntercepts':[encode(c).tolist() for c in coefficients],'colorSpaceHypothesis':'Image pixel samples appear already encoded; assigning them directly to linear FLOAT_COLOR and baking to an sRGB PNG likely encodes twice. Prove source texel/actual shader interpretation, linearize before transport and validate resulting base-color pixels before rerender.','atlasOverlapActual':'The four baked source patches share two side-based UV rectangles: inner and exterior use overlapping UV footprints on each cheek. All four bake stages wrote the same atlas. This can overwrite exterior samples and must be avoided or intentionally reconciled.','materialActual':'New patch copies source KHR_materials_specular specularColorFactor [2,2,2]; no source normal or occlusion texture. Patch roughness is fitted median ~0.38.','proposedNextMethod':'Keep geometry.glb. Transport only original same-cheek surrounding albedo through analytic physical-surface projection into exterior-only coherent islands; inpaint missing interior pixels, preserve boundary color continuity, explicitly distinguish sRGB and linear samples. Keep inner material separate/hidden; validate texel colors against original cheek shader before an actual PBR render. No nearest cross-chart color transfer.','limits':['Cause remains a hypothesis until source-texel/shader and corrected actual render validate it.','No next repair, model generation, rig or asset promotion performed.']}
(O/'texture-diagnosis.json').open('x').write(json.dumps(diagnosis,indent=2)+'\n')
before=O.parent/'gray-diagnostic03';image=Image.new('RGB',(1440,820),'#202328');draw=ImageDraw.Draw(image)
cells=[('Original gray front',before/'painted-gray-face-front.png'),('Original gray profile',before/'painted-gray-face-profile.png'),('Original gray quarter',before/'painted-gray-face-three-quarter.png'),('Original PBR front',before/'painted-PBR-face-front.png'),('Patched gray front',O/'actual-gray-front.png'),('Patched gray profile',O/'actual-gray-profile.png'),('Patched gray quarter',O/'actual-gray-three-quarter.png'),('REJECTED PBR: white patches',O/'actual-PBR-front.png')]
for i,(label,path) in enumerate(cells):
 tile=Image.open(path).convert('RGB');tile.thumbnail((360,360));x=(i%4)*360;y=(i//4)*390;image.paste(tile,(x,y+30));draw.text((x+8,y+9),label,fill='#ffafaf' if 'REJECTED' in label else 'white')
draw.text((10,788),'One connected skin; original outside buffers exact. Geometry promising; PBR rejected. No accepted face, rig or runtime asset.',fill='white');image.save(O/'actual-before-after-geometry-texture.jpg')
shutil.copyfile(R/'h21-cheek-dual-sheet03-correction01-repair-log.txt',O/'repair-log.txt')
(O/'README.md').open('x').write('''# Cheek geometry repaired; texture trial rejected

The actual corrected trial completed at 03:36:46 UTC, CPU two threads, exit 0. Both exterior and existing inner-cavity boundaries were repaired. The result has one physical edge-connected skin, 99,914 triangles, zero physical boundary edges and zero above-two edge incidences. Every retained source triangle and original POSITION/NORMAL/UV/image payload remains byte-exact; 514 explicit local source triangles were replaced. The original 99,999-triangle source is untouched.

An analytic projected-triangle overlap test bounds the new exterior/inner caps: minimum local thickness is 0.0064474 left and 0.0081880 right, approximately 1.803 and 2.290 mm in the recorded display frame. This establishes relative cap depths, not whole-source self-intersection or character acceptance. Four focused tests passed, including a narrow corner crossing that sparse sampling can miss.

The parent viewed actual GLB-reimport gray front/profile/quarter: closed cheek openings with faint faceted patch lines, a promising geometry foundation. The actual PBR front/profile is REJECTED for bright jagged white bandages. Process success, manifold topology and numeric checks do not pass the appearance gate. Original eye/lid softness and remaining facial detail are unchanged. No accepted face score of 7/10 was obtained.

Read-only texture diagnosis records probable double sRGB encoding: fitted values around (.78,.53,.43) were assigned directly to linear vertex colors, and the saved sRGB atlas is correspondingly much brighter. The source texel/shader interpretation must still be proved. Inner and exterior patch bake footprints also overlap on the shared atlas, which can overwrite exterior samples. The copied source specularColorFactor [2,2,2] remains. See texture-diagnosis.json; no rerun followed this finding.

Preserve runtime geometry.glb as the unaccepted geometric foundation. Next agent should transport original surrounding cheek albedo into exterior-only coherent UV islands, explicitly linearize/encode, inpaint missing pixels in that anatomical chart, compare boundary texels, then show actual PBR. Do not resume centroid/fan mask tweaks or replace the source face. Inner closure should not overwrite the exterior atlas. A faint geometry facet seam still needs parent judgment.

Attempt record: two local perimeter failures; the dual-sheet approach then had one native tessellation API setup failure, frozen separately. This corrected dual-sheet run repaired geometry but failed its first texture trial. All lineage evidence is preserved. Hard batch ceiling remains 04:01:29 UTC; this agent retires after this handoff with no active process or future refinement queued. No rig, neck integration, gameplay contacts or production rider was changed.
''')
(O/'retirement-handoff.json').open('x').write(json.dumps({'status':'Builder retired; no live job, no accepted face','source':str(source),'sourceSHA256':sha(source),'sourceSHA256MatchesFrozen':sha(source)==report['sourceSHA256'],'runtimeGeometry':report['grayGeometry'],'runtimeRejectedPBR':report['finalModel'],'runtimeAtlas':report['bake'],'actualReceipt':receipt,'geometryOutsideExact':report['outsideSourceGeometryUVNormalsTexturePayloadExact'],'defectID':'H21-cheekOpenings','priorPerimeterFailures':2,'dualSheetAPISetupFailures':1,'dualSheetGeometryTrial':'Promising, parent review still required','dualSheetTextureFailures':1,'hardDeadlineUTC':'2026-10-01T04:01:29.797205+00:00','activeJobs':[],'responseCount':'Lifetime count not exposed by agent API; conservative retirement after this frozen trial, no reuse.','nextMethod':diagnosis['proposedNextMethod']},indent=2)+'\n')
paths=list(S.glob('*.py'))+list(O.glob('*'));[ast.parse(p.read_text()) for p in S.glob('*.py')]
(O/'checkpoint-texture-failure01.json').open('x').write(json.dumps({'status':'UNACCEPTED geometry foundation; actual PBR rejected','parentReview':'Closed cheeks visually, faint faceted strips; bright jagged white patch texture rejected.','files':[{'path':str(p.resolve()),'SHA256':sha(p),'bytes':p.stat().st_size} for p in paths if p.is_file()]},indent=2)+'\n');print('TRIAL_FROZEN_AND_RETIRED',flush=True)
