"""Export failed uncapped prefix for inspection, not an accepted candidate."""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS','2');os.environ.setdefault('OMP_NUM_THREADS','2')
from pathlib import Path
import numpy as np,json,copy,hashlib,struct,importlib.util
ROOT=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');R=B/'head-sew213';E=ROOT/'docs/evidence/hero-remaster/one-rider-v2/head-sew213';source=B/'source-preserving-garment185/operator/rider.glb';spec=importlib.util.spec_from_file_location('reader',ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);g=mod.GLB(source);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();z=np.load(R/'precap-partial.npz');V=z['attributePositions'].astype(np.float32);F=z['attributeFaces'];mat=z['materials'];N=z['normals'].astype(np.float32);UV=z['uv'].astype(np.float32)
# Body flat-source normal accumulation; protected head normals remain original.
t=V[F[mat==0]].astype(float);nn=np.cross(t[:,1]-t[:,0],t[:,2]-t[:,0]);acc=np.zeros_like(V,float);np.add.at(acc,F[mat==0].ravel(),np.repeat(nn,3,axis=0));length=np.linalg.norm(acc,axis=1);rows=length>0;N[rows]=(acc[rows]/length[rows,None]).astype(np.float32)
j=copy.deepcopy(g.j);binary=bytearray(g.bin)
def accessor(a,ctype,typ):
 a=np.ascontiguousarray(a);off=len(binary);binary.extend(a.tobytes());binary.extend(b'\0'*((-len(binary))%4));vi=len(j['bufferViews']);j['bufferViews'].append({'buffer':0,'byteOffset':off,'byteLength':a.nbytes});ai=len(j['accessors']);d={'bufferView':vi,'componentType':ctype,'count':len(a),'type':typ}
 if typ=='VEC3':d['min']=a.min(0).tolist();d['max']=a.max(0).tolist()
 j['accessors'].append(d);return ai
pi=accessor(V,5126,'VEC3');ni=accessor(N,5126,'VEC3');ui=accessor(UV,5126,'VEC2');gray=len(j['materials']);j['materials'].append({'name':'UNPAINTED gray diagnostic body','pbrMetallicRoughness':{'baseColorFactor':[.45,.45,.45,1],'metallicFactor':0,'roughnessFactor':.8}});prims=[]
for mi,mt in [(0,gray),(1,g.j['meshes'][1]['primitives'][0]['material']),(2,g.j['meshes'][1]['primitives'][1]['material'])]:prims.append({'attributes':{'POSITION':pi,'NORMAL':ni,'TEXCOORD_0':ui},'indices':accessor(F[mat==mi].astype('<u4').ravel(),5125,'SCALAR'),'material':mt,'mode':4})
j['meshes']=[{'name':'FAILED_UNCAPPED_PRECAP213','primitives':prims}];j['nodes']=[{'mesh':0,'name':'FAILED uncapped neck prefix213','extras':{'privateUnacceptedFailedHeadSew213':True,'internalNeckCapMissing':True,'bodyUnpainted':True}}];j['scenes']=[{'nodes':[0]}];j['scene']=0;j.pop('skins',None);j.pop('animations',None);j['asset']['generator']='Rockhop FAILED head-sew213 retained prefix';j['buffers'][0]['byteLength']=len(binary);encoded=json.dumps(j,separators=(',',':')).encode();encoded+=b' '*((-len(encoded))%4);raw=struct.pack('<III',0x46546c67,2,28+len(encoded)+len(binary))+struct.pack('<II',len(encoded),0x4e4f534a)+encoded+struct.pack('<II',len(binary),0x004e4942)+binary;out=R/'failed-precap.glb';assert not out.exists();out.write_bytes(raw);check=mod.GLB(out);assert np.array_equal(check.array(pi),V) and np.array_equal(check.array(ui),UV);assert check.bin[:len(g.bin)]==g.bin;report={'status':'FAILED_UNCAPPED_PREFIX_INSPECTION_ONLY','sourcePrefixNPZSHA256':sha(R/'precap-partial.npz'),'output':str(out),'outputSHA256':sha(out),'bodyUnpaintedGray':True,'approvedHeadOriginalPBRImagesBINExact':True,'positionsAndUVFloat32RoundtripExact':True,'serializationMaximumCoordinateErrorM':float(abs(z['attributePositions']-V).max()),'notAWeldDefinition':'Float32 hides the1ulp64 inner cut alias; precise physical edge cache still required','limits':['No internal cap, no accepted join, rig or game-ready asset','Source-position array includes unreferenced original rows; bounding accessors include retained unused source points','No rendering performed pending parent failed-prefix review']};(E/'partial-export.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
