"""Read-only handoff inventory and small independent final-float32 cage checks."""
from pathlib import Path
from collections import Counter,defaultdict
import hashlib,json,os,ast,struct
os.environ['OPENBLAS_NUM_THREADS']='2';os.environ['OMP_NUM_THREADS']='2'
import numpy as np
from scipy.spatial.transform import Rotation
R=Path('/Users/raynos/projects/games/rockhop');F=R/'assets/blender/hero-remaster/rider/one-rider-v2/foundation-repair-task3';D=Path('/Users/raynos/Documents/Codex/2026-10-01/task-3');O=R/'docs/evidence/hero-remaster/one-rider-v2/independent-update193';sha=lambda b:hashlib.sha256(b).hexdigest()
def pin(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p.read_bytes())}
def dump(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
paths=[F/'README.md',R/'docs/evidence/hero-remaster/one-rider-v2/foundation-repair-task3/V7-qualification-handoff.txt',R/'docs/evidence/hero-remaster/one-rider-v2/foundation-repair-task3/Construction21-current-status.txt',R/'docs/evidence/hero-remaster/one-rider-v2/foundation-repair-task3/next-method-progress02.txt']
rel=['hoodie-repair02/rig-lane/mechanical-suite/quick-summary.json','hoodie-repair02/shape-lane/volume-lane/rounded-finite-gates.json','hoodie-repair02/qa-lane/uv-lower01/SLEEVE21-QA-HANDOFF.txt','hoodie-repair02/qa-lane/uv-lower01/tube21-material304/independent-material304-v7-control.json','hoodie-repair02/shape-lane/volume-lane/sleeve-tube03/CONSTRUCTION-STATUS21.json','hoodie-repair02/shape-lane/volume-lane/sleeve-tube03/source-sleeve-tube-rest21-uvchart.npz','hoodie-repair02/shape-lane/volume-lane/sleeve-tube03/responding_surface22.py','hoodie-repair02/shape-lane/volume-lane/source-embedding23/continuous-shell-handoff.json','hoodie-repair02/shape-lane/volume-lane/source-embedding23/source23-304-provenance.json','hoodie-repair02/qa-lane/continuous-sculpt179/HANDOFF.txt','hoodie-repair02/qa-lane/source-guided-cage182/HANDOFF.txt','hoodie-repair02/qa-lane/source-guided-cage182/independent-topology-seams.json','hoodie-repair02/qa-lane/source-guided-cage182/cage01.npz','hoodie-repair02/shape-lane/volume-lane/source-embedding23/source-guided-cage182-readonly/source-guided-cage182-collapse-attribution.json','hoodie-repair03/lower-foundation/pose-probe02/report.json','hoodie-repair03/inputs/source34-authoritative168-matrices.npz']
paths +=[F/p for p in rel];receipt=D/'deliverables/panel-surgery192/next-operator-receipt.json';assert sha(receipt.read_bytes())=='d696726dd830fe419f6db4ad556180fc50e3f61b316804809f4055aed0625b5e';paths.append(receipt)
for e in json.loads(receipt.read_text())['evidence']:
 p=receipt.parent/e['file'];assert sha(p.read_bytes())==e['sha256'];paths.append(p)
mesh_inventory=[pin(p)for root in [D/'hoodie-repair02',F]for p in sorted(root.rglob('*.glb'))]
# Re-measure only frozen cage; no foreign script execution, solves, exports or broad motion.
cage=F/'hoodie-repair02/qa-lane/source-guided-cage182/cage01.npz';n=np.load(cage,allow_pickle=False);P=n['p'];T=n['f'];U,q=np.unique(P,axis=0,return_inverse=True);tri=P[T].astype(float);area=np.linalg.norm(np.cross(tri[:,1]-tri[:,0],tri[:,2]-tri[:,0]),axis=1);pf=q[T];edges=Counter(tuple(sorted((int(t[k]),int(t[(k+1)%3]))))for t in pf for k in range(3));rawedges=Counter(tuple(sorted((int(t[k]),int(t[(k+1)%3]))))for t in T for k in range(3));counts=Counter(q.tolist());observed={'pDtype':str(P.dtype),'rawVertices':len(P),'triangles':len(T),'quads':len(n['quads']),'exactZeroAreaFaces':int((area==0).sum()),'doubleAreaBelow1e12':int((area<1e-12).sum()),'duplicatePositionGroups':sum(x>1 for x in counts.values()),'excessCoincidentRows':sum(x-1 for x in counts.values()),'rawOverincidentEdges':sum(c>2 for c in rawedges.values()),'physicalOverincidentOccurrenceEdges':sum(c>2 for c in edges.values()),'physicalOverincidentNonzeroEdges':sum(c>2 and e[0]!=e[1]for e,c in edges.items()),'namedBoundaryCounts':{k:len(n[k])for k in ['hoodIDs','hemIDs','cuffLIDs','cuffRIDs']},'fullMotionOrCollisionRun':False};assert observed['exactZeroAreaFaces']==170 and observed['physicalOverincidentOccurrenceEdges']==140
# Reusable GLB class only; other worker recipes are not executed.
reader=R/'assets/blender/hero-remaster/rider/one-rider-v2/rig-foundation167/prepare.py';cls=next(x for x in ast.parse(reader.read_text()).body if isinstance(x,ast.ClassDef)and x.name=='GLB');env={'Path':Path,'json':json,'struct':struct,'np':np,'Rotation':Rotation,'sha':sha};exec(compile(ast.Module(body=[cls],type_ignores=[]),str(reader),'exec'),env)
source=F/'deliverables/C19.glb';body=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/rig-adapter01/body-bind11/guarded-correction01/rider.glb');A=env['GLB'](source,sha(source.read_bytes()));B=env['GLB'](body,sha(body.read_bytes()));geom=[]
for mi,m in enumerate(A.d['meshes']):
 for pi,p in enumerate(m['primitives']):
  aa,at=A.primitive(mi,pi);bb,bt=B.primitive(mi,pi);geom.append({'mesh':mi,'primitive':pi,'positionsExact':bool(np.array_equal(aa['POSITION'],bb['POSITION'])),'normalsExact':bool(np.array_equal(aa['NORMAL'],bb['NORMAL'])),'uvExact':bool(np.array_equal(aa['TEXCOORD_0'],bb['TEXCOORD_0'])),'triangleRowsExact':bool(np.array_equal(at,bt)),'weightsExact':bool(np.array_equal(aa['WEIGHTS_0'],bb['WEIGHTS_0']))})
paths +=[source,body,reader];pin0=[pin(p)for p in paths]
report={'status':'READ_ONLY_INDEPENDENT_HANDOFF_AUDIT_NO_NEW_SOURCE_ACCEPTANCE','inputPins':pin0,'meshInventory':mesh_inventory,'independentCage182Checks':observed,'preferredC19Body11Comparison':geom,'C19RestBindMaxIdentityError':float(np.abs(A.rest()@A.ib()-np.eye(4)).max()),'finding':'No newer generally qualified garment or rig source found. V7 is unchanged authored clip control. Newer construction21/driver22, embedding23, sculpt179 and cage182 remain failed; actual current assets and exact hashes inventoried. Panel192 is a fresh distinct unbuilt graph/operator receipt handled by parent armhole specialist, not a better existing mesh.','scope':'Hash/inventory plus small finalfloat32 topology and rawGLB identity/bind checks only. Existing reports read; their films not replayed and broad rest/motion crossings not rerun. No anatomical/appearance/gameplay/mobile or source acceptance.','usableTechnique':'Use actual ordered source loops and retained halfedge donor incidence; interpolate continuous source section segments with provenance, maintain injective Float32 physical rings, nonzero material transition width and opposite sewn winding. Static weights, local ARAP, circular tube/profile tweaks and discontinuous cage attachments already falsified under their recorded tests.','allReadInputsUnchanged':all(pin(Path(x['path']))==x for x in pin0)};dump(O/'report.json',report);print(json.dumps({'meshPins':len(mesh_inventory),'inputPins':len(pin0),'independentCage':observed,'preferredGeometryComparisons':geom,'restBindError':report['C19RestBindMaxIdentityError']}))
