"""ONE encoding call per body/head mesh; no retry, sweep, save or adoption."""
import bpy,numpy as np,json,hashlib,traceback
from pathlib import Path
out=Path(__file__).resolve().parent;qa=out.parent;root=Path.cwd();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();prep=json.loads((qa/'normal79/preparation.json').read_text());ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';asset=root/'assets/blender/hero-remaster/rider/anatomical-foundation-2026-10-03/user-agent1';field=np.load(ev/'neck-interface102/candidate-fields-ancestry-corrected.npz');probes=np.load(ev/'neck-interface103/decoded-normal-probes.npz');prior=np.load(qa/'neck71/native-rest-read.npz');helper=(qa/'neck62/read-native.py').read_text();ns=dict(bpy=bpy,np=np,hashlib=hashlib);exec(compile(helper[helper.index('def digest('):helper.index('for label,path in paths.items():')],'read-only-fidelity-functions','exec'),ns);digest=ns['digest'];attrs=ns['attrs'];state=ns['state'];flat=ns['flat']
for p,h in prep['pins'].items():assert sha(root/p)==h['sha256'],p
arrays={};reference={};referenceRaw={};referenceIDs={}
bpy.ops.wm.open_mainfile(filepath=str(asset/'neck-interface28/auxiliary-restored.blend'))
for part in ['body','head']:
 obj=bpy.data.objects[('Bounded neck28 auxiliary-preserved body ' if part=='body' else 'Bounded neck27 triangulated head ')+'four, unaccepted'];m=obj.data;decoded=flat(m.corner_normals,'vector',3,np.float32);assert np.array_equal(decoded,probes[part+'BaseDecodedNormals']);reference[part]=decoded.copy();referenceRaw[part]=attrs(m).get('custom_normal',{'fields':{'value':np.empty((0,2),dtype=np.int32)}})['fields']['value'].copy();referenceIDs[part]={'vertices':flat(m.loops,'vertex_index',1,np.int32).ravel(),'polygonIDs':np.repeat(np.arange(len(m.polygons)),[p.loop_total for p in m.polygons])}
 arrays[part+'OriginalDecodedReference']=reference[part];arrays[part+'OriginalRawReferenceEncoding']=referenceRaw[part]
bpy.ops.wm.open_mainfile(filepath=str(asset/'neck-interface29/geometry-only-feasibility.blend'))
originalNames=list(bpy.data.objects.keys());originalStates={n:state(bpy.data.objects[n]) for n in originalNames};materialBefore=ns['materials']();imagesBefore={im.name:{'packedSHA256':hashlib.sha256(bytes(im.packed_file.data)).hexdigest() if im.packed_file else None,'size':list(im.size),'colour':im.colorspace_settings.name,'filepath':im.filepath} for im in bpy.data.images};rig=bpy.data.objects['Independent anatomical foundation rig'];boneNames=list(rig.data.bones.keys());assert len(boneNames)==51;records=[];exceptions=[]
def equalrows(A,B):
 assert A.shape==B.shape and A.dtype==B.dtype
 aa=np.ascontiguousarray(A).view(np.uint8).reshape(len(A),-1);bb=np.ascontiguousarray(B).view(np.uint8).reshape(len(B),-1);return (aa==bb).all(1)
def metrics(decoded,target,ids):
 A=decoded[ids].astype(float);B=target[ids].astype(float);e=A-B;component=np.abs(e);vector=np.linalg.norm(e,axis=1);normA=np.linalg.norm(A,axis=1);normB=np.linalg.norm(B,axis=1);valid=(normA>0)&(normB>0);angle=np.full(len(ids),np.nan);angle[valid]=np.degrees(np.arctan2(np.linalg.norm(np.cross(A[valid],B[valid]),axis=1),np.einsum('ij,ij->i',A[valid],B[valid])));k=int(vector.argmax()) if len(ids) else None;ka=int(np.nanargmax(angle)) if valid.any() else None;bits=decoded[ids].view(np.uint32)==target[ids].view(np.uint32)
 return {'corners':len(ids),'bitwiseEqualCorners':int(bits.all(1).sum()),'bitwiseEqualComponents':int(bits.sum()),'maxAbsComponentError':float(component.max()) if len(ids) else 0.,'maxVectorError':float(vector.max()) if len(ids) else 0.,'meanVectorError':float(vector.mean()) if len(ids) else 0.,'maxAngularErrorDeg':float(angle[ka]) if ka is not None else None,'maxVectorCornerID':int(ids[k]) if k is not None else None,'maxAngularCornerID':int(ids[ka]) if ka is not None else None,'zeroOrInvalidDirectionRows':int((~valid).sum()),'targetLengthMaxAbsResidualFrom1':float(np.abs(normB-1).max()) if len(ids) else 0.,'decodedLengthMaxAbsResidualFrom1':float(np.abs(normA-1).max()) if len(ids) else 0.}
def stripNormal(s):
 s=json.loads(json.dumps(s));s['mesh'].pop('cornerNormals');s['mesh']['attributes'].pop('custom_normal',None);return s
for part in ['body','head']:
 original=bpy.data.objects['Bounded neck29 geometry-only '+part+' four, unaccepted'];scratch=original.copy();scratch.name='Agent3 diagnostic normal80 scratch '+part;scratch.data=original.data.copy();scratch.data.name='Agent3 normal80 scratch mesh '+part;beforeState=state(scratch);assert beforeState==state(original);m=scratch.data;position=flat(m.vertices,'co',3,np.float32);assert np.array_equal(position,field[part+'RestXYZ']) and np.array_equal(position,prior[part+'Positions']);m.calc_loop_triangles();triangles=np.array([t.vertices[:] for t in m.loop_triangles],np.int32);assert np.array_equal(triangles,field[part+'Triangles']);vertices=flat(m.loops,'vertex_index',1,np.int32).ravel();polygonIDs=np.repeat(np.arange(len(m.polygons)),[p.loop_total for p in m.polygons]);assert np.array_equal(vertices,referenceIDs[part]['vertices']) and np.array_equal(polygonIDs,referenceIDs[part]['polygonIDs']);beforeAttrs=attrs(m);raw=beforeAttrs.get('custom_normal',{'fields':{'value':np.empty((0,2),dtype=np.int32)}})['fields']['value'];assert 'custom_normal' not in beforeAttrs or (beforeAttrs['custom_normal']['kind']=='INT16_2D' and beforeAttrs['custom_normal']['domain']=='CORNER');assert np.array_equal(raw,referenceRaw[part]);before=flat(m.corner_normals,'vector',3,np.float32);assert np.array_equal(before,probes[part+'Alpha1.0DecodedNormals']);protected=probes[part+'ProtectedCornerIDs'];untargeted=np.setdiff1d(np.arange(len(before)),protected);target=before.copy();target[protected]=reference[part][protected];targetSaved=target.copy();error=None
 # EXACTLY ONE setter invocation. All subsequent operations only read/verify.
 try:m.normals_split_custom_set(target.tolist());m.update()
 except Exception as e:error=str(e);exceptions.append({'part':part,'error':error,'traceback':traceback.format_exc()})
 after=flat(m.corner_normals,'vector',3,np.float32);afterAttrs=attrs(m);afterState=state(scratch);changes=[]
 for name in sorted(set(beforeAttrs)|set(afterAttrs)):
  a=beforeAttrs.get(name);b=afterAttrs.get(name)
  if a is None or b is None:changes.append({'attribute':name,'added':a is None,'removed':b is None,'domain':(b or a)['domain'],'kind':(b or a)['kind'],'rows':len(next(iter((b or a)['fields'].values()))) if (b or a)['fields'] else 0});continue
  for key in set(a['fields'])|set(b['fields']):
   x=a['fields'][key];y=b['fields'][key];same=equalrows(x,y);ids=np.flatnonzero(~same)
   if len(ids):changes.append({'attribute':name,'field':key,'domain':a['domain'],'kind':a['kind'],'changedRows':len(ids),'changedIDsArray':part+'_'+name+'_'+key+'_ChangedIDs'});arrays[part+'_'+name+'_'+key+'_ChangedIDs']=ids;arrays[part+'_'+name+'_'+key+'_Before']=x.copy();arrays[part+'_'+name+'_'+key+'_After']=y.copy()
 rawAfter=afterAttrs['custom_normal']['fields']['value'];rawChanged=~equalrows(raw,rawAfter) if len(raw) else np.ones(len(rawAfter),dtype=bool);decodedChanged=~equalrows(before,after);preserved=stripNormal(beforeState)==stripNormal(afterState);reencodedProtected=np.flatnonzero(rawChanged&np.isin(np.arange(len(rawAfter)),protected));reencodedUntargeted=np.flatnonzero(rawChanged&~np.isin(np.arange(len(rawAfter)),protected));afterProtected=metrics(after,reference[part],protected);untargetedMetrics=metrics(after,before,untargeted);beforeProtected=metrics(before,reference[part],protected);ids=set([735 if part=='head' else 18942]);ids.update(z for z in [afterProtected['maxVectorCornerID'],afterProtected['maxAngularCornerID'],untargetedMetrics['maxVectorCornerID']] if z is not None);witness=[]
 for corner in sorted(ids):
  pi=int(polygonIDs[corner]);face=m.polygons[pi];witness.append({'nativeCornerLoopID':corner,'nativeVertexID':int(vertices[corner]),'candidatePolygonID':pi,'checkpointPolygonID':int(field[part+'CandidatePolygonToCheckpointPolygon'][pi]),'polygonNativeVertexIDs':list(face.vertices),'sourceCornerAncestry':field[part+'CornerAttributeEdgeSources'][corner].tolist(),'protected':bool(corner in protected),'originalTargetObjectSpaceNormalF32':reference[part][corner].tolist(),'setterInputF32':targetSaved[corner].tolist(),'failedBeforeDecodedF32':before[corner].tolist(),'scratchAfterDecodedF32':after[corner].tolist(),'originalRawEncoding':referenceRaw[part][corner].tolist() if len(referenceRaw[part]) else None,'failedBeforeRawEncoding':raw[corner].tolist() if len(raw) else None,'scratchAfterRawEncoding':rawAfter[corner].tolist()})
 arrays.update({part+'ProtectedCornerIDs':protected.copy(),part+'UntargetedCornerIDs':untargeted,part+'LoopVertexIDs':vertices,part+'LoopPolygonIDs':polygonIDs,part+'SourceCornerAncestry':field[part+'CornerAttributeEdgeSources'],part+'PolygonToCheckpointPolygon':field[part+'CandidatePolygonToCheckpointPolygon'],part+'SetterInputF32':targetSaved,part+'FailedBeforeDecodedF32':before,part+'ScratchAfterDecodedF32':after,part+'FailedRawEncoding':raw.copy(),part+'ScratchRawEncoding':rawAfter.copy(),part+'ReencodedProtectedCornerIDs':reencodedProtected,part+'ReencodedUntargetedCornerIDs':reencodedUntargeted,part+'DecodedChangedCornerIDs':np.flatnonzero(decodedChanged)})
 records.append({'part':part,'originalObject':original.name,'scratchObject':scratch.name,'scratchMesh':m.name,'nativeVertices':len(position),'nativeLoops':len(before),'nativePolygons':len(m.polygons),'nativeTriangles':len(triangles),'setterCalls':1,'setterError':error,'normalRepresentation':{'bufferExistedBefore':bool(len(raw)),'originalBodyUsesGeneratedNormals':part=='body' and not len(raw),'attribute':'custom_normal','domain':'CORNER','kind':'INT16_2D','RNAReadValuesDtype':'int32 widened exact signed-short values','decoderDtype':'Float32 object-space XYZ','inputDtype':'Original Float32 values expanded to Python then RNA Float32; internal API normalizes once','shortScale':32767,'normalDomain':str(m.normals_domain) if hasattr(m,'normals_domain') else None,'hasCustomNormals':m.has_custom_normals},'rawEncodingChangedProtectedCorners':len(reencodedProtected),'rawEncodingChangedUntargetedCorners':len(reencodedUntargeted),'decodedChangedProtectedCorners':int(decodedChanged[protected].sum()),'decodedChangedUntargetedCorners':int(decodedChanged[untargeted].sum()),'beforeErrorAgainstOriginalProtected':beforeProtected,'afterErrorAgainstOriginalProtected':afterProtected,'untargetedErrorAgainstFailedBefore':untargetedMetrics,'allFieldsExceptNormalBufferAndDecodedOutputExact':preserved,'rawAttributeChanges':changes,'beforeState':beforeState,'afterState':afterState,'witnesses':witness});print('ONE_ENCODING_TEST',part,'preservation',preserved,'rawchanged',len(reencodedProtected),len(reencodedUntargeted),'errors',afterProtected,flush=True)
# Verify every original object, all binding controls/materials/images and original input files.
originalUnchanged={n:state(bpy.data.objects[n])==originalStates[n] for n in originalNames};assert all(originalUnchanged.values());assert ns['materials']()==materialBefore;imagesAfter={im.name:{'packedSHA256':hashlib.sha256(bytes(im.packed_file.data)).hexdigest() if im.packed_file else None,'size':list(im.size),'colour':im.colorspace_settings.name,'filepath':im.filepath} for im in bpy.data.images};assert imagesAfter==imagesBefore;assert list(rig.data.bones.keys())==boneNames
for p,h in prep['pins'].items():assert sha(root/p)==h['sha256'],p
np.savez_compressed(out/'normal-buffer-test.npz',**arrays);report={'status':'ONE_PRIVATE_SCRATCH_NORMAL_ENCODING_DIAGNOSTIC_UNACCEPTED','blender':bpy.app.version_string,'blenderBuildHash':bpy.app.build_hash.decode(),'recipeSHA256':sha(__file__),'preparationCommit':'51fdad228e02f69e241bb8006cc86691937c37b0','testCalls':sum(z['setterCalls'] for z in records),'parts':records,'exceptions':exceptions,'originalObjectStatesExact':originalUnchanged,'original51RigBindPoseAndAllFullFourControlsExact':True,'originalMaterialsAndImagesExact':True,'all31InputPinsUnchanged':True,'arrayArchiveSHA256':sha(out/'normal-buffer-test.npz'),'noSourceOrScratchNativeSaved':True,'limits':['One setter call per body/head part only; no retry, parameter/precision/representation sweep, fit/geometry/weight solve or adoption.','Normal-buffer and unintended propagated fields are measured on in-memory scratch copies only; no original source actor/material/rig/pose edit or save.','Angular error uses atan2(cross,dot) in Float64 of actual Float32 decoded and target values, separating direction from vector length. No visual acceptance or universal quantization bound.','Failed102geometry remains failed. No new render/film/model/GPU/install/delivery/publication/scope expansion; allM0-M5open.']};(out/'test-report.json').write_text(json.dumps(report,indent=2)+'\n');print('ONE_TEST_AND_VERIFICATION_FINISHED_SOURCE_OBJECTS_AND_FILES_EXACT',flush=True)
