"""Verify retained ONE-test fields; no Blender/API or second experiment."""
import json,hashlib
from pathlib import Path
import numpy as np
out=Path(__file__).resolve().parent;qa=out.parent;root=Path.cwd();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();r=json.loads((out/'test-report.json').read_text());d=np.load(out/'normal-buffer-test.npz');prep=json.loads((qa/'normal79/preparation.json').read_text());assert r['testCalls']==2 and not r['exceptions'];source=np.load(root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1/neck-interface103/decoded-normal-probes.npz');scope=json.loads((qa/'body59/proposal.json').read_text())['preciseInitialAuthoringMargin'];boundary=np.load(root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1/neck-interface96/ordered-boundaries.npz');rows=[]
for s in r['parts']:
 p=s['part'];ids=d[p+'ProtectedCornerIDs'];assert np.array_equal(d[p+'OriginalDecodedReference'],source[p+'BaseDecodedNormals']) and np.array_equal(ids,source[p+'ProtectedCornerIDs']);assert np.array_equal(d[p+'SetterInputF32'][ids],source[p+'BaseDecodedNormals'][ids]);u=d[p+'UntargetedCornerIDs'];assert np.array_equal(d[p+'SetterInputF32'][u],d[p+'FailedBeforeDecodedF32'][u]);bits=d[p+'ScratchAfterDecodedF32'][ids].view(np.uint32)==d[p+'OriginalDecodedReference'][ids].view(np.uint32);assert int(bits.all(1).sum())==s['afterErrorAgainstOriginalProtected']['bitwiseEqualCorners'];assert int(bits.sum())==s['afterErrorAgainstOriginalProtected']['bitwiseEqualComponents'];a=s['beforeState'];b=s['afterState'];keys=['positions','polygons','loops','edges','materials','smooth','materialIndices','weights','groups','shapeKeys'];checks={k:a['mesh'][k]==b['mesh'][k] for k in keys};checks.update({k:a[k]==b[k] for k in a if k!='mesh'});assert all(checks.values());otherAttrs={}
 for name,attr in a['mesh']['attributes'].items():
  if name!='custom_normal':otherAttrs[name]=attr==b['mesh']['attributes'][name];assert otherAttrs[name],(p,name)
 extra=set(b['mesh']['attributes'])-set(a['mesh']['attributes']);assert extra==({'custom_normal','sharp_edge'} if p=='body' else set());newsharp=None
 if p=='body':
  n=18450;z=np.zeros((n,1),np.bool_);h=hashlib.sha256(z.tobytes()).hexdigest();assert h==b['mesh']['attributes']['sharp_edge']['fields']['value'];newsharp={'attributeAdded':True,'edges':n,'allValuesFalseVerifiedByCompleteBufferSHA256':h,'trueEdgeFlags':0,'schemaChangeStillOutsideStrictNormalBufferOnlyAllowance':True};assert not a['mesh']['hasCustomNormals'] and b['mesh']['hasCustomNormals'];assert len(d[p+'OriginalRawReferenceEncoding'])==len(d[p+'FailedRawEncoding'])==0
 sub={}
 if p=='head':
  he=set(scope['headInitialBoundaryLedNativeVertexIDs']);alias=boundary['headPositionAlias'];partial={int(v) for v in np.unique(alias[list(he)]) if not set(np.flatnonzero(alias==v))<=he};pin=[v for v in he if int(alias[v]) in partial];loop=d[p+'LoopVertexIDs'];inside=ids[np.isin(loop[ids],pin)];outside=ids[~np.isin(loop[ids],pin)];assert len(inside)==173
  for label,q in [('partialAliasPinnedInside',inside),('otherProtected',outside)]:
   A=d[p+'ScratchAfterDecodedF32'][q].astype(float);B=d[p+'OriginalDecodedReference'][q].astype(float);bits=d[p+'ScratchAfterDecodedF32'][q].view(np.uint32)==d[p+'OriginalDecodedReference'][q].view(np.uint32);v=np.linalg.norm(A-B,axis=1);ang=np.degrees(np.arctan2(np.linalg.norm(np.cross(A,B),axis=1),(A*B).sum(1)));sub[label]={'corners':len(q),'bitwiseEqualCorners':int(bits.all(1).sum()),'maxVectorError':float(v.max()),'maxAngularErrorDeg':float(ang.max()),'maxErrorCornerID':int(q[v.argmax()])};assert all(int(x) in ids for x in inside)
  raw=d[p+'OriginalRawReferenceEncoding'];sub['originalProtectedNoOpEncodedCorners']=int((raw[ids,0]==0).sum());sub['afterProtectedNoOpEncodedCorners']=int((d[p+'ScratchRawEncoding'][ids,0]==0).sum())
 rows.append({'part':p,'geometryTopologyMaterialWeightsGroupsTransformsModifiersConstraintsAndShapeKeysExact':checks,'allExistingNonNormalAttributeFieldsExact':otherAttrs,'addedAttributes':sorted(extra),'bodySharpEdgeCreation':newsharp,'protectedSubsets':sub})
for p,h in prep['pins'].items():assert sha(root/p)==h['sha256'],p
stable=json.loads((qa/'gate78/source-before.json').read_text())
for p,h in stable['allInputAndStableEvidencePins'].items():assert sha(root/p)==h,p
z={'status':'RETAINED_SINGLE_ENCODING_TEST_VERIFIED_NO_REENCODE','recipeSHA256':sha(__file__),'testReportSHA256':sha(out/'test-report.json'),'arraySHA256':sha(out/'normal-buffer-test.npz'),'parts':rows,'originalSourceAndAll31PreparationPinsExact':True,'all191PriorStablePinsExact':True,'oneActualEncodingPerPart':True,'preflightFailureBeforeAnyEncoding':'Initial reader assumed body had custom_normal; body has none. Rejected preflight recipe/log retained. Corrected before any setter; no precision/parameter/encoding retry.','limits':['This is verification of retained arrays and immutable-field hashes only, not another API conversion.','Measured direction/vector error is not exact original decoded Float32 equality or root visual acceptance. No universal best-possible error or normal-encoding impossibility proof.']};(out/'verification.json').write_text(json.dumps(z,indent=2)+'\n');print(json.dumps(rows,indent=2))
