from pathlib import Path
import json,shutil,hashlib,html
root=Path('/Users/raynos/projects/games/rockhop');leaf=root/'docs/evidence/hero-remaster/progress-gallery-2026-10-07';site=leaf/'site-source';out=site/'build';(out/'photos').mkdir(parents=True,exist_ok=True)
manifest=json.loads((leaf/'media-inventory.json').read_text());review=json.loads((root/'docs/evidence/hero-remaster/audit-2026-10-07-agent2/played-review.json').read_text());catalog=[]
for movie,record in zip(manifest['movies'],review['movies']):
 frames=record['capturedFramePins'];indices=sorted(set(round(i*(len(frames)-1)/3) for i in range(4)));pictures=[]
 for n in indices:
  src=Path(frames[n]['path']);name=f"photos/{movie['index']:02d}-{n:04d}.png";shutil.copyfile(src,out/name);pictures.append({'src':name,'time':frames[n]['mediaTime'],'original':str(src.relative_to(root)),'sha256':frames[n]['sha256']})
 catalog.append({'index':movie['index'],'title':movie['title'],'version':movie['sourceRenderVersion'],'status':movie['status'],'photos':pictures})
(out/'catalog.json').write_text(json.dumps(catalog,indent=2)+'\n')
esc=html.escape
byid={m['index']:m for m in catalog}
def imagecell(index,label):
 m=byid[index];p=m['photos'][0]
 return f'<figure><figcaption><strong>{esc(label)}</strong><span>{esc(m["title"])}</span></figcaption><a href="{p["src"]}"><img src="{p["src"]}" alt="{esc(m["title"])}" width="640" height="640"></a></figure>'
featured=json.loads((leaf/'featured-videos.json').read_text())
(out/'videos').mkdir(exist_ok=True)
video_cards=''
for v in featured['videos']:
 src=root/v['source'];assert hashlib.sha256(src.read_bytes()).hexdigest()==v['sha256']
 shutil.copyfile(src,out/v['src'])
 poster=byid[v['index']]['photos'][1]['src']
 duration=f"{v['durationSeconds']:.1f}s"
 video_cards+=f'<article class="video-card"><h3><span class="rank">{v["rank"]:02d}</span> {esc(v["title"])}</h3><video controls playsinline muted preload="none" poster="{poster}" aria-label="{esc(v["title"])}"><source src="{v["src"]}" type="video/mp4"></video><p class="duration">{duration} · historical, unaccepted evidence</p><p>{esc(v["why"])}</p></article>'
featured_section='<section class="featured" aria-labelledby="featured-heading"><h2 id="featured-heading">Watch these five</h2><p>Five clips in priority order · 1 minute 38 seconds total. Start with the full rider, then inspect the parts that still need work. Each plays only when you press play.</p><div class="video-grid">'+video_cards+'</div></section>'
(out/'featured-videos.json').write_text(json.dumps(featured,indent=2)+'\n')
pairs=''
for title,caption,a,b,al,bl in [('Body construction','Earlier and later candidates. Pose and camera differ; both remain unaccepted.',18,16,'Before · body02','After · body05'),('Glove fit','Original dark glove appearance source and the later source-versus-fit diagnostic. Colored fingers are diagnostic labels.',2,14,'Before · donor','After · fit trial'),('Hoodie deformation','Appearance donor and failed native skinning trial. This comparison shows the source-to-wearable gap.',0,4,'Before · appearance source','After · skinning trial')]:
 pairs+=f'<section class="comparison"><h2>{esc(title)}</h2><p>{esc(caption)}</p><div class="pair">{imagecell(a,al)}{imagecell(b,bl)}</div></section>'
cards=''
for m in catalog:
 pictures=''.join(f'<a href="{p["src"]}"><img loading="lazy" src="{p["src"]}" alt="{esc(m["title"])} at {p["time"]:.2f} seconds"><span>{p["time"]:.2f}s</span></a>' for p in m['photos'])
 cards+=f'<details><summary>{m["index"]+1:02d} · {esc(m["title"])}</summary><p>{esc(m["version"])} · source or unaccepted trial</p><div class="strip">{pictures}</div></details>'
(out/'index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rockhop · rider progress</title><meta name="description" content="Before-and-after rider photos and five priority videos with dated source versions and honest review status."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%2317191e'/%3E%3Cpath d='M8 25V7h9c10 0 10 12 1 13l7 5h-8l-5-5v5zm5-13v4h4c3 0 3-4 0-4z' fill='%23efb638'/%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"></head><body><main><header><div class="brand">ROCKHOP <span>RIDER REVIEW</span></div><h1>Before &amp; after</h1><p class="lead">Latest available visual record · October 7, 2026</p><aside><strong>Historical review snapshot · not the new rebuild.</strong><p>These October 3–5 source renders were reviewed or preserved on October 7. The first-principles rebuild is separate; this gallery does not show a finished new rider. None of these trials establishes acceptance.</p></aside></header>'''+featured_section+pairs+'''<section class="library"><h2>All 21 visual sequences</h2><p>Four unedited playback photos per sequence. Open a photo for its full size. The five priority videos are above. The complete 21-video packet and all 1,354 playback photos were supplied separately in chat.</p>'''+cards+'''</section><footer>Window: October 5, 14:49 to October 7, 14:49 · Panama time. Playback snapshots preserve source images; they are not new Blender renders. “After” describes version order and does not mean accepted.</footer></main></body></html>''')
(out/'style.css').write_text('''*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:#111318;color:#edf0f4;font:16px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1180px;margin:auto;padding:28px}.brand{color:#efb638;font-weight:850;letter-spacing:.12em}.brand span{color:#b9c0ca;font-size:.875rem;margin-left:16px}h1{font-size:clamp(2rem,5vw,3rem);line-height:1.15;letter-spacing:-.04em;margin:18px 0 8px}h2{font-size:1.4rem;line-height:1.3;margin:0 0 8px}.lead,p{color:#bdc5d0;margin:0 0 18px}aside{border-left:4px solid #efb638;background:#1b1f27;padding:16px 20px;margin:22px 0 32px}aside strong{font-size:1rem;color:#f6ce76}aside p{margin:8px 0 0}.comparison{margin:0 0 42px}.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}figure{margin:0;background:#20242d;border:1px solid #3b414c}figcaption{padding:14px 18px}figcaption strong{display:block;font-size:1rem}figcaption span{font-size:.875rem;color:#bcc4d0}img{display:block;max-width:100%;width:100%;height:auto}figure img{aspect-ratio:1;object-fit:contain;background:#373c43}.library{border-top:1px solid #3b414c;padding-top:30px}details{border:1px solid #39414e;border-radius:5px;margin:12px 0;background:#1b2029}summary{padding:16px;font-weight:650;cursor:pointer;min-height:52px}details p{padding:0 16px;font-size:.875rem}.strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:0 16px 16px}.strip a{text-decoration:none;color:#cbd4e0}.strip img{aspect-ratio:1;object-fit:contain;background:#383d45}.strip span{font-size:.875rem;display:block;padding:5px 0}.featured{margin:0 0 42px}.video-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.video-card{background:#20242d;border:1px solid #3b414c;padding:16px}.video-card:first-child{grid-column:1/-1}.video-card h3{font-size:1.1rem;margin:0 0 12px;line-height:1.4}.rank{color:#efb638;margin-right:6px}.video-card video{display:block;width:100%;max-height:560px;background:#111318}.video-card p{margin:12px 0 0}.video-card .duration{font-size:.875rem;color:#efb638}a:focus-visible,summary:focus-visible{outline:3px solid #efb638;outline-offset:3px}footer{color:#aab4c1;font-size:.875rem;border-top:1px solid #39414e;margin-top:30px;padding-top:20px}@media(max-width:650px){main{padding:18px}.video-grid{grid-template-columns:1fr}.pair{gap:12px;grid-template-columns:1fr}.strip{grid-template-columns:repeat(2,minmax(0,1fr))}.brand span{display:block;margin:5px 0 0}h1{margin-top:18px}}''')
host=site/'.openai/hosting.json';d=json.loads(host.read_text());d['static']={'directory':'build'};host.write_text(json.dumps(d,indent=2)+'\n')

print(json.dumps({'sitePhotos':sum(len(m['photos']) for m in catalog),'siteBytes':sum(p.stat().st_size for p in out.rglob('*') if p.is_file()),'comparisons':3,'sequences':21}))
