from pathlib import Path
import json,hashlib,struct,ast
import numpy as np
E=Path('docs/evidence/hero-remaster/finish-2026-10-05/wardrobe');A=Path('assets/blender/hero-remaster/rider/finish-2026-10-05/wardrobe');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();rows=[]
for name in ['hoodie','jeans','gloves','boots']:
 d=json.loads((E/(name+'-source.json')).read_text());src=Path(d['source']['path']);assert sha(src)==d['source']['sha256'];raw=src.read_bytes();n=struct.unpack_from('<I',raw,12)[0];g=json.loads(raw[20:20+n]);o=28+n;binary=raw[o:]
 def get(i):
  a=g['accessors'][i];v=g['bufferViews'][a['bufferView']];typ={5126:'<f4',5125:'<u4',5123:'<u2'}[a['componentType']];c={'SCALAR':1,'VEC2':2,'VEC3':3}[a['type']];sz=np.dtype(typ).itemsize
  return np.ndarray((a['count'],c),dtype=typ,buffer=binary,offset=v.get('byteOffset',0)+a.get('byteOffset',0),strides=(v.get('byteStride',sz*c),sz))
 p=g['meshes'][0]['primitives'][0];xyz=get(p['attributes']['POSITION']);f=get(p['indices']).reshape(-1,3);uv=get(p['attributes']['TEXCOORD_0']);clean=np.load(d['cleanedDonor']['path']);proto=np.load(d['prototype']['npz']['path']);ids=clean['originalTriangleRows'];assert np.array_equal(clean['vertices'][clean['faces']],xyz[f[ids]]);assert np.array_equal(clean['originalCornerUV'],uv[f[ids]]);q=(xyz[f[proto['originalTriangleRows']]]*proto['barycentric'][:,:,None]).sum(1);gap=np.linalg.norm(q-proto['vertices'],axis=1);assert gap.max()<1e-12 and np.isfinite(proto['vertices']).all();assert np.linalg.det(np.array(d['sourceFrontToBlenderBasisOnly'])[:3,:3])==1
 for key,m in d['maps'].items():
  assert sha(m['path'])==m['sha256']
  material=g['materials'][p['material']]['pbrMetallicRoughness'];image=g['images'][g['textures'][material[key]['index']]['source']];view=g['bufferViews'][image['bufferView']];begin=view.get('byteOffset',0);assert Path(m['path']).read_bytes()==binary[begin:begin+view['byteLength']]
 assert sha(d['cleanedDonor']['path'])==d['cleanedDonor']['sha256'];assert sha(d['prototype']['npz']['path'])==d['prototype']['npz']['sha256']
 rows.append({'item':name,'originalHashMatches':True,'retainedTriangleAndUVExact':True,'prototypeAncestryMaxSourceUnits':float(gap.max()),'prototypeFaces':len(proto['faces']),'properBasisDeterminant':1,'mapHashesMatch':True})
for p in [A/'prepare.py',A/'register.py']:ast.parse(p.read_text())
reg=json.loads((E/'semantic-registration.json').read_text());assert sha(reg['foundation']['path'])==reg['foundation']['sha256'];r={'status':'PARENT_SOURCE_PREPARATION_READBACK_PASS_UNACCEPTED','items':rows,'foundationHashMatches':True,'limits':['Source preparation only; prototypeUV aliases remain disclosed, and no fitted/cavity/skin/contact/native/motion/art acceptance.','No new dense source or production mesh generated by this readback.']};(E/'parent-readback.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r))
