"""Encode the one frozen neck99 capture; repeats/crops never alter fields."""
import hashlib
import json
import subprocess
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[6]
out = root / 'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1/neck-interface99/played'
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
render_path = out / 'render.json'
render = json.loads(render_path.read_text())
assert render['sampledSources'] == 309 and render['sourceGeometryUVMaterialsAndFilePinsExact']
assert not (out / 'movie.json').exists()
font_path = Path('/System/Library/Fonts/Supplemental/Arial.ttf')
bold_path = Path('/System/Library/Fonts/Supplemental/Arial Bold.ttf')
font = ImageFont.truetype(str(font_path), 24)
small = ImageFont.truetype(str(font_path), 20)
bold = ImageFont.truetype(str(bold_path), 26)
prepared = out / 'encoded-frames'; prepared.mkdir(exist_ok=True)
fps = 60; sequence = []; receipt = []

def encode_frame(row, focus, hold=False):
    raw_path = out / 'frames' / f"{row['number']:04d}.png"
    assert sha(raw_path) == row['PNG_SHA256']
    raw = Image.open(raw_path).convert('RGB')
    canvas = Image.new('RGB', (1920, 1440), (25, 29, 31))
    if focus:
        for view in row['views']:
            x, y, w, h = view['neckContextCropXYWH']
            crop = raw.crop((x, y, x + w, y + h)).resize((600, 560), Image.Resampling.LANCZOS)
            canvas.paste(crop, (view['column'] * 640 + 20, 80 + view['row'] * 640 + 40))
    else: canvas.paste(raw, (0, 80))
    draw = ImageDraw.Draw(canvas)
    domain = 'NATIVE EXISTING FK' if row['domain'] == 'native' else 'ACTUAL47 NATIVE RECONSTRUCTION'
    pause = ' | PAUSED EXACT CAPTURED WITNESS' if hold else ''
    draw.text((16, 10), f"{domain} | source {row['sourceIndex']} | t={row['sourceTimeS']:.6f}s{pause}", font=bold, fill='white')
    draw.text((16, 44), ('NECK CONTEXT — same captured sequence' if focus else 'FULL CONTEXT') + ' | front / left side / rear', font=font, fill='white')
    # Labels occupy added margins or the inter-row gap, never the raw actor.
    draw.text((16, 1360), 'Top: original FOUR wearer   |   Bottom: frozen failed neck27 FOUR', font=font, fill='white')
    counts = row['nativeFourLocalContact']
    draw.text((16, 1392), f"Local pairs: body-self {counts['bodySelf']['pairs']} / head-self {counts['headSelf']['pairs']} / body-head {counts['bodyHead']['pairs']} — counts are not a visible-art verdict", font=small, fill=(220, 225, 226))
    return canvas

for focus in [False, True]:
    for domain in ['native', 'actual47']:
        rows = [row for row in render['frames'] if row['domain'] == domain]
        for row in rows:
            name = f"{len(receipt):04d}.png"; target = prepared / name
            encode_frame(row, focus).save(target)
            copies = 5 if domain == 'native' else 2
            sequence.extend([name] * copies)
            receipt.append({'image': name, 'domain': domain, 'sourceIndex': row['sourceIndex'], 'kind': 'moving focus' if focus else 'moving full', 'repeats': copies})
        source_id = 72 if domain == 'native' else 668
        row = next(row for row in rows if row['sourceIndex'] == source_id)
        name = f"{len(receipt):04d}.png"; encode_frame(row, focus, True).save(prepared / name)
        sequence.extend([name] * (3 * fps))
        receipt.append({'image': name, 'domain': domain, 'sourceIndex': source_id, 'kind': 'paused captured witness', 'focus': focus, 'repeats': 3 * fps})
# A concat list with repeated exact PNGs gives the archived sample cadence;
# no video interpolation or new pose holds were generated by Blender.
concat = out / 'sequence.txt'
concat.write_text(''.join("file 'encoded-frames/" + name + "'\nduration 0.016666666666666667\n" for name in sequence))
movie = out / 'failed-neck27-matched.mp4'
command = ['/opt/homebrew/bin/ffmpeg', '-v', 'error', '-f', 'concat', '-safe', '0', '-i', str(concat),
    '-r', str(fps), '-frames:v', str(len(sequence)), '-c:v', 'libx264', '-preset', 'medium', '-crf', '21', '-pix_fmt', 'yuv420p', '-an', '-movflags', '+faststart', str(movie)]
subprocess.run(command, check=True)
decoded = subprocess.run(['/opt/homebrew/bin/ffmpeg', '-v', 'error', '-i', str(movie), '-f', 'null', '-'], capture_output=True, text=True)
assert decoded.returncode == 0 and not decoded.stderr
probe = json.loads(subprocess.check_output(['/opt/homebrew/bin/ffprobe', '-v', 'error', '-show_streams', '-show_format', '-of', 'json', str(movie)], text=True))
assert all(stream['codec_type'] != 'audio' for stream in probe['streams'])
report = {'status': 'UNACCEPTED_ONE_FAILED_NECK_PROOF_ENCODED', 'movie': str(movie.relative_to(root)), 'sha256': sha(movie),
    'bytes': movie.stat().st_size, 'dimensions': [1920, 1440], 'fps': fps, 'frames': len(sequence), 'durationS': len(sequence) / fps,
    'sourceRenderSHA256': sha(render_path), 'recipeSHA256': sha(__file__), 'fontPins': {str(p): sha(p) for p in [font_path, bold_path]},
    'audioStreams': 0, 'fullDecodeErrors': 0, 'rows': receipt,
    'timing': 'Native every4th48Hz sample repeated5at60fps; actual47every4th120Hz sample repeated2. Final703 has8.333ms cadence padding. Focus repeats the same PNGs. Native72/actual668witnesses repeat exactly3s, explicitly paused; no interpolation/controller/new poses.',
    'limits': ['One paired baseline/candidate capture, full context and same-image neck crops. Parent alone judges played appearance.',
        'Frozen98auxiliary omission remains; correction follows current99checkpoint. Contact and actual47identity failures are retained, never waived.',
        'Silent technical decode is not moving-art/device/player/engine acceptance. All M0-M5 open.']}
(out / 'movie.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps({k: report[k] for k in ['status', 'movie', 'sha256', 'bytes', 'durationS', 'frames']}, indent=2))
