"""Read-only receipt recovery after saved/reopened native; never repeat authoring."""
import hashlib,json
from pathlib import Path
import bpy,numpy as np
from mathutils import Vector
from mathutils.bvhtree import BVHTree
root=Path(__file__).resolve().parents[6];owned=Path(__file__).resolve().parent;ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';out=ev/'hand-grip106';scopepath=ev/'hand-grip104/scope.json';scope=json.loads(scopepath.read_text());n=np.load(ev/'hand-grip104/source-fields.npz');f=np.load(out/'candidate-fields.npz');names=n['boneNames'].tolist();allowed=[names.index(s) for s in scope['scope']['weightBoneNames']];outside=np.setdiff1d(np.arange(51),allowed);source=root/scope['immutableControl']['path'];native=owned/'hand-grip01/bounded-full-four.blend';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();native_sha=sha(native);field_sha=sha(out/'candidate-fields.npz');full=f['fullWeights'];four=f['fourWeights'];old=n['gloveWeights'];P=n['gloveXYZ'].astype(float);driverpath=ev/'hand-grip105/actual-driver.json';driver=json.loads(driverpath.read_text());finitepath=root/scope['physicalChecks']['actualSurfaceSource'];exportfield=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/grip74/export-hand-fields.npz';helper=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/neck62/read-native.py';queryrecipe=root/'docs/evidence/hero-remaster/user-agent3-qa-2026-10-03/grip74/measure-grip.py';author=owned/'author_bounded_hand_grip.py';text=helper.read_text();h=dict(bpy=bpy,np=np,hashlib=hashlib);exec(compile(text[text.index('def digest('):text.index('for label,path in paths.items():')],str(helper),'exec'),h)
qtext=queryrecipe.read_text();qh=dict(np=np);exec(compile(qtext[qtext.index('def point_query('):qtext.index('# Native rest ancestry:')],str(queryrecipe),'exec'),qh);query=qh['point_query'];a=author.read_text();exec(compile(a[a.index('C=np.array('):a.index('B,first,first_targets=pose(')],str(author),'exec'),globals());B,first,first_targets=pose(rows[0][1]);assert np.array_equal(first,f['firstCandidateBoneWorld']) and np.array_equal(B,f['firstBikeFrame'])
bpy.ops.wm.open_mainfile(filepath=str(native));control=json.loads((ev/'hand-grip104/immutable-control.json').read_text())
for name,state in control['objects'].items():assert h['state'](bpy.data.objects[name])==state,name
assert h['materials']()==control['materials'];rig=bpy.data.objects['Independent anatomical foundation rig'];newrig=bpy.data.objects['Bounded actual-grip01 original51 rig, unaccepted'];assert np.array_equal(np.array([np.array(b.matrix_local) for b in newrig.data.bones]),n['rigRest']);assert [names.index(b.parent.name) if b.parent else -1 for b in newrig.data.bones]==n['parents'].tolist()
for j in outside:assert h['state'](newrig)['armature']['pose'][names[j]]==control['objects'][rig.name]['armature']['pose'][names[j]]
basis={s:np.array(newrig.pose.bones[s].matrix_basis).tolist() for s in scope['scope']['existingPoseBoneNames']};objects=['Bounded actual-grip01 glove '+s+', unaccepted' for s in ['full','four']];orig=bpy.data.objects[scope['objects']['glove']['object']];oldmesh=h['state'](orig)['mesh']
for label,oname,expected in zip(['full','four'],objects,[full,four]):
 o=bpy.data.objects[oname];measured=np.zeros_like(expected)
 for v in o.data.vertices:
  for g in v.groups:
   name=o.vertex_groups[g.group].name
   if name in names:measured[v.index,names.index(name)]=g.weight
 assert np.array_equal(measured,expected);mesh=h['state'](o)['mesh'];mesh.pop('weights');base=dict(oldmesh);base.pop('weights');assert mesh==base
 for s in ['L','R']:assert all(o.vertex_groups[k].lock_weight==orig.vertex_groups[k].lock_weight for k in names)
for im in bpy.data.images:
 if im.name in control['images']:
  c=control['images'][im.name];assert im.colorspace_settings.name==c['colour'] and list(im.size)==c['size'];assert (hashlib.sha256(bytes(im.packed_file.data)).hexdigest() if im.packed_file else None)==c['packed']
inputs=[source,scopepath,ev/'hand-grip104/source-fields.npz',finitepath,driverpath,exportfield,helper,queryrecipe]+[root/c['file'] for c in driver['cases']];pins={str(p.relative_to(root)):sha(p) for p in inputs}
assert np.array_equal(full[:,outside],old[:,outside]) and np.array_equal(four[:,outside],old[:,outside]);assert sha(source)==scope['immutableControl']['sha256']
# The fallback condition can be read from archived anatomical triangle/barycentric rows.
w=n['bodyWeights'][n['bodyTriangles'][f['bodyTriangleAncestry']]][:,:,allowed];mass=np.einsum('ij,ijk->ik',f['bodyBarycentrics'],w).sum(1);fallback=np.flatnonzero(mass<=0).tolist()
report={'status':'UNACCEPTED_ONE_HAND_CANDIDATE_FROZEN_SURFACE_QUALIFICATION_PENDING','executedAuthoringRecipeSHA256':sha(author),'receiptRecoveryRecipeSHA256':sha(__file__),'pins':pins,'scopeSHA256':sha(scopepath),'native':str(native.relative_to(root)),'nativeSHA256':native_sha,'fieldsSHA256':field_sha,'newObjects':objects,'newRig':newrig.name,'all34OriginalObjectsExactAfterSaveReopen':True,'all51RestBindExact':True,'outside19SavedBonePosesExact':True,'topologyUVPBRRawAttributesAndDecodedRestNormalsExact':True,'allPackedImagesMaterialGraphsExact':True,'sourcePositionsAllExact':True,'outside19WeightColumnsExact':True,'fullInfluenceMaximum':int((full>0).sum(1).max()),'fourInfluenceMaximum':int((four>0).sum(1).max()),'removedWeightMassPercentiles':np.percentile(f['removedMass'],[0,50,95,100]).tolist(),'bodyAncestryDistancePercentilesM':np.percentile(f['bodyDistanceM'],[0,50,95,100]).tolist(),'fallbackRetainedSourceWeightNativeIDs':fallback,'distalPositiveRows':{s:{label:int((a[:,j]>0).sum()) for label,a in [('source',old),('full',full),('four',four)]} for j,s in enumerate(names) if '_03.' in s},'palms':palms,'firstFiniteTargets':first_targets,'fixedFingerFlexAnglesDeg':angles,'thumbFirstOppositionDeg':35,'savedHandPoseBasisFirstObservedFrame':basis,'actualSource37VsNative26RestMaximumElementDifference':rigResidual,'driverMapping':'Directly observed source37 world bone times OWN inverse bind times exact native26 rest. Source export removes dots from semantic joint names: bijective51-name correspondence asserted, no nearest-bone guessing. Only32 admitted hand/finger candidate bones replaced; outside19 driver bone worlds unchanged. Actual bike.frame is independent. Native candidate replay, not actual engine consumption of a candidate export.','recovery':'Initial symbolic name mismatch stopped before save and is retained. Repaired author saved/reopened the ONE native and all fields, then receipt serialization accessed a stale Blender object after reopen. Recovery checks that exact file read-only; no candidate rewrite or second authoring.', 'limits':['ONE barycentric anatomical glove binding field, unchanged geometry and ONE fixed flex candidate; angles/opposition are unqualified design choices, no sweep.','Finite source glove ray point is a palm proposal. Exact target position is not deformed skin seating; full surface/penetration/enclosure/wrist/full-four checks required before capture.','No body/neck/hoodie/handlebar/global transform/newbone/rest-bind/normal edits or promotion; allM0-M5 open/root sole judge.']};(out/'authoring.json').write_text(json.dumps(report,indent=2)+'\n');assert sha(native)==native_sha and sha(out/'candidate-fields.npz')==field_sha;print(json.dumps({k:report[k] for k in ['status','nativeSHA256','fullInfluenceMaximum','fourInfluenceMaximum','removedWeightMassPercentiles','bodyAncestryDistancePercentilesM','distalPositiveRows']},indent=2))
