"""Freeze read-only NEW anatomy/rig proposal, never author a candidate."""
from pathlib import Path
import json,hashlib
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2')
A=R/'assets/blender/hero-remaster/rider/one-rider-v2/tpose-rig-adapter212';E=R/'docs/evidence/hero-remaster/one-rider-v2/tpose-rig-adapter212'
inputs=[B/'finite-cleanup210/ancestry.npz',B/'finite-cleanup210/clean-native.glb',B/'source-preserving-garment185/operator/rider.glb',R/'docs/evidence/hero-remaster/one-rider-v2/finite-cleanup210/freeze.json',R/'docs/evidence/hero-remaster/one-rider-v2/head-join211/join-contract.json',R/'docs/evidence/hero-remaster/one-rider-v2/head-join211/freeze.json',R/'src/render/hero/gltfRider.ts',R/'src/core/riderGeometry.ts',R/'src/render/hero/sleeveSkin.ts',R/'src/render/bike/bikeModel.ts',R/'harness/hero-remaster/new-rider-private-adapter.mts',R/'harness/hero-remaster/new-rider-fresh-c19-adapter.mts',R/'harness/hero-remaster/new-rider-contact-adapter.mts',R/'harness/hero-remaster/basic-pose-gate/protocol.ts',R/'harness/hero-remaster/basic-pose-gate/generate.py',R/'assets/design/hero-remaster/one-rider-v2/tpose-construction-target204/reference.png',R/'assets/design/hero-remaster/one-rider-v2/tpose-construction-target204/SPEC.md']
def pin(p):return {'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
owned=sorted(p for d in (A,E) for p in d.iterdir() if p.is_file() and p.name!='freeze.json')
out={'status':'FROZEN_READ_ONLY_PROPOSED_ARM_FIELD_AND19BONE_ADAPTATION','geometryAttempts':0,'gpuUsed':False,'cpuThreads':2,'inputPins':{str(p):pin(p) for p in inputs},'ownedFiles':{str(p):pin(p) for p in owned},'limitations':['No edited geometry, weights, rig, fixture, runtime patch, textures, player asset or acceptance.','All target skeleton centres and contact orientations remain declared authoring hypotheses, with actual source-surface provenance distinct.','Reach sampled201 physical-profile inputs, not recorded live gameplay/landings.','Parent must admit one explicit construction before geometry mutation.']}
(E/'freeze.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'freezeSHA256':pin(E/'freeze.json')['sha256'],'inputs':len(inputs),'ownedFiles':len(owned),'geometryAttempts':0},indent=2))
