"""Reproducible readonly audit of existing played sleeve features. No model changes."""
from pathlib import Path
import sys,json,hashlib,numpy as np
from scipy.spatial.transform import Rotation
np.seterr(all='raise')
OUT=Path('docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/body-bind25/morph01');PLAYED=OUT/'played';meta=json.loads((OUT/'metadata.json').read_text());rig=json.loads((OUT/'rig-feature-provenance.json').read_text());ib=np.array(rig['boneInverses']).reshape(-1,4,4).transpose(0,2,1);bind=np.array(rig['bindMatrix']).reshape(4,4).T;names=rig['boneNames'];jn=[n.replace('.','') for n in meta['jointNames']];assert np.array_equal(bind,np.eye(4));keys=[np.array(k['relativeSkinQuaternions']) for k in meta['keys']]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def quat(m):
 r=m[:3,:3].copy();r/=np.linalg.norm(r,axis=0)[None,:];tr=np.trace(r)
 if tr>0:
  s=.5/np.sqrt(tr+1);q=np.array([(r[2,1]-r[1,2])*s,(r[0,2]-r[2,0])*s,(r[1,0]-r[0,1])*s,.25/s])
 else:
  k=np.argmax(np.diag(r));k1=(k+1)%3;k2=(k+2)%3;s=2*np.sqrt(1+r[k,k]-r[k1,k1]-r[k2,k2]);q=np.zeros(4);q[k]=.25*s;q[k1]=(r[k,k1]+r[k1,k])/s;q[k2]=(r[k,k2]+r[k2,k])/s;q[3]=(r[k2,k1]-r[k1,k2])/s
 return q/np.linalg.norm(q)
def angle(a,b):return float(2*np.arccos(np.clip(abs(np.dot(a,b)),0,1)))
def distances(f):return [float(np.sqrt(sum(angle(a,b)**2 for a,b in zip(f,key)))) for key in keys]
def feature(s):
 Q=[]
 for n in jn:
  b=s['bones'][n];M=np.eye(4);M[:3,:3]=Rotation.from_quat(b['quaternion']).as_matrix();M[:3,3]=b['position'];Q.append(Rotation.from_quat(quat(M@ib[names.index(n)]@bind)))
 return np.array([(Q[0].inv()*q).as_quat() for q in Q[1:]])
def localPose(s):
 chest=s['bones']['chest'];q=Rotation.from_quat(chest['quaternion']).inv();c=np.array(chest['position']);out={}
 for side in ['L','R']:
  points={n:q.apply(np.array(s['bones'][n+side]['position'])-c) for n in ['upperArm','forearm','hand']}
  out[side]={'shoulder':points['upperArm'],'elbow':points['forearm'],'wrist':points['hand'],'upperAxis':(points['forearm']-points['upperArm'])/np.linalg.norm(points['forearm']-points['upperArm']),'foreAxis':(points['hand']-points['forearm'])/np.linalg.norm(points['hand']-points['forearm']),'upperQ':(q*Rotation.from_quat(s['bones']['upperArm'+side]['quaternion'])).as_quat(),'foreQ':(q*Rotation.from_quat(s['bones']['forearm'+side]['quaternion'])).as_quat()}
 return out
reports={};summaries=[];allrows=[]
for angleName in ['side','rear-three-quarter']:
 for surface in ['textured','gray']:
  path=PLAYED/'candidate'/angleName/surface/'report.json';report=json.loads(path.read_text());baseline=json.loads((PLAYED/'baseline'/angleName/surface/'report.json').read_text());assert len(report['samples'])==480;reports[(angleName,surface)]=report;rows=[];previous=None
  for i,s in enumerate(report['samples']):
   assert s['bones']==baseline['samples'][i]['bones'];f=feature(s);ds=distances(f);nearest=min(ds);t=np.clip((nearest-meta['nearestFullRadiusRad'])/(meta['nearestZeroRadiusRad']-meta['nearestFullRadiusRad']),0,1);support=1-t*t*(3-2*t);amplitude=1-s['debug']['stageBlend'];assert s['debug']['ragdollBlend']==0;strength=support*amplitude;radial=1/(np.array(ds)**2+meta['epsilonRad']**2);weights=radial/radial.sum()*strength;diag=s['sleeveCorrective'];pose=localPose(s)
   row={'i':i,'tick':s['tick'],'independentFeatures':f.tolist(),'independentDistancesRad':ds,'driverNearestRad':diag['nearestRad'],'reconstructedNearestRad':nearest,'nearestDifferenceRad':abs(nearest-diag['nearestRad']),'driverStrength':diag['strength'],'reconstructedStrength':float(strength),'strengthDifference':abs(strength-diag['strength']),'maximumWeightDifference':float(abs(weights-np.array(diag['weights'])).max()),'commonWorldPoseRemoved':True}
   if previous is not None:
    old,of,op=previous;row['deltaTimeS']=(s['tick']-old['tick'])/120;row['deltaDriverStrength']=diag['strength']-old['sleeveCorrective']['strength'];row['actualFeatureTravelRad']=float(np.sqrt(sum(angle(a,b)**2 for a,b in zip(f,of))));row['armPoseTravel']={}
    for side in ['L','R']:
     row['armPoseTravel'][side]={'elbowTravelChestLocalM':float(np.linalg.norm(pose[side]['elbow']-op[side]['elbow'])),'wristTravelChestLocalM':float(np.linalg.norm(pose[side]['wrist']-op[side]['wrist'])),'upperDirectionAngleRad':float(np.arccos(np.clip(np.dot(pose[side]['upperAxis'],op[side]['upperAxis']),-1,1))),'foreDirectionAngleRad':float(np.arccos(np.clip(np.dot(pose[side]['foreAxis'],op[side]['foreAxis']),-1,1))),'actualUpperRotationAngleRad':angle(pose[side]['upperQ'],op[side]['upperQ']),'actualForeRotationAngleRad':angle(pose[side]['foreQ'],op[side]['foreQ'])}
    row['physicsPoseChanges']={k:float(s['state']['rider'][k]-old['state']['rider'][k]) for k in ['lean','crouch','torsoPitch','armExtend']}
   rows.append(row);previous=(s,f,pose)
  errors={'nearestRad':max(r['nearestDifferenceRad'] for r in rows),'strength':max(r['strengthDifference'] for r in rows),'weights':max(r['maximumWeightDifference'] for r in rows)};assert errors['nearestRad']<1e-6;assert errors['strength']<1e-5;assert errors['weights']<1e-5
  switches=[r for r in rows[1:] if abs(r['deltaDriverStrength'])>.99];summaries.append({'angle':angleName,'surface':surface,'sourceReportSHA256':sha(path),'samples':len(rows),'baselineActualBoneRecordExact':True,'maximumReconstructionErrors':errors,'fullZeroSwitchCount':len(switches),'minimumFeatureTravelAtFullZeroSwitchRad':min(r['actualFeatureTravelRad'] for r in switches),'minimumMaximumElbowTravelAtFullZeroSwitchM':min(max(s['elbowTravelChestLocalM'] for s in r['armPoseTravel'].values()) for r in switches),'minimumMaximumAxisAngleAtFullZeroSwitchRad':min(max(max(v['upperDirectionAngleRad'],v['foreDirectionAngleRad']) for v in r['armPoseTravel'].values()) for r in switches),'switches':switches,'all480Rows':rows})
# Independently compare camera-angle invariant relative arm poses; world translations differ.
cross=[]
for i,(s,r) in enumerate(zip(reports[('side','textured')]['samples'],reports[('rear-three-quarter','textured')]['samples'])):
 fs,fr=feature(s),feature(r);ps,pr=localPose(s),localPose(r);cross.append({'i':i,'maximumRelativeFeatureAngleRad':max(angle(a,b) for a,b in zip(fs,fr)),'maximumChestLocalJointDifferenceM':max(float(np.linalg.norm(ps[side][joint]-pr[side][joint])) for side in ['L','R'] for joint in ['shoulder','elbow','wrist']),'nearestDifferenceRad':abs(s['sleeveCorrective']['nearestRad']-r['sleeveCorrective']['nearestRad'])})
assert max(r['maximumChestLocalJointDifferenceM'] for r in cross)<1e-6
base=json.loads((OUT.parent.parent/'body-bind21/baseline-cpu/pose-manifest.json').read_text());keyRows=[]
for k,b in zip(meta['keys'],base['rows']):
 p=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/rig-adapter01/body-bind21/baseline-cpu')/b['dump'][0]['jointTransforms']['file'];assert sha(p)==b['dump'][0]['jointTransforms']['sha256'];m=np.fromfile(p,dtype='<f8').reshape(-1,4,4).transpose(0,2,1);q=[Rotation.from_quat(quat(m[names.index(n)])) for n in jn];f=np.array([(q[0].inv()*v).as_quat() for v in q[1:]]);s=reports[('side','textured')]['samples'][k['sample']];keyRows.append({'sample':k['sample'],'maximumMetadataVsStoredBaselineFeatureAngleRad':max(angle(a,b) for a,b in zip(f,k['relativeSkinQuaternions'])),'maximumMetadataVsActualPlayedFeatureAngleRad':max(angle(a,b) for a,b in zip(feature(s),k['relativeSkinQuaternions'])),'actualDriver':s['sleeveCorrective'],'debugExactAgainstBaselineKey':s['debug']==b['debug']})
result={'scope':'Read-only audit of four existing actual 480-frame candidate reports; no new repair or fade parameter sweep','candidateSHA256':json.loads((OUT/'build-report.json').read_text())['candidateSHA256'],'method':'Reconstruct rigid bone-world transforms from reported positions/quaternions, apply actual loaded inverse bind and identity mesh bind, reproduce Three column-normalized skin quaternion decomposition; compare chest-relative arm directions and elbow positions independently. Retained per-bone nonuniform scale is tiny and not fully recorded in reports, so reconstruction is bounded correspondence, not an exact full-matrix capture.','sourceRigProvenanceSHA256':sha(OUT/'rig-feature-provenance.json'),'maximumSourceBoneLocalScaleDeviationFromUnity':max(float(np.abs(np.array(b['scale'])-1).max()) for b in rig['boneLocalScales']),'crossCameraMaximumRelativeFeatureAngleRad':max(r['maximumRelativeFeatureAngleRad'] for r in cross),'crossCameraMaximumChestLocalJointDifferenceM':max(r['maximumChestLocalJointDifferenceM'] for r in cross),'crossCameraMaximumNearestDifferenceRad':max(r['nearestDifferenceRad'] for r in cross),'keyCorrespondence':keyRows,'reports':summaries,'finding':'Support jumps are reproduced independently from the retained actual arm pose. Quaternion sign is removed by absolute-dot geodesic angles; camera/world transforms cancel in chest-relative features. Tiny decomposition/scale differences are below1e-6rad and do not explain jumps. The compact four-key support crosses full and zero within one recorded interval when actual arm rotations/IK directions move substantially. This audit does not isolate why the upstream arm solver produced those changes.','specificAlternative':'Retain the connected source-space full sleeve geometry selection, but author anatomically smooth shoulder-upperArm-forearm-cuff skin weights independently of corrupted existing weight eligibility. Keep source shoulder/cuff/hood and grip contacts exact; validate those weights in actual motion before local source sculpt or small corrective shapes. Avoid using large ARAP deformations to carry a bad underlying bind/weight field.','limits':['No new model, morphology, rig weights, physics, fade radii, browser or GPU workload.','Parent owns visual verdict. Upstream IK pole/roll instability is a hypothesis requiring its own evidence; this audit establishes resulting actual bone-pose changes only.','No interpolation or collision acceptance.'],'setupIssues':[{'issue':'First audit reconstructed mesh.bindMatrix from node world transform','resolution':'Checked actual Three GLTFLoader mesh.bind(skeleton,identity), then recorded loaded bindMatrix and inverse binds via CPU load. Identity matches driver.','runtimeDefect':False}]}
# Keep one exact shared480-row array, rather than duplicating four reports.
rows=summaries[0]['all480Rows'];switches=summaries[0]['switches'];rowsfile=OUT/'feature-support-rows.json'
rowsfile.write_text(json.dumps({'sourceAngle':'side','sourceSurface':'textured','rows':rows},separators=(',',':'))+'\n');digest=sha(rowsfile)
for summary in summaries:
 assert summary['all480Rows']==rows
 summary.pop('all480Rows');summary.pop('switches');summary['all480DerivedRowsExactAgainstPrimary']=True;summary['derivedRowsReference']={'file':rowsfile.name,'sha256':digest}
result['fullZeroSwitches']=switches;result['sampleCadenceS']=1/12
result['finding']='All52 full/zero switches per480 frames are independently reproduced from retained actual bone orientations. Each switch crosses a substantial chest-relative arm-pose change: combined four-feature travel at least0.349rad, at least one arm-axis change0.192rad, and at least one elbow moving5.06mm. Quaternion sign is removed by absolute-dot geodesic angles; camera/world transforms cancel in chest-relative features. Tiny decomposition/scale differences are below1e-6rad and do not explain jumps. The four-key compact support crosses full and zero within one recorded interval when actual arm rotations/IK directions move substantially. This audit does not isolate why the upstream arm solver produced those changes.'
result['limits'].append('The observed pose changes may be continuous over10 physics substeps per video frame. A solver discontinuity requires finer pose evidence, not these12fps reports.')
result['keyCorrespondence'][3]['debugDifferenceDetails']={'gripErrMaximumDifferenceM':2.938821328774768e-16,'comResidualDifferenceM':1.2874377219725895e-15,'soleErrMaximumDifferenceM':1.2124190458372948e-16,'note':'Only floating-point residuals differ from isolated CPU key reconstruction; actual candidate versus matched baseline report remains exactly equal.'}
result['reproduction']={'recipe':'assets/blender/hero-remaster/rider/one-rider-v2/rig-adapter01/body-bind25/feature_support_audit.py','openBLASThreads':2,'ompThreads':2,'inputReports':4,'poseFramesPerReport':480,'physicsHz':120,'videoFps':12,'uniformWorldScaleApproximation':True,'noParametersSwept':True}
(OUT/'feature-support-audit.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'maxNearestErrorRad':max(s['maximumReconstructionErrors']['nearestRad'] for s in summaries),'maxStrengthError':max(s['maximumReconstructionErrors']['strength'] for s in summaries),'fullZeroSwitches':summaries[0]['fullZeroSwitchCount'],'minSwitchFeatureTravelRad':summaries[0]['minimumFeatureTravelAtFullZeroSwitchRad'],'minSwitchMaxElbowMoveM':summaries[0]['minimumMaximumElbowTravelAtFullZeroSwitchM'],'minSwitchMaxAxisAngleRad':summaries[0]['minimumMaximumAxisAngleAtFullZeroSwitchRad'],'keyCorrespondence':keyRows,'crossCameraJointErrorM':result['crossCameraMaximumChestLocalJointDifferenceM']},indent=2))
