"""One local alternate-diagonal repair, two quads only, CPU all480motion audit.
All155fields remain byteexact; only explicit native triangle indices change.
"""
from pathlib import Path
import json,hashlib,argparse
import numpy as np
REPO=Path('/Users/raynos/projects/games/rockhop');ROOT=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/garment-rebuild01');OUT=REPO/'docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/wrist-local156';RUN=ROOT/'wrist-local156';parser=argparse.ArgumentParser();parser.add_argument('--output-dir',type=Path);parser.add_argument('--evidence-dir',type=Path);args=parser.parse_args();assert (args.output_dir is None)==(args.evidence_dir is None)
if args.output_dir is not None:RUN=args.output_dir;OUT=args.evidence_dir
RUN.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);sha=lambda b:hashlib.sha256(b).hexdigest();source=ROOT/'cuff-ankle-transition155/transition155.npz';raw=source.read_bytes();sourceReportPath=REPO/'docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/cuff-ankle-transition155/construction-report.json';sourceReport=json.loads(sourceReportPath.read_bytes());assert sha(raw)==sourceReport['artifactSHA256'];data=np.load(source);f={k:data[k] for k in data.files};P=f['native_positions'];W=f['native_weights19'];N=f['native_normals'];Q=f['native_retained_quads'];quadIDs=f['native_retained_quad_ids'];before=np.concatenate([Q[:,[0,1,2]],Q[:,[0,2,3]]]);after=before.copy();changes=[]
# Literal failed quads only. Change a-c diagonal to b-d while preserving winding.
for qi in [1248,1820]:
 ids=np.flatnonzero(quadIDs==qi);assert len(ids)==1;j=int(ids[0]);q=Q[j];indices=[j,j+len(Q)];after[indices]=q[[[0,1,3],[1,2,3]]];changes.append({'sourceNativeQuadID':qi,'retainedQuadID':j,'quadVertices':q.tolist(),'explicitNativeTriangleIDs':indices,'oldTriangles':before[indices].tolist(),'newTriangles':after[indices].tolist(),'oldDiagonal':q[[0,2]].tolist(),'newDiagonal':q[[1,3]].tolist(),'quadBoundaryVerticesUnchanged':True})
changed=np.flatnonzero(np.any(before!=after,axis=1));assert len(changed)==4;unaffected=np.ones(len(before),bool);unaffected[changed]=False;assert np.array_equal(before[unaffected],after[unaffected]);arrays=dict(f);arrays.update(native_triangles_before156=before,native_triangles=after,native_modified_triangle_ids156=changed,native_diagonal_repaired_source_quad_ids156=np.array([1248,1820]));artifact=RUN/'wrist-local156.npz';assert not artifact.exists(),'Preserve frozen single repair';np.savez_compressed(artifact,**arrays)
for k in f:assert np.array_equal(arrays[k],f[k],equal_nan=True) if f[k].dtype.kind in 'fc' else np.array_equal(arrays[k],f[k])
for k,v in sourceReport['sourceArrays'].items():assert sha(arrays[k].tobytes())==v['sha256']
motionPath=REPO/'docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/full-motion155/report.json';motion=json.loads(motionPath.read_bytes());body=motion['outputs'][0];glove=motion['outputs'][1];mr=(ROOT/'full-motion155'/body['file']).read_bytes();gr=(ROOT/'full-motion155'/glove['file']).read_bytes();assert sha(mr)==body['sha256'] and sha(gr)==glove['sha256'] and mr==gr;assert body['bones']==glove['bones'] and body['sourceBindMatrix']==glove['sourceBindMatrix']==np.eye(4).T.reshape(-1).tolist();M=np.frombuffer(mr,dtype='<f8').reshape(480,19,4,4).transpose(0,1,3,2)
def unit(a):return a/np.maximum(np.linalg.norm(a,axis=-1,keepdims=True),1e-20)
def measures(T,posed,skinnedN):
 r=P[T];p=posed[T];rc=np.cross(r[:,1]-r[:,0],r[:,2]-r[:,0]);pc=np.cross(p[:,1]-p[:,0],p[:,2]-p[:,0]);restedges=np.linalg.norm(r-np.roll(r,-1,axis=1),axis=2);posededges=np.linalg.norm(p-np.roll(p,-1,axis=1),axis=2);stretch=posededges/np.maximum(restedges,1e-20);ratio=np.linalg.norm(pc,axis=1)/np.maximum(np.linalg.norm(rc,axis=1),1e-20);rd=np.einsum('ti,ti->t',unit(rc),unit(N[T].mean(1)));pd=np.einsum('ti,ti->t',unit(pc),unit(skinnedN[T].mean(1)));flag=(rd>.2)&(pd<-.2)
 return {'areaRatio':ratio,'stretch':stretch,'opposition':flag,'triangleCross':pc}
def summary(a,mask):
 return {'triangles':int(mask.sum()),'maximumEdgeStretch':float(a['stretch'][mask].max()),'edgeStretchP99':float(np.quantile(a['stretch'][mask],.99)),'minimumAreaRatio':float(a['areaRatio'][mask].min()),'areaCollapsedBelow25Percent':int((a['areaRatio'][mask]<.25).sum()),'normalOppositionFlags':int(a['opposition'][mask].sum())}
scopes={'literal repaired4triangles':~unaffected,'whole retained clean garment':np.ones(len(before),bool)}
for side in ['L','R']:scopes['native upstream sleeve.'+side]=(f['native_cuff_'+side+'_blend_alpha'][before]>0).any(1)
rows=[];pose39=None
for frame,matrix in enumerate(M):
 posed=np.einsum('vj,jab,vb->va',W,matrix[:,:3,:],np.c_[P,np.ones(len(P))]);skinned=unit(np.einsum('vj,jab,vb->va',W,matrix[:,:3,:3],N));old=measures(before,posed,skinned);new=measures(after,posed,skinned)
 for k in ['areaRatio','stretch','opposition','triangleCross']:assert np.array_equal(old[k][unaffected],new[k][unaffected])
 quadRows=[]
 for c in changes:
  ids=c['explicitNativeTriangleIDs'];q=c['quadVertices'];oldArea=np.linalg.norm(old['triangleCross'][ids],axis=1)/2;newArea=np.linalg.norm(new['triangleCross'][ids],axis=1)/2;oldDot=float(np.dot(*unit(old['triangleCross'][ids])));newDot=float(np.dot(*unit(new['triangleCross'][ids])));boundary=P[q];posedBoundary=posed[q];boundaryStretch=np.linalg.norm(posedBoundary-np.roll(posedBoundary,-1,axis=0),axis=1)/np.linalg.norm(boundary-np.roll(boundary,-1,axis=0),axis=1)
  quadRows.append({'sourceNativeQuadID':c['sourceNativeQuadID'],'beforeAreaRatios':old['areaRatio'][ids].tolist(),'afterAreaRatios':new['areaRatio'][ids].tolist(),'beforeTriangleNormalDot':oldDot,'afterTriangleNormalDot':newDot,'oldTotalQuadTriangleAreaM2':float(oldArea.sum()),'newTotalQuadTriangleAreaM2':float(newArea.sum()),'boundaryEdgeStretchUnchanged':boundaryStretch.tolist()})
 rows.append({'frame':frame,'tick':motion['framesChecked'][frame]['tick'],'scopes':{scope:{'before':summary(old,mask),'after':summary(new,mask)} for scope,mask in scopes.items()},'quadGeometry':quadRows})
 if frame==39:pose39={'nativeVertexIDs':sorted(set(v for c in changes for v in c['quadVertices'])),'positions':posed[sorted(set(v for c in changes for v in c['quadVertices']))].tolist(),'quads':quadRows}
aggregate={}
for scope in scopes:
 aggregate[scope]={}
 for version in ['before','after']:
  a=[row['scopes'][scope][version] for row in rows];aggregate[scope][version]={'maximumEdgeStretch':max(x['maximumEdgeStretch'] for x in a),'minimumAreaRatio':min(x['minimumAreaRatio'] for x in a),'sumAreaCollapseFlagsAcrossFrames':sum(x['areaCollapsedBelow25Percent'] for x in a),'framesWithAreaCollapse':sum(x['areaCollapsedBelow25Percent']>0 for x in a),'maximumAreaCollapsesPerFrame':max(x['areaCollapsedBelow25Percent'] for x in a),'sumNormalOppositionFlagsAcrossFrames':sum(x['normalOppositionFlags'] for x in a),'framesWithNormalOpposition':sum(x['normalOppositionFlags']>0 for x in a)}
report={'status':'One alternate-diagonal local repair; CPU feasibility only; parent judges full moving appearance','source155ArtifactSHA256':sha(raw),'candidateArtifact':str(artifact),'candidateSHA256':sha(artifact.read_bytes()),'source34GLBSHA256':sourceReport['sourceGLBSHA256'],'fullMotion155ManifestSHA256':sha(motionPath.read_bytes()),'fullBodyAndGloveMatricesByteIdentical':True,'identityBindAndBoneOrderVerified':True,'allOriginal155NPZFieldsByteExact':True,'allProtectedSourceFiveRawAttributesExact':True,'settings':{'singleAttempt':1,'method':'Flip the two existing diagonals of literal quads1248/1820 froma-c tob-d, preserve boundary winding/vertices/weights/normals/UV. No geometry or weight sweep.','collapseThresholdUnchanged':.25,'normalFlagThresholdUnchanged':-.2,'unaffectedTrianglesAndAll480MetricsByteExact':True,'requiredExporter':'Use native_triangles explicit index array. native_retained_quads retain historical sourceface provenance; exporting them without diagonal override would discard this repair.'},'changes':changes,'aggregate':aggregate,'frame39':pose39,'rows':rows,'limits':['No GPU, surface selfintersection, texture/normal join or rendered quality acceptance.','The two rest diagonals differ physically; boundary restedges remain unchanged and all vertex fields exact.','Whole garment severe flags/stretch outside these quads remain; local repair is not a completed rig or character.']};assert source.read_bytes()==raw;(OUT/'repair-audit.json').write_text(json.dumps(report,separators=(',',':'))+'\n');print(json.dumps({'aggregate':aggregate,'frame39':pose39},indent=2))
