"""Necessary bound restricted to edges covered by the >=2mm strain bar."""
from pathlib import Path
import runpy,json,time,numpy as np,subprocess,re,os,signal
start=time.monotonic();x=runpy.run_path(str(Path(__file__).with_name('preflight.py')));globals().update({k:v for k,v in x.items()if not k.startswith('__')});keep=ll>=.002;constrained=coo_matrix((np.r_[ll[keep],ll[keep]],(np.r_[le[keep,0],le[keep,1]],np.r_[le[keep,1],le[keep,0]])),shape=(len(ids),len(ids))).tocsr();short,prev=dijkstra(constrained,indices=fi,directed=False,return_predecessors=True);s=short[:,fi];pair=np.argwhere(np.triu(np.isfinite(s)&(s>0),1));worst={'minimumNecessaryStrainBound':0};tested=0
for fr in f['frames']:
 assert time.monotonic()-start<720
 D=np.array(fr['deformationWorldColumnMajor']).reshape(19,4,4).transpose(0,2,1);M=D@rest@ib;Q=np.einsum('vj,jab,vb->va',fixedW,M[:,:3,:],fixedP,optimize=True)
 if len(pair):
  posed=np.linalg.norm(Q[pair[:,0]]-Q[pair[:,1]],axis=1);restpath=s[pair[:,0],pair[:,1]];ratio=posed/restpath;k=int(np.argmax(ratio));a,b=map(int,pair[k]);tested+=1
  if ratio[k]>worst['minimumNecessaryStrainBound']:
   chain=[int(fi[b])]
   while chain[-1]!=fi[a]:chain.append(int(prev[a,chain[-1]]));assert len(chain)<=len(ids) and chain[-1]>=0
   chain.reverse();phys=ids[chain];lens=np.linalg.norm(U[phys[1:]]-U[phys[:-1]],axis=1);assert (lens>=.002).all();assert abs(lens.sum()-restpath[k])<1e-12
   worst={'family':fr['family'],'frame':fr['frame'],'timeSeconds':fr['timeSeconds'],'minimumNecessaryStrainBound':float(ratio[k]),'fixedPhysicalEndpoints':[int(fixed[a]),int(fixed[b])],'fixedEndpointBodyAliases':[np.flatnonzero(inv[:off[1]]==fixed[a]).tolist(),np.flatnonzero(inv[:off[1]]==fixed[b]).tolist()],'posedEndpointDistanceM':float(posed[k]),'shortestConstrainedRestEdgePathM':float(restpath[k]),'allowed1_5PathLengthM':float(1.5*restpath[k]),'violationM':float(posed[k]-1.5*restpath[k]),'pathPhysicalIDs':phys.tolist(),'pathSourcePositionsM':U[phys].tolist(),'pathRestEdgeLengthsM':lens.tolist(),'minimumPathEdgeM':float(lens.min()),'pathBodyAttributeAliases':[np.flatnonzero(inv[:off[1]]==v).tolist()for v in phys]}
report={'status':'PREFLIGHT_REJECTED_NECESSARY_BOUND_GT1_5'if worst['minimumNecessaryStrainBound']>1.5 else'NECESSARY_ONLY_NOT_PROVEN_FEASIBLE','sourceSHA256':sha(source),'fixtureSHA256':sha(fpath),'constrainedEdgesMinimumRestLengthM':.002,'pathEdgesWithinFrozenPatch':True,'framesTested':tested,'fixedNodes':fixed.tolist(),'physicalNodeCount':len(ids),'worst':worst,'limits':['A necessary triangle-inequality bound valid for EVERY weight solution or extra-support field inside this exact patch while boundary and geometry stay fixed.','No solver/candidate/export.','This rejects the frozen40mm/256node1.5strain approach; no patch enlargement or relaxed threshold.','No global infeasibility claim about construction changes, changed boundaries or deformation representation.']};(O/'preflight-edges2mm.json').write_text(json.dumps(report,indent=2)+'\n');vm=subprocess.check_output(['vm_stat'],text=True);page=int(re.search(r'page size of (\d+)',vm).group(1));anon=int(re.search(r'Anonymous pages:\s*(\d+)',vm).group(1))*page;assert anon<70_000_000_000;elapsed=time.monotonic()-start;assert elapsed<720;(O/'preflight-process.json').write_text(json.dumps({'wallSeconds':elapsed,'anonymousBytesAtCompletion':anon,'CPUThreads':2,'timeoutSeconds':720,'anonymousLimitBytes':70_000_000_000,'GPUUsed':False,'solverUsed':False},indent=2)+'\n');print(json.dumps(report))
