"""READ-ONLY frozen patch inventory and necessary strain feasibility bound."""
from pathlib import Path
import importlib.util,json,hashlib,numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import dijkstra
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');O=R/'docs/evidence/hero-remaster/one-rider-v2/source-rig188/actual-three';recipe=R/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py';sp=importlib.util.spec_from_file_location('reader188',recipe);m=importlib.util.module_from_spec(sp);sp.loader.exec_module(m);source=B/'candidate-handoff170/hood-fixed185-187/rider.glb';g=m.GLB(source);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(source)=='4eb597a9ff926fb5ce30854272d8391347c2e220829486136b1509e02faa947c'
parts=[]
for p in g.j['meshes'][0]['primitives']:
 parts.append({k:g.array(v)for k,v in p['attributes'].items()}|{'T':g.array(p['indices']).reshape(-1,3)})
allP=np.concatenate([p['POSITION']for p in parts]).astype(float);U,inv=np.unique(allP,axis=0,return_inverse=True);off=np.r_[0,np.cumsum([len(p['POSITION'])for p in parts])];T=inv[np.concatenate([p['T']+off[i]for i,p in enumerate(parts)])];E=np.unique(np.sort(np.concatenate([T[:,[0,1]],T[:,[1,2]],T[:,[2,0]]]),axis=1),axis=0);length=np.linalg.norm(U[E[:,0]]-U[E[:,1]],axis=1);assert (length>0).all();graph=coo_matrix((np.r_[length,length],(np.r_[E[:,0],E[:,1]],np.r_[E[:,1],E[:,0]])),shape=(len(U),len(U))).tocsr();seeds=inv[np.array([2030,2172])];dist=dijkstra(graph,indices=seeds,directed=False,min_only=True);inside=dist<=.040;ids=np.flatnonzero(inside);cross=E[inside[E[:,0]]!=inside[E[:,1]]];outer=np.unique(cross[inside[cross]]);glove=np.unique(inv[off[1]:off[2]]);hood=np.unique(inv[off[2]:off[3]]);protected=np.union1d(np.intersect1d(ids,glove),np.intersect1d(ids,hood));fixed=np.union1d(outer,protected);free=np.setdiff1d(ids,fixed)
J=parts[0]['JOINTS_0'];rawW=parts[0]['WEIGHTS_0'];W=(rawW.astype(float)/abs(rawW.astype(float)).sum(1,keepdims=True)).astype('f4').astype(float);W19=np.zeros((len(W),19))
for lane in range(4):np.add.at(W19,(np.arange(len(W)),J[:,lane]),W[:,lane])
node_to_body={int(v):int(i)for i,v in enumerate(inv[:off[1]])};assert all(int(i)in node_to_body for i in ids);nodeW=np.array([W19[node_to_body[int(i)]]for i in ids]);inventory=[{'physicalID':int(i),'sourcePositionM':U[i].tolist(),'geodesicDistanceFromSeedM':float(dist[i]),'bodyAttributeAliases':np.flatnonzero(inv[:off[1]]==i).tolist(),'gloveAttributeAliases':(np.flatnonzero(inv[off[1]:off[2]]==i)).tolist(),'hoodAttributeAliases':(np.flatnonzero(inv[off[2]:off[3]]==i)).tolist(),'fixed':bool(i in fixed),'supportJointOrdinals':np.flatnonzero(nodeW[k]>0).tolist(),'normalizedWeights19':nodeW[k].tolist()}for k,i in enumerate(ids)]
# Only paths whose every node lies in the proposed patch. Fixed endpoints make the following bound independent of ALL possible interior weights.
edges=E[inside[E].all(1)];remap={int(v):k for k,v in enumerate(ids)};le=np.array([[remap[int(a)],remap[int(b)]]for a,b in edges]);ll=np.linalg.norm(U[edges[:,0]]-U[edges[:,1]],axis=1);sub=coo_matrix((np.r_[ll,ll],(np.r_[le[:,0],le[:,1]],np.r_[le[:,1],le[:,0]])),shape=(len(ids),len(ids))).tocsr();fi=np.array([remap[int(v)]for v in fixed]);shortest=dijkstra(sub,indices=fi,directed=False)[:,fi];valid=np.isfinite(shortest)&(shortest>0);pair=np.argwhere(np.triu(valid,1));fpath=B/'basic-pose-gate158/fixture-v4-asymmetric-halfsteps.json';f=json.loads(fpath.read_text());rest=np.array(m.worlds(g.j))[g.j['skins'][0]['joints']];ib=g.array(g.j['skins'][0]['inverseBindMatrices']).reshape(19,4,4).transpose(0,2,1);fixedW=nodeW[fi];fixedP=np.c_[U[fixed],np.ones(len(fixed))];worst={'minimumNecessaryStrainBound':0};rows=[]
for fr in f['frames']:
 D=np.array(fr['deformationWorldColumnMajor']).reshape(19,4,4).transpose(0,2,1);M=D@rest@ib;Q=np.einsum('vj,jab,vb->va',fixedW,M[:,:3,:],fixedP,optimize=True)
 if len(pair):
  posed=np.linalg.norm(Q[pair[:,0]]-Q[pair[:,1]],axis=1);restpath=shortest[pair[:,0],pair[:,1]];ratio=posed/restpath;k=int(np.argmax(ratio));a,b=map(int,pair[k]);row={'family':fr['family'],'frame':fr['frame'],'timeSeconds':fr['timeSeconds'],'minimumNecessaryStrainBound':float(ratio[k]),'fixedPhysicalEndpoints':[int(fixed[a]),int(fixed[b])],'fixedEndpointBodyAliases':[np.flatnonzero(inv[:off[1]]==fixed[a]).tolist(),np.flatnonzero(inv[:off[1]]==fixed[b]).tolist()],'posedEndpointDistanceM':float(posed[k]),'shortestPatchRestEdgePathM':float(restpath[k]),'allowed1_5PathLengthM':float(1.5*restpath[k]),'violationM':float(posed[k]-1.5*restpath[k])};rows.append(row)
  if row['minimumNecessaryStrainBound']>worst['minimumNecessaryStrainBound']:worst=row
cap=len(ids)<=256;necessary=worst['minimumNecessaryStrainBound']<=1.5;report={'status':'PREFLIGHT_REJECTED_NO_SOLVER_OR_CANDIDATE'if not(cap and necessary)else'NECESSARY_BOUND_ONLY_NOT_PROVEN_FEASIBLE','source':str(source),'sourceSHA256':sha(source),'fixtureSHA256':sha(fpath),'radiusM':.040,'physicalNodeCap':256,'nodesInsideRadius':len(ids),'freeNodes':len(free),'fixedOuterRingNodes':len(outer),'fixedProtectedAliasNodes':len(protected),'fixedTotalNodes':len(fixed),'patchNodeCapSatisfied':cap,'strainLimit':1.5,'fixedEndpointNecessaryBoundSatisfied':necessary,'worstFixedEndpointBound':worst,'testedFrames':len(rows),'existingJointSupportOnly':True,'protectedRules':['Geometry/indices/head/hood/gloves/alllowerbody unchanged.','Body exact-position aliases share one existing support field; no newjoint supports.','Outer ring and any glove/hood alias held exact.','No40mm patch growth, node cropping, threshold relaxation or solver.'],'constructionLimit':'A tiny elbow-region patch cannot repair the whole deep underarm web or move a sewn armhole. Root played187construction fails still take priority.','limits':['Fixed endpoint triangle inequality is a necessary condition, not sufficiency, collision proof or visible garment acceptance.','Every edge on shortest path is subject to proposed1.5limit, including edges<2mm: this is a stronger fullpatch proposal bound. A>=2mm-only bar cannot use shortedges as fixed constrained lengths; report this limitation, never mislabel as infeasibility of a looser specification.','CPU independent frozen fixture positions; actualThree witness verification separate report.']};(O/'patch-inventory.json').write_text(json.dumps(inventory,indent=2)+'\n');(O/'preflight-path-bounds.json').write_text(json.dumps(rows)+'\n');(O/'preflight.json').write_text(json.dumps(report,indent=2)+'\n');assert sha(source)==report['sourceSHA256'];print(json.dumps({k:v for k,v in report.items()if k not in ['limits','protectedRules']}))
