"""Same NEW nineteen-bone source, two independent grip morphs and explicit adapter."""
from pathlib import Path
import bpy,json,hashlib
import numpy as np
from mathutils import Vector,Matrix
ROOT=Path('/Users/raynos/projects/games/rockhop');BASE=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/rig-adapter01');OUT=ROOT/'docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/body-bind05';RUN=BASE/'body-bind05';RUN.mkdir(exist_ok=True);SOURCE=BASE/'body-bind04/rider.blend';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();before=sha(SOURCE);bpy.ops.wm.open_mainfile(filepath=str(SOURCE));scene=bpy.context.scene;scene.frame_set(1);rig=next(o for o in scene.objects if o.type=='ARMATURE');meshes=[o for o in scene.objects if o.type=='MESH'];body=next(o for o in meshes if 'protected' in o.name.lower());assert len(rig.data.bones)==19 and body.data.shape_keys is None
original=np.array([v.co for v in body.data.vertices]);basis=body.shape_key_add(name='Basis');rows=[];metadata={'version':1,'source':'body-bind04 actualNEWwhite19joint','declaredUniformScale':1.015,'runtimeAxisMapping':'proper(-Y,Z,-X), nativeL mapsruntimeR','hands':{},'legacyAnkleToSoleDisplacement':[-.010,-.079,0.0],'scope':'Privatecontactadapter; sourcebind preserved, physicsunchanged; playedapprovalpending'}
for native,sd,folder in [('L','R',BASE/'native-grip03'),('R','L',BASE/'native-grip03/R')]:
 file=folder/'native-held-shape.npz';d=np.load(file);ids=d['sourceCompleteVertexIds'];assert np.array_equal(original[ids],d['sourcePositions']);key=body.shape_key_add(name='gripClosed.'+sd);delta=d['morphDeltaDQS'];assert np.isfinite(delta).all()
 for i,p in zip(ids,d['wrappedPositionsDQS']):key.data[int(i)].co=Vector(p)
 key.value=0
 rawRotation=d['nativeToRuntimeProperRotation'];assert abs(np.linalg.det(rawRotation)-1)<1e-10;rotation=Matrix(rawRotation.tolist());assert abs(rotation.determinant()-1)<2e-6;target=rotation@rig.data.bones['hand.'+sd].matrix_local.to_3x3();q=target.to_quaternion();virtual=Vector(d['nativeVirtualPhysicsMarker']);socket=bpy.data.objects['gripSocket.'+sd];desired=rig.matrix_world@virtual;socket.matrix_world=Matrix.Translation(desired);bpy.context.view_layer.update();actual=socket.matrix_world.translation;assert (actual-desired).length<1e-6
 metadata['hands'][sd]={'targetWorldQuaternion':[q.x,q.y,q.z,q.w],'sourceNativeSide':native,'nativeVirtualPhysicsMarker':list(virtual),'sourceHandRestMatrix': [list(row) for row in rig.data.bones['hand.'+sd].matrix_local],'nativeToRuntimeRotation':d['nativeToRuntimeProperRotation'].tolist(),'sourceNativeWrist':list(rig.data.bones['hand.'+sd].head_local),'runtimeRodCentre':d['runtimeRodCentre'].tolist(),'gripMorphName':'gripClosed.'+sd,'sourceMorphSHA256':sha(file)}
 rows.append({'nativeSide':native,'runtimeSide':sd,'rawProperRotationDeterminant':float(np.linalg.det(rawRotation)),'blenderFloat32RotationDeterminant':rotation.determinant(),'vertices':len(ids),'nonzeroMorphVertices':int(np.count_nonzero(np.linalg.norm(delta,axis=1)>1e-8)),'maxMorphNativeM':float(np.linalg.norm(delta,axis=1).max()),'wristNativeDeltaM':float(np.linalg.norm(delta[d['wristLoopLocalIds']],axis=1).max()),'sourceBufferSHA256':sha(file),'virtualSocketSourceWorldPosition':list(actual)})
assert np.array_equal(np.array([v.co for v in body.data.vertices]),original);rig['rockhopRiderContactAdapter']=json.dumps(metadata,separators=(',',':'));body['rockhopGripMorphs']='Two independentlysolved nativehands; basepositions/weights/UVs retained'
scene.frame_set(1);bpy.context.view_layer.update();bpy.ops.wm.save_as_mainfile(filepath=str(RUN/'rider.blend'));bpy.ops.object.select_all(action='DESELECT');rig.select_set(True)
for o in meshes:o.select_set(True)
for o in scene.objects:
 if o.type=='EMPTY':o.select_set(True)
bpy.ops.export_scene.gltf(filepath=str(RUN/'rider.glb'),export_format='GLB',use_selection=True,export_animations=True,export_skins=True,export_force_sampling=True,export_extras=True,export_morph=True)
assert sha(SOURCE)==before;(OUT/'report.json').write_text(json.dumps({'sourceSHA256':before,'sourceUnchanged':True,'boneCount':19,'baseBodyPositionsByteExact':True,'rows':rows,'adapter':metadata,'GLBSHA256':sha(RUN/'rider.glb'),'limits':['Twoindependentgripmorphs/virtualsockets andtargetquaternions only; notruntimevalidation','Sameoriginalsittingclip retained, gripmorphbasevalues0','No physics/player/bike edits; source19bone weights/binds retained'],'CPUthreads':2,'GPUjob':False},indent=2)+'\n');print('NEW19_BOTH_GRIP_MORPHS_EXPORTED',flush=True)
