"""Add actual reviewed outcomes without replacing the existing fifteen comparisons."""
from pathlib import Path
import hashlib,json,shutil,subprocess
from PIL import Image
repo=Path('/Users/raynos/projects/games/rockhop');base=repo/'docs/evidence/hero-remaster/one-rider-v2/rig-adapter01';site=repo/'harness/out/hero-remaster/rider-review-site';media=site/'dist/media';recipe=repo/'assets/blender/hero-remaster/rider/one-rider-v2/rig-adapter01/body-bind11/sitting-multiangle01/review.html';out=base/'body-bind22/gallery-update129';out.mkdir(exist_ok=True);rows=[];cards=[]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
html=recipe.read_text();assert html.count('<video ')==15 and 'id="material-arm-comparison"' not in html
for number,label,score in [(22,'Cleaner eye skin · retained progress',6.8),(24,'Cornea treatment · rejected',6.6)]:
 folder=base/f'body-bind{number}/played01/textured';r=json.loads((folder/'report.json').read_text());assert not r.get('failure') and not r['errors'] and len(r['samples'])==72;expected='cc20ab813669b628c8e5d21596b655188d7188770adc374377cebf40769232ff';assert any(x['sha256']==expected for x in r['loaded'])
 stem=f'eye{number}-textured';video=media/f'{stem}.mp4';shutil.copy2(folder/'played.mp4',video);receipt=json.loads((folder/'frames-archive.json').read_text());Image.open(Path(receipt['privateMovieDecodedFrames'])/'0019.png').convert('RGB').save(media/f'{stem}.jpg',quality=94);shutil.copy2(base/f'body-bind{number}/played01/actual-before-after-textured.jpg',media/f'{stem}-comparison.jpg')
 cards.append(f'<article class="card"><div class="label"><h3>{label}</h3><p>Face {score}/10 · below the 7/10 minimum</p></div><video controls muted playsinline loop preload="metadata" poster="media/{stem}.jpg" src="media/{stem}.mp4"></video><div class="links"><a href="media/{stem}.mp4">Open video</a><a href="media/{stem}-comparison.jpg">Full-size before / after</a></div></article>');rows.append({'source':str(folder/'played.mp4'),'sourceModelSHA256':expected,'sourceMovieSHA256':sha(folder/'played.mp4'),'video':video.name,'videoSHA256':sha(video),'copiedExact':True})
section='<section id="material-arm-comparison"><h2>Latest face and sleeve tests</h2><p>The cleaner eye skin is progress. The cornea treatment made the iris cloudy, so it was rejected. Both keep the head and hoodie join. The earlier comparisons remain below.</p><section class="gameplay">'+''.join(cards)+'</section><h2>Sleeves in motion · correction rejected</h2><p>Compare the existing rider and the attempted correction under the same recorded ride, camera and lighting. The correction makes deep, flattened folds in the upper arm. It is kept here as evidence of why this approach was stopped. Gameplay behavior is unchanged.</p><section class="gameplay">'
cards=[]
for angle,title in [('side','Side'),('rear-three-quarter','Rear three-quarter')]:
 for label,caption in [('baseline','Existing rider'),('candidate','Sleeve correction · rejected')]:
  folder=base/'body-bind25/morph01/played'/label/angle/'textured';r=json.loads((folder/'report.json').read_text());expected='b7f4f22790124c664f9907104e5b17b77775b4c5c995f715d62be640bbcc8754' if label=='baseline' else '0fd9f63bdba68de60fa97ff43682842f8ffa30b6da5895221d837c70985d8c98';assert r['sourceSHA256']==expected and len(r['samples'])==480 and not r.get('failure') and not r['errors'];assert any(x['sha256']==expected for x in r['loaded'])
  stem=f'sleeve25-{label}-{angle}';video=media/f'{stem}-review.mp4';assert not video.exists();command=['ffmpeg','-v','error','-i',str(folder/'played.mp4'),'-c:v','libx264','-threads','2','-crf','24','-pix_fmt','yuv420p','-an','-movflags','+faststart',str(video)];subprocess.run(command,check=True)
  receipt=json.loads((folder/'frames-archive.json').read_text());Image.open(Path(receipt['privateDecodedFrames'])/'0427.png').convert('RGB').save(media/f'{stem}.jpg',quality=94);board=f'sleeve25-{angle}-comparison.jpg';shutil.copy2(base/'body-bind25/morph01/played/matched-boards'/f'{angle}-textured-key426.jpg',media/board)
  probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-select_streams','v:0','-show_entries','stream=codec_name,width,height,r_frame_rate,nb_frames:format=duration','-of','json',str(video)],text=True));assert probe['streams'][0]['width']==1280 and probe['streams'][0]['height']==720 and int(probe['streams'][0]['nb_frames'])==480 and float(probe['format']['duration'])==40
  cards.append(f'<article class="card"><div class="label"><h3>{title} · {caption}</h3></div><video controls muted playsinline loop preload="metadata" poster="media/{stem}.jpg" src="media/{stem}-review.mp4"></video><div class="links"><a href="media/{stem}-review.mp4">Open 40-second video</a><a href="media/{board}">Matched frame sequence</a></div></article>');rows.append({'source':str(folder/'played.mp4'),'sourceModelSHA256':expected,'sourceMovieSHA256':sha(folder/'played.mp4'),'reviewMovie':video.name,'reviewMovieSHA256':sha(video),'ffmpeg':command,'ffprobe':probe,'limits':'CPU video encoding only;1280×720/480actualframes retained, no reframing, repaint or pose substitution. Original full-quality movie is preserved in source evidence.'})
section+=''.join(cards)+'</section></section>'
html=html.replace('<section id="latest-comparison">',section+'<section id="latest-comparison">');assert html.count('<video ')==21;recipe.write_text(html);(site/'dist/index.html').write_text(html)
(out/'site-media.json').write_text(json.dumps({'previousVideosRetained':15,'addedVideos':6,'totalVideos':21,'rows':rows},indent=2)+'\n');print(json.dumps({'totalVideos':21,'addedVideos':6,'reviewBytes':sum((media/r.get('video',r.get('reviewMovie'))).stat().st_size for r in rows)}))
