"""Actual closed candidate: IPC, edge folds, conservation and export roundtrip."""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS','2');os.environ.setdefault('OMP_NUM_THREADS','2')
from pathlib import Path
import hashlib,importlib.util,json,time,numpy as np,ipctk
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components
from fractions import Fraction as Q
ipctk.set_num_threads(2);ROOT=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');R=B/'head-sew216';E=ROOT/'docs/evidence/hero-remaster/one-rider-v2/head-sew216';s=time.monotonic();z=np.load(R/'construction.npz');P=z['positions'].astype(float);F=z['faces'].astype(np.int32);V=z['attributePositions'];AF=z['attributeFaces'];mat=z['materials'];roles=z['roles'];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
D=np.concatenate([F[:,[0,1]],F[:,[1,2]],F[:,[2,0]]]);edges,iv,c=np.unique(np.sort(D,axis=1),axis=0,return_inverse=True,return_counts=True);sign=np.where(D[:,0]<D[:,1],1,-1);w=np.bincount(iv,weights=sign,minlength=len(edges));areas=np.linalg.norm(np.cross(P[F[:,1]]-P[F[:,0]],P[F[:,2]]-P[F[:,0]]),axis=1)/2
intersects=bool(ipctk.has_intersections(ipctk.CollisionMesh(P,edges.astype(np.int32),F),P));face_ids=np.tile(np.arange(len(F)),3);order=np.argsort(iv,kind='stable');off=np.r_[0,np.cumsum(c)];two=np.flatnonzero(c==2);fa=face_ids[order[off[two]]];fb=face_ids[order[off[two]+1]];EE=edges[two];A=P[EE[:,0]];B0=P[EE[:,1]];oa=np.array([next(int(x) for x in F[i] if x not in e) for i,e in zip(fa,EE)]);ob=np.array([next(int(x) for x in F[i] if x not in e) for i,e in zip(fb,EE)]);C=P[oa];D0=P[ob];n1=np.cross(B0-A,C-A);n2=np.cross(B0-A,D0-A);same=(n1*n2).sum(1)>0;triple=np.einsum('ij,ij->i',n1,D0-A);near=np.flatnonzero(same&(abs(triple)<=1e-12*np.linalg.norm(n1,axis=1)*np.maximum(np.linalg.norm(D0-A,axis=1),1e-20)));fold=[]
def exact_coplanar(a,b,c,d):
 x=[[Q(float(p[k]))-Q(float(a[k])) for k in range(3)] for p in [b,c,d]]
 return x[0][0]*(x[1][1]*x[2][2]-x[1][2]*x[2][1])-x[0][1]*(x[1][0]*x[2][2]-x[1][2]*x[2][0])+x[0][2]*(x[1][0]*x[2][1]-x[1][1]*x[2][0])==0
for k in near:
 if exact_coplanar(A[k],B0[k],C[k],D0[k]):fold.append({'edge':EE[k].tolist(),'facePair':[int(fa[k]),int(fb[k])],'roles':[str(roles[fa[k]]),str(roles[fb[k]])]})
components,labels=connected_components(coo_matrix((np.ones(2*len(edges)),(np.r_[edges[:,0],edges[:,1]],np.r_[edges[:,1],edges[:,0]])),shape=(len(P),len(P))).tocsr());component_rows=[]
for ci in range(components):
 ids=np.flatnonzero(labels==ci);fs=np.flatnonzero(labels[F[:,0]]==ci);component_rows.append({'vertices':len(ids),'faces':len(fs),'roles':sorted(set(roles[fs].tolist()))})
# Verify GLB actually contains these positions/incidences and unchanged head source assets.
spec=importlib.util.spec_from_file_location('reader',ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);g=m.GLB(R/'rider.glb');source=m.GLB(B/'source-preserving-garment185/operator/rider.glb');pr=g.j['meshes'][0]['primitives'];gv=g.array(pr[0]['attributes']['POSITION']);guv=g.array(pr[0]['attributes']['TEXCOORD_0']);assert np.array_equal(gv,V) and np.array_equal(guv,z['attributeUV']);assert all(np.array_equal(g.array(p['indices']).reshape(-1,3),AF[mat==i]) for i,p in enumerate(pr));assert g.bin[:len(source.bin)]==source.bin
provenance=json.loads((R/'attribute-provenance.json').read_text());hp=source.j['meshes'][1]['primitives'][0];hs=source.array(hp['attributes']['POSITION']);huv=source.array(hp['attributes']['TEXCOORD_0']);hn=source.array(hp['attributes']['NORMAL']);gn=g.array(pr[0]['attributes']['NORMAL']);head=[(i,p['row']) for i,p in enumerate(provenance) if p.get('kind')=='donor185-original' and p.get('protected')];assert all(np.array_equal(gv[i],hs[row]) and np.array_equal(guv[i],huv[row]) and np.array_equal(gn[i],hn[row]) for i,row in head)
# Count true outer weld physical vertices: both body/head faces incident to same quotient ID.
body=np.unique(F[mat==0]);headids=np.unique(F[mat==1]);weld=np.intersect1d(body,headids);assert len(weld)==549;capids=np.flatnonzero(roles=='internal-cap');cap_area_sum=float(areas[capids].sum());cap_sumvec=np.cross(P[F[capids,1]]-P[F[capids,0]],P[F[capids,2]]-P[F[capids,0]]).sum(0)/2;cap_winding_consistent=bool(abs(np.linalg.norm(cap_sumvec)-cap_area_sum)<=1e-10*cap_area_sum);okay=not intersects and not fold and int((c==1).sum())==0 and int((c>2).sum())==0 and int(((c==2)&(w!=0)).sum())==0 and not (areas==0).any() and cap_winding_consistent
report={'status':'REST_GATE_CLEAR_WITHIN_MEASURED_COVERAGE_NO_ART_RIG_ACCEPTANCE' if okay else 'STOPPED_REST_GEOMETRY_FAILED','candidateSHA256':sha(R/'rider.glb'),'constructionSHA256':sha(R/'construction.npz'),'vertices':len(P),'faces':len(F),'boundaryEdges':int((c==1).sum()),'nonmanifoldEdges':int((c>2).sum()),'windingConflictEdges':int(((c==2)&(w!=0)).sum()),'zeroAreaFaces':int((areas==0).sum()),'minimumAreaM2':float(areas.min()),'fullNativeIPCAnyIntersection':intersects,'sameSideNearCoplanarEdgeCandidates':len(near),'exactAdjacentPositiveCoplanarFolds':len(fold),'foldWitnesses':fold,'components':component_rows,'trueBodyHeadSharedPhysicalVertices':len(weld),'internalCapTriangles':len(capids),'capAreaM2':cap_area_sum,'capConsistentPlanarWinding':cap_winding_consistent,'exportedPositionsUVIndicesRoundtripExact':True,'protectedHeadGeometryUVNormalsRowsExact':len(head),'headPBRSourceBINPrefixExact':True,'nativeThreads':ipctk.get_num_threads(),'seconds':time.monotonic()-s,'limits':['Measured IPC controls detect nonadjacent coplanar overlap but not sharededge folds; separate adjacent fold check included','Static gate only; no near-coplanar thickness/appearance, neck rotation, bend, rig, gameplay/contact/mobile pass','Six-vertex inherited disconnected native component remains exactly; body source is still finite subset of invalid native output','Body unpainted, native arms short, source anatomy unresolved','OutputGLB unrigged; source head bind weights saved but not promoted into a new rig']};(E/'rest-audit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
