"""Freeze one closed unaccepted candidate and completed static receipts."""
from pathlib import Path
import json,hashlib,gzip
ROOT=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');E=ROOT/'docs/evidence/hero-remaster/one-rider-v2/head-sew216';A=ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/head-sew216';R=B/'head-sew216';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
# Preserve original unified diff privately and commit byte-equivalent gzip. Context
# blank lines are meaningful diff bytes, not source trailing whitespace to modify.
diff=E/'cache-only.diff'
if diff.exists():
 raw=diff.read_bytes();original=R/'cache-only.diff';assert not original.exists();original.write_bytes(raw);compressed=E/'cache-only.diff.gz';compressed.write_bytes(gzip.compress(raw,mtime=0));assert gzip.decompress(compressed.read_bytes())==raw;diff.unlink();(E/'cache-diff-pin.json').write_text(json.dumps({'originalNamespace':str(diff),'retainedOriginal':str(original),'originalSHA256':sha(original),'gzip':str(compressed),'gzipSHA256':sha(compressed),'exactDecompressedEquality':True},indent=2)+'\n')
inputs=json.loads((E/'build-report.json').read_text())['inputs'];reader=ROOT/'assets/blender/hero-remaster/rider/one-rider-v2/candidate-handoff170/map_candidate.py';inputs[str(reader)]=sha(reader);frozen213=ROOT/'docs/evidence/hero-remaster/one-rider-v2/head-sew213/freeze.json';inputs[str(frozen213)]=sha(frozen213);assert all(sha(Path(p))==h for p,h in inputs.items());audit=json.loads((E/'rest-audit.json').read_text());report={'status':'FROZEN_CLOSED_STATIC_NECK_SEW_NO_ART_RIG_ACCEPTANCE','geometryAttempts':1,'previousFailedAttempt':'head-sew213 remains immutable','candidateSHA256':sha(R/'rider.glb'),'inputPins':inputs,'ownedFiles':{str(p):sha(p) for p in list(A.glob('*.py'))+list(E.glob('*')) if p.name!='freeze.json'},'privateOutputs':{str(p):sha(p) for p in R.glob('*') if p.is_file()},'sourcesUnchanged':True,'GPUJob':False,'CPUThreads':2,'allJobsTerminal':True,'rendersStarted':0,'deferredReason':'User requested wrap up; no new render or experiment launch','restStatus':audit['status'],'limits':['Static closed join only; no appearance, rig, neck/spine motion or gameplay/contact/mobile gate','Body gray and native arms short; independent arm216 not composed','Finite-subset source qualification unchanged; no production promotion']};(E/'freeze.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'freezeSHA256':sha(E/'freeze.json'),'inputs':len(inputs),'ownedFiles':len(report['ownedFiles']),'privateOutputs':len(report['privateOutputs']),'candidateSHA256':report['candidateSHA256']},indent=2))
