"""Silent CPU film encoding and frozen neutral appearance evidence receipt."""
from pathlib import Path
import json,struct,hashlib,subprocess
R=Path('/Users/raynos/projects/games/rockhop');S=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/source-preserving-garment186/render');E=R/'docs/evidence/hero-remaster/one-rider-v2/source-preserving-garment186/render';A=R/'assets/blender/hero-remaster/rider/one-rider-v2/source-preserving-garment186/render';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();attempt=json.loads((E/'attempt.json').read_text())
try:
 process=json.loads((E/'process.json').read_text());assert process['status']=='FROZEN_CPU_RENDER_COMPLETE'and process['exitCode']==0
 images=[E/f'{mode}-{view}.png'for mode in ['pbr','gray']for view in ['front','side','back']];frames=[S/'frames'/f'{mode}-{i:03d}.png'for mode in ['pbr','gray']for i in range(24)];assert len(images+frames)==54
 for p in images+frames:
  b=p.read_bytes();assert b[:8]==b'\x89PNG\r\n\x1a\n'and struct.unpack_from('>II',b,16)==(400,450)
 films=[]
 for mode in ['pbr','gray']:
  out=E/f'{mode}-turntable.mp4';assert not out.exists();cmd=['/opt/homebrew/bin/ffmpeg','-hide_banner','-loglevel','error','-framerate','6','-i',str(S/'frames'/f'{mode}-%03d.png'),'-frames:v','24','-an','-c:v','libx264','-threads','2','-pix_fmt','yuv420p','-movflags','+faststart',str(out)];subprocess.run(cmd,check=True);probe=json.loads(subprocess.check_output(['/opt/homebrew/bin/ffprobe','-v','error','-count_frames','-show_streams','-show_format','-of','json',str(out)],text=True));streams=probe['streams'];assert len(streams)==1 and streams[0]['codec_type']=='video';v=streams[0];assert int(v['nb_read_frames'])==24 and v['width']==400 and v['height']==450 and v['r_frame_rate']=='6/1'and float(probe['format']['duration'])==4
  films.append({'path':str(out),'sha256':sha(out),'frames':24,'fps':6,'durationSeconds':4,'audioStreams':0,'encodingArgv':cmd,'probe':probe})
 prep=json.loads((E/'preparation.json').read_text());report={'status':'FROZEN_MATCHED_STATIC_NEUTRAL_EVIDENCE_AWAIT_PARENT_PLAYBACK','sourceSHA256':prep['sourceSHA256'],'neutralSHA256':prep['neutralSHA256'],'sourceBINAndGeometryExact':True,'staticViewOnly':True,'original19SkinAssetAnimationAccepted':False,'exact179SettingsExceptPaths':True,'CPUThreads':2,'samples':4,'resolution':[400,450],'imageCount':54,'filmCount':2,'films':films,'protected185VerifierRecipeSha256':prep['owned185VerifierSHA256'],'process':process,'limits':['No rig/pose/game readiness or parent appearance judgment','Neutral GLB removes only skins, animations and node.skin JSON; source BIN/geometry/PBR/transforms preserved','Private Blender import is a rendering view, not a source re-export or replacement asset']};(E/'report.json').write_text(json.dumps(report,indent=2)+'\n');attempt['status']=report['status'];(E/'attempt.json').write_text(json.dumps(attempt,indent=2)+'\n')
 files=[p for p in E.glob('*')if p.is_file()and p.name!='freeze.json']+list(A.glob('*.py'))+[p for p in S.rglob('*')if p.is_file()];freeze={'status':report['status'],'files':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(files)]};(E/'freeze.json').write_text(json.dumps(freeze,indent=2)+'\n');print(json.dumps({'status':report['status'],'films':[{k:v for k,v in f.items()if k not in ['probe','encodingArgv']}for f in films],'freezeSha256':sha(E/'freeze.json')}))
except Exception as e:
 attempt['status']='FROZEN_ENCODING_OR_RECEIPT_FAILURE';attempt['failures'].append({'stage':'encoding/receipt','type':type(e).__name__,'error':str(e)});(E/'attempt.json').write_text(json.dumps(attempt,indent=2)+'\n');raise
