"""Read-only exact native/GLB/importer face-index difference; no repair/render."""
import bpy,numpy as np,json,struct,hashlib
from pathlib import Path
R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/A-new-head-audit');G=R/'generation/h21-buzz-native01';O=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/A-new-head-audit/generation-evidence/h21-buzz-native01')
if (O/'raw-index-forensic.json').exists():raise RuntimeError('Frozen forensic exists')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
inputs={str(p):sha(p) for p in [G/'raw-shape.npz',G/'raw-shape.glb']};data=np.load(G/'raw-shape.npz');vertices=data['vertices'];faces=data['faces'];blob=(G/'raw-shape.glb').read_bytes();jlen,jkind=struct.unpack_from('<II',blob,12);gltf=json.loads(blob[20:20+jlen]);binaryStart=20+jlen+8;binary=blob[binaryStart:];primitive=gltf['meshes'][0]['primitives'][0];accessor=gltf['accessors'][primitive['indices']];view=gltf['bufferViews'][accessor['bufferView']];offset=view.get('byteOffset',0)+accessor.get('byteOffset',0);assert accessor['componentType']==5125
glbFaces=np.frombuffer(binary,dtype='<u4',count=accessor['count'],offset=offset).reshape(-1,3);assert np.array_equal(glbFaces,faces),'Raw source GLB index payload changed'
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(G/'raw-shape.glb'));meshes=[o for o in bpy.context.scene.objects if o.type=='MESH'];assert len(meshes)==1;m=meshes[0].data;loops=np.empty(len(m.loops),np.int32);m.loops.foreach_get('vertex_index',loops);lengths=np.empty(len(m.polygons),np.int32);m.polygons.foreach_get('loop_total',lengths);assert np.all(lengths==3);imported=loops.reshape(-1,3)
# Stable index signatures retain duplicate occurrences; never silently deduplicate.
canonical=np.sort(faces,axis=1);canonicalImported=np.sort(imported,axis=1);rowtype=np.dtype((np.void,canonical.dtype.itemsize*3));sourceRows=canonical.view(rowtype).ravel();importRows=canonicalImported.view(rowtype).ravel();u,counts=np.unique(sourceRows,return_counts=True);iu,icounts=np.unique(importRows,return_counts=True);where=np.searchsorted(iu,u);present=np.zeros(len(u),np.int64);valid=where<len(iu);matching=np.zeros(len(u),bool);matching[valid]=iu[where[valid]]==u[valid];present[matching]=icounts[where[matching]];missingCounts=counts-present;missingTypes=u[missingCounts>0];missingMask=np.isin(sourceRows,missingTypes);missingIDs=np.flatnonzero(missingMask)
repeat=(faces[:,0]==faces[:,1])|(faces[:,1]==faces[:,2])|(faces[:,0]==faces[:,2]);area=np.linalg.norm(np.cross(vertices[faces[:,1]]-vertices[faces[:,0]],vertices[faces[:,2]]-vertices[faces[:,0]]),axis=1)*.5
report={'status':'UNACCEPTED exact raw index containment/importer forensic','inputsSHA256':inputs,'sourceNPZVertices':len(vertices),'sourceNPZTriangles':len(faces),'rawGLBIndexTriangles':len(glbFaces),'rawGLBIndicesEqualNativeNPZ':True,'rawGLBIndexSHA256':hashlib.sha256(glbFaces.astype(np.int32).tobytes()).hexdigest(),'nativeNPZFaceIndexSHA256':hashlib.sha256(faces.tobytes()).hexdigest(),'BlenderImportedVertices':len(m.vertices),'BlenderImportedTriangles':len(imported),'triangleCountDifference':len(faces)-len(imported),'missingTriangleOccurrences':int(missingCounts[missingCounts>0].sum()),'sourceMissingFaceIDs':missingIDs.tolist(),'missingFaceRepeatedVertexIndexCount':int(repeat[missingIDs].sum()),'missingFaceZeroAreaCount':int((area[missingIDs]==0).sum()),'sourceTotalRepeatedVertexIndexTriangles':int(repeat.sum()),'sourceTotalExactlyZeroAreaTriangles':int((area==0).sum()),'sourceDuplicateUnorderedTriangleOccurrences':int((counts-1).sum()),'limits':['GLB index byte preservation proved separately from Blender importer/render validation.','No original source repair or reduction; no appearance/motion acceptance.','Missing source face IDs include every occurrence of missing repeated index signatures; occurrence count reported separately.']}
assert inputs=={p:sha(Path(p)) for p in inputs};(O/'raw-index-forensic.json').write_text(json.dumps(report,indent=2)+'\n');print('RAW_IMPORTER_FORENSIC',json.dumps({k:report[k] for k in ['rawGLBIndicesEqualNativeNPZ','triangleCountDifference','missingTriangleOccurrences','missingFaceRepeatedVertexIndexCount','missingFaceZeroAreaCount']}),flush=True)
