"""Read-only literal protected seam membership and lower skin risk, no repair."""
from pathlib import Path
from collections import Counter
import ast,json,struct,hashlib,numpy as np
from scipy.spatial.transform import Rotation
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');O=R/'docs/evidence/hero-remaster/one-rider-v2/source-preserving-garment184/source-audit';S=B/'source-preserving-garment184/source-audit';sha=lambda b:hashlib.sha256(b).hexdigest();reader=R/'assets/blender/hero-remaster/rider/one-rider-v2/rig-foundation167/prepare.py';tree=ast.parse(reader.read_text());cls=next(x for x in tree.body if isinstance(x,ast.ClassDef)and x.name=='GLB');env={'Path':Path,'json':json,'struct':struct,'np':np,'Rotation':Rotation,'sha':sha};exec(compile(ast.Module(body=[cls],type_ignores=[]),str(reader),'exec'),env);source=Path('/Users/raynos/Documents/Codex/2026-10-01/task-3/deliverables/C19.glb');C=env['GLB'](source,'186d0f86ae62722689be3c194f7437f623799c837e7ba515358680db12a1382e');parts=[C.primitive(0,i)for i in range(3)];common=set(map(tuple,parts[0][0]['POSITION']))&set(map(tuple,parts[2][0]['POSITION']));assert len(common)==307;wfile=S/'all-strict-witnesses.json';w=json.loads(wfile.read_text());rows=[]
for x in w:
 faces=[]
 for key in ['A','B']:
  f=x[key];pi=f['sourcePrimitive'];ids=np.array(f['sourceVertexIDs']);p=parts[pi][0]['POSITION'][ids];lock=np.array([tuple(v)in common for v in p]);faces.append({'sourcePrimitive':pi,'sourceFace':f['sourceFace'],'sourceVertexIDs':ids.tolist(),'protectedHoodBodySeamMembership':lock.tolist(),'sourceFloat32Positions':p.tolist(),'boundsM':[p.min(0).tolist(),p.max(0).tolist()]})
 rows.append({'pairID':x['pairID'],'faces':faces,'repairConstraint':'Shared307seam positions stayfixed; sourcehood/head likeness isprotected. A bodyonly adjustment cannotremovehoodselfcrossings. Any futurehoodinterior surgery needsparent explicitpermission; no repair performed.'})
hoodFaceIDs=sorted({f['sourceFace']for x in w for f in [x['A'],x['B']]if f['sourcePrimitive']==2});hoodVerts=np.unique(parts[2][1][hoodFaceIDs]);interior=[int(i)for i in hoodVerts if tuple(parts[2][0]['POSITION'][i])not in common];locked=[int(i)for i in hoodVerts if tuple(parts[2][0]['POSITION'][i])in common];hpos,hinv=np.unique(parts[2][0]['POSITION'],axis=0,return_inverse=True);he=Counter(tuple(sorted([int(t[k]),int(t[(k+1)%3])]))for t in hinv[parts[2][1]]for k in range(3));openIDs={v for e,n in he.items()if n==1 for v in e};upperBoundary={tuple(hpos[i])for i in openIDs if tuple(hpos[i])not in common};assert len(upperBoundary)==237;upperLocked=[int(i)for i in hoodVerts if tuple(parts[2][0]['POSITION'][i])in upperBoundary];assert not upperLocked
bodyFaceIDs=sorted({f['sourceFace']for x in w for f in [x['A'],x['B']]if f['sourcePrimitive']==0});a,T=parts[0];P=a['POSITION'];ids=np.flatnonzero(((P[T][:,:,1]>.69)&(P[T][:,:,1]<1.08)&(abs(P[T][:,:,2])<.245)).all(1));vertices=np.unique(T[ids]);W=np.zeros((len(P),19))
for k in range(4):np.add.at(W,(np.arange(len(P)),a['JOINTS_0'][:,k]),a['WEIGHTS_0'][:,k])
nam=[C.d['nodes'][i]['name'].removeprefix('fresh.')for i in C.d['skins'][0]['joints']];thigh=W[:,[nam.index('thigh.L'),nam.index('thigh.R')]].sum(1);pelvis=W[:,nam.index('pelvis')];rids=vertices[(thigh[vertices]>.99)&(pelvis[vertices]==0)];example=16094;ti=T[example]
result={'status':'ORIGINAL_SOURCE_LOCAL_RISK_ONLY_NO_GEOMETRY','sourceSHA256':C.h,'sourceBodyCrossingFaces':bodyFaceIDs,'sourceHoodCrossingFaces':hoodFaceIDs,'hoodAffectedUniqueRows':len(hoodVerts),'hoodAffectedProtected307SeamRows':locked,'hoodAffectedNonSeamInteriorRows':interior,'hoodAffectedUpper237BoundaryRows':upperLocked,'crossingSeamMembershipWitnesses':rows,'feasibility':{'topologicallyLocalCandidate':True,'reason':'Onlyone sourcebodyface and13sourcehoodfaces participate in the measured strictpairs, inthree spatialclusters. Literal local face/row lists allow a bounded sourcepatch diagnosis; this does not prove a repair succeeds.','bodyOnlyCannotClearAll':'Ninehoodselfcrossings remain even ifbody7449 ischanged. No body-only edit can alterthose intersections.','protectedSeamConstraint':'Several crossingfaces contain2protected307seam nodes; none hasall3 locked. Keepthese exactseam anchors anddonor aliasesfixed. Other affectedhoodrows areinterior and mayallowlocal edge-diagonal/patch surgery withinfixed boundary, subject to parent permittedhood edits.','targetedAlternative':'Classifyeach cluster as a local source patch, retain literal outer patch and307seam nodes, test a constrainedlocal connectivity alternative or permittedinterior fold separation; reject ifpatch boundary itself forces crossing. No remesh/export or successfulrepair claim.'},'lowerRisk':{'scope':'Geometric allcorners .69<Y<1.08 andabsZ<.245, not certified butt-only anatomy','sourceTriangles':len(ids),'sourceVertices':len(vertices),'strongThighOver99percentAndZeroPelvisVertices':len(rids),'maximumThighWeight':float(thigh[vertices].max()),'meanPelvisWeight':float(pelvis[vertices].mean()),'pelvisZeroVertices':int((pelvis[vertices]==0).sum()),'literalSaddleReferenceFace':{'face':example,'sourceVertexIDs':ti.tolist(),'positions':P[ti].tolist(),'canonicalWeights19':W[ti].tolist()},'warning':'Strongthigh ownership canbe correctforupperlegs; without seatedphysicsmotion it doesnot certify orrejectbutt/hipdeformation. Zero strictrestbodyselfcrossings isnotseated clearancelandingweight/contact approval. Fusedshirt/denim materialownership remains semantic, not solvedby sourceprimitive orflatheight.'},'inputs':[{'path':str(p),'SHA256':sha(p.read_bytes())}for p in [source,reader,wfile]],'recipeSHA256':sha(Path(__file__).read_bytes())};(O/'local-risk.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'bodyFaces':bodyFaceIDs,'hoodFaces':hoodFaceIDs,'affectedHoodRows':len(hoodVerts),'protectedRows':locked,'nonSeamRows':interior,'lowerFaces':len(ids),'strongThighVertices':len(rids),'zeroPelvisVertices':result['lowerRisk']['pelvisZeroVertices']}))
