"""Read-only actual palmar and thumb surface witnesses on both skin variants."""
import json,hashlib
from pathlib import Path
import numpy as np
ROOT=Path('/Users/raynos/projects/games/rockhop');BASE=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');OUT=ROOT/'docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/native-grip02';RUN=BASE/'rig-adapter01/native-grip02';LAND=OUT.parent/'native-landmarks'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
path=RUN/'native-hand-animation.npz';d=np.load(path);report=json.loads((OUT/'build-report.json').read_text());h=json.loads((LAND/'report.json').read_text())['hands'][0];normal=-np.array(h['sourceCanonicalNormalMapped']);length=np.array(h['palmLongAxisWristToMCP']);axis=d['cylinderAxis'];centre=d['cylinderCentre'];radius=float(d['cylinderRadius']);tris=d['triangleIndices'];ids=d['sourceCompleteVertexIds'];rest=d['sourcePositions'];mapping=json.loads((LAND/'native-weight-transfer-map.json').read_text())['matches'][0];fw=np.array([sum(w for n,w in gs if n.startswith('finger') and n.endswith('.L')) for gs in mapping['nativeWeights']]);fixedtris=np.flatnonzero(np.all(fw[tris]<.02,axis=1));variants={}
for mode in ['DQS','LBS']:
 p=d['framePositions'+mode][16];q=p-centre;rad=q-np.outer(q@axis,axis);r=np.linalg.norm(rad,axis=1);t=np.stack([q@normal,q@length],1)[tris[fixedtris]];a=t;b=np.roll(t,-1,axis=1);edge=b-a;u=np.clip(-np.sum(a*edge,2)/np.maximum(np.sum(edge*edge,2),1e-18),0,1);closest=a+u[:,:,None]*edge;dist=np.linalg.norm(closest,axis=2);ti,ei=np.unravel_index(np.argmin(dist),dist.shape);first=int(tris[fixedtris[ti],ei]);second=int(tris[fixedtris[ti],(ei+1)%3]);point=p[first]*(1-u[ti,ei])+p[second]*u[ti,ei];contacts=[]
 for finger in range(1,6):
  indices=np.array([vi for vi,gs in enumerate(mapping['nativeWeights']) if sum(w for n,w in gs if n.startswith(f'finger{finger}-') and n.endswith('.L'))>.5]);gap=r[indices]-radius;nearest=np.argsort(np.abs(gap))[:5]
  contacts.append({'finger':finger,'minimumAbsoluteSkinGapM':float(np.abs(gap).min()),'skinVerticesWithin1mm':int((np.abs(gap)<=.001).sum()),'surfaceWitnesses':[{'completeVertexId':int(ids[indices[i]]),'point':p[indices[i]].tolist(),'radialGapM':float(gap[i]),'axialDistanceM':float((p[indices[i]]-centre)@axis)} for i in nearest]})
 wrist=d['wristLoopLocalIds'];variantframes=d['framePositions'+mode];axial=(variantframes-centre)@axis
 variants[mode]={'distalPalmStaticTriangleWitness':{'nativeTriangleIndex':int(fixedtris[ti]),'nativeTriangleVertices':tris[fixedtris[ti]].tolist(),'completeTriangleVertices':ids[tris[fixedtris[ti]]].tolist(),'actualClosestPoint':point.tolist(),'radialGapM':float(dist[ti,ei]-radius),'axialDistanceM':float((point-centre)@axis),'status':'Actual fixed native palm triangle edge witness; no invented socket'},'fingerContacts':contacts,'maximumAbsoluteAxialDistanceAcrossFramesM':float(np.abs(axial).max()),'allVerticesWithinFinite160mmCylinderAxialRange':bool(np.abs(axial).max()<=.08),'maximumWristDeltaAcrossFramesM':float(np.linalg.norm(variantframes[:,wrist]-rest[wrist],axis=2).max()),'lastOpenMaximumPositionDeltaM':float(np.linalg.norm(variantframes[-1]-rest,axis=1).max()),'morphDeltaSHA256':hashlib.sha256(d['morphDelta'+mode].tobytes()).hexdigest()}
(OUT/'contact-audit.json').write_text(json.dumps({'status':'Actual native skin contact witnesses; closingtransitionremainfailed','bufferSHA256':sha(path),'variants':variants,'recipeSHA256':sha(Path(__file__)),'limits':['Skin witnesses are actualmeshpoints; visual grip still belongs toparent.','Palmwitness is edgeclosestamongfixedpalmsurfaces, notanacceptedruntimecontactsocket.','33frame samplecoverage, no certificate forunsampled continuousmotion.']},indent=2)+'\n');print('ACTUAL_PALM_AND_THUMB_CONTACT_WITNESSES_FROZEN')
