"""Clarify finite-length coverage of the frozen worst penetration witness."""
import json,hashlib
from pathlib import Path
import numpy as np
OUT=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/native-grip02');RUN=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/rig-adapter01/native-grip02');LAND=OUT.parent/'native-landmarks';d=np.load(RUN/'native-hand-animation.npz');h=json.loads((LAND/'report.json').read_text())['hands'][0];normal=-np.array(h['sourceCanonicalNormalMapped']);length=np.array(h['palmLongAxisWristToMCP']);axis=d['cylinderAxis'];tris=d['triangleIndices'];report=json.loads((OUT/'build-report.json').read_text());witness=[]
for mode,rows in report['frameChecks'].items():
 for label,row in [('worst',max(rows,key=lambda r:r['maximumContinuousTriangleCylinderPenetrationM'])),('wrapped',rows[16])]:
  frame=row['frame'];p=d['framePositions'+mode][frame];q=p-np.array(row['handleCentre']);t=np.stack([q@normal,q@length],1)[tris];a=t;b=np.roll(t,-1,axis=1);e=b-a;cross=a[:,:,0]*b[:,:,1]-a[:,:,1]*b[:,:,0];inside=(cross.min(1)>=-1e-15)|(cross.max(1)<=1e-15);u=np.clip(-np.sum(a*e,2)/np.maximum(np.sum(e*e,2),1e-18),0,1);near=a+u[:,:,None]*e;dist=np.linalg.norm(near,axis=2).min(1);dist[inside]=0;index=int(np.argmin(dist));axial=q[tris[index]]@axis;witness.append({'mode':mode,'phase':label,'frame':frame,'sourceLocalTriangleVertices':tris[index].tolist(),'sourceCompleteTriangleVertices':d['sourceCompleteVertexIds'][tris[index]].tolist(),'radialTrianglePenetrationM':float(.018-dist[index]),'triangleAxialBoundsM':[float(axial.min()),float(axial.max())],'entireWorstTriangleWithinFinite160mmCylinder':bool(np.abs(axial).max()<=.08)})
(OUT/'finite-cylinder-witness.json').write_text(json.dumps({'status':'Exact finite-length verification of worst frozen penetration triangles','witnesses':witness,'allHandVerticesGloballyWithinAxialRange':False,'globalMaximumAxialOverrunM':.00058410648355699,'limit':'Some open thumb vertices extend0.584mmpastoneendcap; do notclaim globalfullcylindercoverage. Worst/closed penetration triangles independentlytested.','recipeSHA256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()},indent=2)+'\n');print('FINITE_CYLINDER_WORST_WITNESSES_FROZEN')
