"""Document exact projected source triangle when original hood occludes marker."""
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import numpy as np,json,hashlib,datetime
P=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();j=json.loads((P/'tongue-center-source-witness.json').read_text());im=Image.open(P/'original-source-graytongue-witness-profile.png').convert('RGB');d=ImageDraw.Draw(im);font=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',18);small=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',15)
target=np.array([0,.01,1.50]);right=np.array([0,1,0]);up=np.array([-.025,0,4]);up/=np.linalg.norm(up)
def project(p):p=np.array(p)-target;return (400+float(p@right)*800/.66,400-float(p@up)*800/.66)
tri=[project(p) for p in j['originalTriangleXYZ']];q=project(j['XYZ']);d.line(tri+[tri[0]],fill=(255,40,40),width=3);d.ellipse((q[0]-8,q[1]-8,q[0]+8,q[1]+8),outline=(255,40,40),width=3);d.line([(650,210),q],fill=(255,40,40),width=3);d.rectangle((430,145,795,213),fill=(24,24,24));d.text((439,151),'Projected source face '+str(j['originalSourceTriangle']),font=font,fill='white');d.text((439,179),'Occluded inside original hood fold',font=small,fill=(255,190,70));d.rectangle((8,730,792,794),fill=(24,24,24));d.text((16,737),'Read-only annotation. Gray-tongue center maps to rear inner hood region.',font=small,fill='white');d.text((16,761),'Source anatomy label remains unaccepted; no silent skin/lining assumption.',font=small,fill=(255,190,70));out=P/'source-profile-exactface-projection.png';im.save(out)
record={'status':'Read-only same-finding supplement, no geometry/material/source changes','exactCenterWitness':j,'projectedProfileCenterPixels':list(q),'projectedOriginalTrianglePixels':tri,'annotationDisclosure':'Original surface physically occludes red3Dmarker. This overlay shows exact projected sourceface coordinates through that occlusion, not a visible originalface or altered asset.','actualProfileOriginalRender':str(P/'original-source-graytongue-witness-profile.png'),'annotatedProfile':str(out),'finishUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'recipeSHA':sha(__file__)};(P/'precise-tongue-supplement.json').write_text(json.dumps(record,indent=2)+'\n');(P/'supplement-freeze-manifest.json').write_text(json.dumps({'finishUTC':record['finishUTC'],'files':{p.name:sha(p) for p in [P/'tongue-center-source-witness.json',P/'precise-tongue-supplement.json',P/'original-source-graytongue-witness-profile.png',P/'original-source-graytongue-witness-three-quarter.png',out]},'noSourceChanges':True},indent=2)+'\n');print('Exact sourceface',j['originalSourceTriangle'],'profileprojected center',q)
