"""Read-only camera-ray/source-face/texel tracing of parent-rejected gray tongue."""
import bpy,numpy as np,json,hashlib,math
from pathlib import Path
from mathutils import Vector
R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');O=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();before={str(p):sha(p) for p in [R/'anatomical-source-hood.blend',R/'anatomical-source-hood.glb',R/'true-clipped-hood.npz']};bpy.ops.wm.open_mainfile(filepath=str(R/'anatomical-source-hood.blend'));obj=next(o for o in bpy.context.scene.objects if o.type=='MESH');d=np.load(R/'true-clipped-hood.npz');src=np.load(R.parent/'wholehood01-trial01/donor-source.npz');mat=obj.data.materials[0];bs=next(n for n in mat.node_tree.nodes if n.type=='BSDF_PRINCIPLED');tex=bs.inputs['Base Color'].links[0].from_node;image=tex.image;W,H=image.size;pix=np.array(image.pixels[:]).reshape(H,W,4);target=Vector((0,.010,1.48));camera=target+Vector((0,-4,.025));rotation=(target-camera).to_track_quat('-Z','Y').to_matrix();right=rotation@Vector((1,0,0));up=rotation@Vector((0,1,0));direction=rotation@Vector((0,0,-1));samples=[]
for y in range(235,259,3):
 for x in range(315,376,3):
  origin=camera+right*((x+.5)/640-.5)*.5+up*(.5-(y+.5)/640)*.5;hit,co,normal,idx=obj.ray_cast(origin,direction)
  if not hit:continue
  vs=d['vertices'][d['faces'][idx]];v0=vs[1]-vs[0];v1=vs[2]-vs[0];v2=np.array(co)-vs[0];dots=np.array([[v0@v0,v0@v1],[v0@v1,v1@v1]]);ab=np.linalg.solve(dots,np.array([v2@v0,v2@v1]));bary=np.array([1-ab.sum(),ab[0],ab[1]]);uv=bary@d['uv'][idx];px=int(uv[0]*W)%W;py=int(uv[1]*H)%H;rgba=pix[py,px];sourceid=int(d['sourceFaceOrigins'][idx]);samples.append({'pixel':[x,y],'derivedTriangle':int(idx),'originalSourceTriangle':sourceid,'hitXYZ':list(co),'barycentric':bary.tolist(),'nativeUV':uv.tolist(),'nativeTexturePixelBottomUp':[px,py],'imageRGBA':rgba.tolist(),'originalSourceTriangleXYZ':src['vertices'][src['faces'][sourceid]].tolist()})
ids=sorted(set(s['originalSourceTriangle'] for s in samples));report={'status':'Read-only exact provenance of suspicious front gray tongue; no recolor or repair','regionPixels':'front640px, x315..375,y235..258; parent-visible gray tongue and immediate fabric context. All samples retained, no color selection.','camera':{'location':list(camera),'target':list(target),'orthoScale':.5,'elevationM':.025,'source':'Exact isolated front render camera'},'sourceMaterial':mat.name,'baseColorTexture':{'node':tex.name,'image':image.name,'size':[W,H],'colorspace':image.colorspace_settings.name,'imagePackedSHA':hashlib.sha256(bytes(image.packed_file.data)).hexdigest() if image.packed_file else None,'pixelValues':'Actual bpyimage float pixels; not a rendered-color inference'},'sourceTriangleIDs':ids,'sourceTriangleCount':len(ids),'sampleCount':len(samples),'samples':samples,'sourceDerivativeHashesUnchanged':before=={p:sha(p) for p in before},'protectedDerivativeSHA':before,'recipeSHA':sha(__file__),'anatomicalInterpretation':'Evaluate exact hitXYZ/source triangle coordinates against measured neck witness and rearclothsourcebounds. Gray source texture alone is not proof of anatomy; no lining/skin attribution assumed.'};(O/'gray-tongue-ray-provenance.json').write_text(json.dumps(report,indent=2)+'\n');print('TONGUE_RAY_PROVENANCE',len(samples),len(ids));print('XYZ bounds',np.array([s['hitXYZ'] for s in samples]).min(0).tolist(),np.array([s['hitXYZ'] for s in samples]).max(0).tolist())
