"""Freeze observed old-skin/hair contamination; do not integrate or adjust cuts."""
from pathlib import Path
import numpy as np,json,hashlib,datetime
from PIL import Image,ImageDraw,ImageFont
BASE=Path('/Users/raynos/projects/games/rockhop');A=BASE/'assets/blender/hero-remaster/rider/one-rider-v2/autonomous-lanes/C-garment-pattern';O=BASE/'docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-trial01';R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-trial01');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
assert not (O/'unsafe-mask-freeze-manifest.json').exists();data=np.load(R/'donor-source.npz');mask=data['mask'];v=data['vertices'];f=data['faces'];mi=np.where(mask)[0];np.savez_compressed(R/'exact-selected-and-removed-source-faceIDs.npz',selected=mi,removed=np.where(~mask)[0])
rep=json.loads((O/'mask-inspection.json').read_text());rep.pop('selectedSourceFaceIDs');rep.pop('removedOriginalHeadHairSkinAndOtherFaceIDs');rep['exactSourceFaceIDsBinary']={'path':str(R/'exact-selected-and-removed-source-faceIDs.npz'),'sha256':sha(R/'exact-selected-and-removed-source-faceIDs.npz'),'selected':int(mask.sum()),'removed':int((~mask).sum())};rep['allOriginalSourceArraysBinary']={'path':str(R/'donor-source.npz'),'sha256':sha(R/'donor-source.npz')};(O/'mask-inspection.json').write_text(json.dumps(rep,indent=2)+'\n')
# Diagnostic topological measurement only. Coordinate equality merges UV splits for counting; no asset is rewritten.
_,inv=np.unique(v.astype(np.float32),axis=0,return_inverse=True);ff=inv[f[mask]];parent=np.arange(len(v));find=lambda x:x
def root(a):
 while parent[a]!=a:parent[a]=parent[parent[a]];a=parent[a]
 return a
def union(a,b):
 a,b=root(int(a)),root(int(b))
 if a!=b:parent[b]=a
for a,b,c in ff:union(a,b);union(a,c)
roots=np.array([root(int(t[0])) for t in ff]);counts=np.unique(roots,return_counts=True)[1];ed=np.concatenate([ff[:,[0,1]],ff[:,[1,2]],ff[:,[2,0]]]);_,ec=np.unique(np.sort(ed,axis=1),axis=0,return_counts=True)
fnt=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',18);small=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',14);board=Image.new('RGB',(1600,1000),(24,24,24));draw=ImageDraw.Draw(board);draw.text((8,8),'FAILED source-only donor01 mask: old neck/skin and floating head fragments remain',font=fnt,fill=(255,190,70));draw.text((8,36),'Initial one-mask inspection; current receiver/body unchanged. No widening, integration, bake or rig performed.',font=small,fill='white')
for row,mode in enumerate(['pbr','gray']):
 for col,view in enumerate(['front','profile','rear','three-quarter']):
  y=70+row*450;x=col*400;draw.text((x+8,y),f'{mode} {view}',font=fnt,fill='white');im=Image.open(O/f'inspection-{mode}-hood-{view}.png').convert('RGB');im=im.resize((400,400),Image.Resampling.LANCZOS);board.paste(im,(x,y+28))
board.save(O/'unsafe-wholehood-mask-board.jpg',quality=94)
paths=[Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/hunyuan21/01')/n for n in ['working-display2.glb','raw-shape.glb','raw-shape.npz']];paths += [Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/glove-cleanup/glove-material/isolated-correction01/bodyPBR.blend'),Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/head-cleanup/mpfb-v8-palette/african/head.blend')];prior=json.loads((O/'setup01-failure.json').read_text())['sourceSHA256After'];source_after={str(p):sha(p) for p in paths};assert prior==source_after
final={'status':'FAILED unsafe source-only cloth separation; unaccepted, no integration','actualStartUTC':'2026-10-01 03:00:58 UTC','deadlineUTC':'2026-10-01 03:30:58 UTC','freezeUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'newDonor01Failures':{'materialImageSetup':1,'unsafeSemanticSeparation':1,'acceptedAppearance':0},'oldH21_4ReducedHoodLineageRetired':15,'visibleFailure':'PBR and gray front/profile show OLD donor neck/skin retained inside hood; floating old-head/skin/hair fragments remain above opening. Color hue cannot distinguish all ochre fabric from flesh/hair. This is our classification failure, not generator blame.','sourceMask':rep['wholeHoodMask'],'nativePBRImageSocketProvenance':rep['imageSocketProvenance'],'selectedSourceTriangles':len(ff),'coordinateExactWeldedDiagnosticTopology':{'method':'Read-only count with float32 position equality to exclude UV split artifacts; no derivative/source welding','components':len(counts),'largestComponentTriangles':int(counts.max()),'componentTriangleCountsDescending':sorted(counts.tolist(),reverse=True),'boundaryEdges':int((ec==1).sum()),'nonmanifoldEdges':int((ec>2).sum())},'sourceAfterSHA256':source_after,'allSourcesUnchanged':prior==source_after,'protectedBodyScope':'Entire source body/gloves/legs/shoes/clothes/materials/UVs/weights byte-identical; receiver not loaded or altered. No body cut or assembly exists.','retainedHighResolutionRaw':'158114vertices316248triangles, untouched. 55k reduced source inspection explicitly labeled; no reliable rawUV transfer asserted.','master':str(R/'donor-mask-inspection.blend'),'masterSHA256':sha(R/'donor-mask-inspection.blend'),'exactFaceIDsBinary':rep['exactSourceFaceIDsBinary'],'actualEvidenceBoard':str(O/'unsafe-wholehood-mask-board.jpg'),'specificNextAlternative':'After parent checkpoint: anatomical source labeling in front/profile/rear, explicit skin-vs-cloth seed sets and connected cloth growth with reviewed true cloth/skin boundary. Keep own native sourceUV/PBR. No blind hue threshold widening and no integration until source-only cloth is clean. Entire donor01 source lineage remains distinct from retired old H21-04 cut/strip repair.','GPU':False,'CPUThreads':2,'noRigOrClearanceClaim':True,'recipes':{p.name:sha(p) for p in [A/'inspect_wholehood01_mask_corrected01.py',A/'render_wholehood01_inspection.py',Path(__file__)]}}
(O/'unsafe-mask-report.json').write_text(json.dumps(final,indent=2)+'\n');(O/'README.md').write_text('''# NEW wholehood01 trial01 — unsafe separation, unaccepted

The corrected actual Principled Base Color socket lookup succeeds. Initial native-PBR55k source mask selects5461triangles using one geometry/material rule. Actual front/profile/rear/three-quarter nativePBR and gray renders show that OLD donor neck/skin and floating head fragments remain. This source-only extraction is unsafe and frozen. No receiver body has been loaded or modified, and no integration/bake/rig follows this failure.

`unsafe-wholehood-mask-board.jpg` is the actual8-view inspection; `unsafe-mask-report.json` records exact failure distinction/source proofs and diagnostic topology. `mask-inspection.json` records image socket provenance and initial mask. Exact selected/removed faceIDs and full source arrays are retained as hashed compact runtimeNPZ. Original failed name-lookup recipe/log remain frozen as setupfailure1; unsafe semantic separation is a separate failure. Neither failure implicates the generator.

All three donor source files/current body/native sizing head bytes match earlier preserved hashes. Full body protected: gloves, limbs, shoes, drawstrings, UVs/materials/native weights unchanged. Higher-resolution raw158114vertices316248triangles remains untouched; this inspection uses original55kreduction/nativePBR and claims no reliable rawtexture mapping. No temporary native head appended, body assembly, neck clearance/motion, runtime rig or production asset exists. Old15failureH21-04hood repair remains retired.

Specific next approach needs an explicit anatomical skin/cloth seed separation inspected from three sides, then connected cloth selection preserving nativeUVs; no blind mask widening. Parent judges and commits before another experiment. OriginalCPU2thread03:00:58→03:30:58UTC bound retained; freeze timestamp inreport. SharedBlender5.2.1 uses isolated laneC config/extensions/scripts/temp; noGPU. Initial log creation redirect was blocked by safetyhook; safe exclusive-create subprocess logging succeeded without overwrite.
''')
files={str(p.relative_to(O)):sha(p) for p in sorted(O.rglob('*')) if p.is_file() and p.name!='unsafe-mask-freeze-manifest.json'};(O/'unsafe-mask-freeze-manifest.json').write_text(json.dumps({'freezeUTC':final['freezeUTC'],'sourceHashesUnchanged':True,'files':files},indent=2)+'\n');print(json.dumps(final,indent=2))
