"""Freeze donor01 setupfailure before any materiallookup correction."""
from pathlib import Path
import json,hashlib,datetime
BASE=Path('/Users/raynos/projects/games/rockhop');OUT=BASE/'docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-trial01';OUT.mkdir(exist_ok=True);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
recipe=BASE/'assets/blender/hero-remaster/rider/one-rider-v2/autonomous-lanes/C-garment-pattern/inspect_wholehood01_mask.py'
paths=[Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/hunyuan21/01')/p for p in ['working-display2.glb','raw-shape.glb','raw-shape.npz']]
prior=json.loads((BASE/'docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/raw-hood01-display-correction/report.json').read_text())['sourceSHA256'];now={str(p):sha(p) for p in paths};assert prior==now
body=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/glove-cleanup/glove-material/isolated-correction01/bodyPBR.blend');head=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/head-cleanup/mpfb-v8-palette/african/head.blend')
assert sha(body)=='952c4ed7fb5f3d82ccdce4c606535e5c347076e1cbdd41f87bc7d31eaac3f1c5';assert sha(head)=='2484a601f81fa1ba173929d310d4e03ca4aca4862ac66bd87a8590765a1a538a'
report={'status':'FAILED NEWdonor01 materialimage lookup setup; no extraction output or receiver change','actualStartUTC':'2026-10-01 03:00:58 UTC','originalDeadlineUTC':'2026-10-01 03:30:58 UTC','freezeUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'failureCountNewDonor01':1,'oldReducedH21_4HoodLineageRetiredFailures':15,'exception':'StopIteration','exceptionSourceLine':8,'cause':'Nameheuristic assumed imported basecolorimage label/name containsBase/base. Actualimported materialname convention differs. Image selection raised beforeclassification, meshconstruction/save or bodyread.','actualBlenderToolOutputSummary':'22:03:07 imported textured GLB in0.05s; Traceback inspect_wholehood01_mask.py line8; StopIteration. Blender5.2.1quit. exec exited0 although Pythonexception; success determined by missing output/error, notshellcode.','proposedSpecificCorrection':'FollowPrincipled BSDF Base Color actual socket link upstream to image texture; recordnodesocket/image provenance. No wildcard texture guessing.','noNextRunBeforeCheckpoint':True,'recipeSHA256':sha(recipe),'donorSourceHashesUnchanged':prior==now,'sourceSHA256After':now|{str(body):sha(body),str(head):sha(head)},'renderOutputCount':0,'maskOutputCount':0,'noGeometryEdited':True,'protectedCurrentBodyHeadBytesUntouched':True,'CPUThreads':2,'GPU':False}
(OUT/'setup01-failure.json').write_text(json.dumps(report,indent=2)+'\n');(OUT/'inspect_wholehood01_mask-failed01.py.txt').write_bytes(recipe.read_bytes());(OUT/'setup01-relevant-log.txt').write_text('Imported textured GLB at22:03:07 in0.05s.\nTraceback: inspect_wholehood01_mask.py, line8 (basecolorimage lookup)\nStopIteration\nBlender5.2.1 LTS quit; processcode0doesnotmeanPythonrecipepassed.\nThis file is a relevant diagnostic transcription from actual tooloutput, not a complete bytecapture.\n')
(OUT/'README.md').write_text('# NEW wholehood01 trial01 — setupfailure1, unaccepted\n\nMaterialimage lookup raised StopIteration before clothclassification/extraction/output or receiver changes. The image-name heuristic was wrong. Exact failedrecipe copy/SHA and diagnostic transcription are frozen. Source3donorfiles/currentbody/nativesizinghead rehashunchanged; highresolutionraw retained untouched.\n\nSpecific next correction: traverse actual Principled BaseColor socket link to image, recordprovenance, then inspectselectedhood withoutblindcuts. Parentcheckpoint requiredbefore correction. Original03:00:58→03:30:58CPU2threadboundcontinues; no timerreset. Old15hoodrepairfailuresremainretired.\n')
(OUT/'setup01-freeze-manifest.json').write_text(json.dumps({'freezeUTC':report['freezeUTC'],'files':{p.name:sha(p) for p in sorted(OUT.iterdir()) if p.is_file()}},indent=2)+'\n');print(json.dumps(report,indent=2))
