"""Freeze parent-rejected gray tongue and retire old agent with exact provenance."""
from pathlib import Path
import json,hashlib,datetime,numpy as np
from PIL import Image,ImageDraw,ImageFont
B=Path('/Users/raynos/projects/games/rockhop');O=B/'docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02';R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');A=B/'assets/blender/hero-remaster/rider/one-rider-v2/autonomous-lanes/C-garment-pattern';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert not (O/'freeze-manifest.json').exists()
font=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',18);small=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',14);board=Image.new('RGB',(1600,1000),(24,24,24));draw=ImageDraw.Draw(board);draw.text((8,8),'UNACCEPTED anatomical donor01 isolation: natural cowl/bag, gray tongue remains',font=font,fill=(255,190,70));draw.text((8,35),'Actual GLB reimport; no color selection; source UVs kept. Parent rejects visible ambiguous inner tongue.',font=small,fill='white')
for row,mode in enumerate(['pbr','gray']):
 for col,view in enumerate(['front','profile','rear','three-quarter']):
  x=col*400;y=70+row*450;draw.text((x+8,y),f'{mode} {view}',font=font,fill='white');im=Image.open(O/f'isolated-{mode}-hood-{view}.png').convert('RGB').resize((400,400),Image.Resampling.LANCZOS);board.paste(im,(x,y+28))
board.save(O/'anatomical-isolation-board.jpg',quality=94)
clip=json.loads((O/'anatomical-clip-report.json').read_text());rays=json.loads((O/'gray-tongue-ray-provenance.json').read_text());core=[s for s in rays['samples'] if 336<=s['pixel'][0]<=363 and 238<=s['pixel'][1]<=247];coreids=sorted(set(s['originalSourceTriangle'] for s in core));q=np.array([s['hitXYZ'] for s in core]);sources=[Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/hunyuan21/01')/n for n in ['working-display2.glb','raw-shape.glb','raw-shape.npz']];sources += [Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/glove-cleanup/glove-material/isolated-correction01/bodyPBR.blend'),Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/head-cleanup/mpfb-v8-palette/african/head.blend')];expected=json.loads((O.parent/'wholehood01-trial01/unsafe-mask-report.json').read_text())['sourceAfterSHA256'];after={str(p):sha(p) for p in sources};assert expected==after
rep={'status':'FAILED visible ambiguous gray inner tongue; no binding/assembly; parent alone judges','actualStartUTC':clip['actualStartUTC'],'deadlineUTC':clip['deadlineUTC'],'freezeUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'parentActualReview':'NEWhood01 natural bag/cowl much better, but upper inner front gray tongue/oldskin-or-hair contamination remains visible. Freeze without repair/binding.','newDonorFailuresRetained':{'materialLookupSetup':1,'colorThresholdSeparation':1,'anatomicalGrayTongueIsolation':1},'retiredOldH21_4NeckRepairFailures':15,'sourceGeometryProtected':{'uncutOriginalDonorTriangles':clip['exactUncutSourceTriangles'],'positionMaxDelta':0,'UVExact':True,'retainedTriangles':4096,'components':1,'nonmanifoldEdges':0,'openBoundaryEdges':522,'receiverBodyNeverLoaded':True,'entireBodySHAUnchanged':True,'plannedReceiverProtectedTriangles':40386},'grayTongueProvenance':{'frontRenderCorePixelRegion':[336,238,363,247],'coreSourceTriangleIDs':coreids,'coreWorldXYZMin':q.min(0).tolist(),'coreWorldXYZMax':q.max(0).tolist(),'all39SourceFaceIDsAnd168Samples':'gray-tongue-ray-provenance.json','actualAtlasImage':rays['baseColorTexture'],'sampleWitness':next(s for s in core if s['pixel']==[345,244]),'anatomicalRelationship':'Ray-hit patch is at source rear inner surface Y+.144–.156m,Z1.535–1.543m, behind the lower central neck witness Y-.068→-.040m. This coordinate relationship identifies exact source location but does NOT prove skin/lining identity. Native atlas and PBR shading provenance remain unmodified. Never quietly recolor or call it accepted lining.'},'sourceSHAAfter':after,'allSourcesUnchanged':after==expected,'runtimeMaster':str(R/'anatomical-source-hood.blend'),'runtimeGLB':str(R/'anatomical-source-hood.glb'),'masterSHA':sha(R/'anatomical-source-hood.blend'),'GLBSHA':sha(R/'anatomical-source-hood.glb'),'grayTongueCrop':'gray-tongue-pixel-witness.png: exact front render pixels280..399,205..269 scaled6x; no painting','noBindingOrWholeBodyOutput':'Wholebody views were not fabricated: source-only defect prevented body assembly. No rig, material bake, head integration or contact claim.','agentRetirement':'Lifetime response total cannot be verified after inherited compactions. Per parent retire conservatively after this frozen trial; no lifetime/defect reset, next refinement assigned fresh agent.','recipes':{p.name:sha(p) for p in [A/'clip_anatomical_wholehood01.py',A/'render_anatomical_hood01.py',A/'audit_gray_tongue_hood01.py',Path(__file__)]}}
(O/'final-report.json').write_text(json.dumps(rep,indent=2)+'\n');(O/'README.md').write_text('''# NEW donor01 anatomical isolation — gray tongue rejected, frozen

Actual GLB reimport PBR/gray front/profile/rear/quarter shows a substantially better cowl and rear bag. Parent rejects the gray tongue inside the upper front opening. No binding, body assembly or further geometry correction follows this finding. Entire existing body/native sizing head and all donor raw/reduced sources remain byte-identical. The old H21-04 reduced cut/strip/lining lineage remains retired at15failures.

`anatomical-isolation-board.jpg` shows actual8views. `anatomical-clip-report.json` declares measured rearcloth/lower-neck source witnesses and the authored Z-varying ellipse plus true36-step edge intersections; no color criterion. Native source UVs interpolate only inside the original triangle chart.4096triangles retain3313 exact uncut original triangle positions/UVs. One connected component,0nonmanifold,522openedges are diagnostics, not acceptance.

`gray-tongue-ray-provenance.json` maps168actualcamera rays to39 original sourcefaceIDs, barycentricUVs, sourceXYZ and actual atlas texels. Core gray tongue has exact IDs/world bounds/sample in `final-report.json`. The patch is on a source rear inner surface (Y+.144–.156m,Z1.535–1.543m), behind lower central neck witness Y-.068→-.040m. This location is not proof of cloth/skin identity. No quiet recolor or accepted-lining claim. `gray-tongue-pixel-witness.png` is a6x crop of actual rendered pixels, unpainted.

Original316248triangle raw shape remains untouched; current prototype uses55k nativeUV/PBR source. No reliable highresolution raw texture transfer claimed. Wholebody views/rig/contact tests were not fabricated: unsafe source-only tongue prevents integration. Current body40386protected receivertriangles recognized, but receiver was not loaded/cut. CPU2 sharedBlender5.2.1 withisolatedCconfiguration, noGPU. Fresh03:38:33→04:08:33UTCbound; actualfreeze inmanifest.

Agent retirement: lifetime response count cannot be verified after inherited compactions. Parent requested conservative retirement after this frozen trial. Next refinement gets a fresh agent; source/defect histories remain preserved.
''')
(O/'RETIREMENT-HANDOFF.md').write_text('''# Retired agent handoff — do not resume old source repair

- Parent owns next refinement. This agent retires after this frozen anatomical trial because lifetime response total cannot be verified. No counter/history reset.
- Current best body remains `.../glove-cleanup/glove-material/isolated-correction01/bodyPBR.blend`, SHA952c4ed7fb5f3d82ccdce4c606535e5c347076e1cbdd41f87bc7d31eaac3f1c5. Source body40386protected receivertriangles, black neutral gloves, legs/shoes/drawstrings unchanged. No new wholebody or binding output exists.
- NEW donor01 original `.../hunyuan21/01/working-display2.glb` SHA783b58fec94aa9657dc44bed14d4767af610bfa29b336f916d5107118a01d5cb. Untouched rawGLB42b23ca04f82728299caca26e958996e8ffaeb8fc491d2e77b1983ef4880e0c2/rawNPZe4580ff1b95af69c0cfe4273f34913950ae284ab32d4d38254cfbd5f55e6055d (158114vertices316248triangles).
- NEW donor failure history:1image-lookup setup failure,1unsafe color-mask separation,1anatomical visible gray-tongue isolation. Color-threshold technique stopped. Old H21-04 neck-cut/strip/lining repair is permanently retired after15failures, no attempt16.
- Source-only anatomical master/runtimeGLB/exacttriangleUVNPZ are under `.../C-garment-pattern/wholehood01-anatomical-trial02/`. Unaccepted, parent reviews. All8actualviews are reimportedGLB. Do not bind or recolor the gray tongue silently.
- Next source investigation has exact front graytongue camera rays/39 original sourcefaceIDs/texel provenance. Core sourcefaces sample28422 at pixel345,244 maps sourceXYZ(.01992,.15077,1.53811), UV-derived nativepixel(1289,1831), RGBA(.23137,.10196,.06667,1). More sourceIDs/sample coordinates inprovenanceJSON. Anatomical rearposition alone does not decide lining vs oldskin/hair.
- Measured wholehood rearcloth maxZ1.577023, maxY.181029. Trueclipcap1.585023, varyingellipse parameters fully declared;3313unchanged trianglesUV/geometry exact,4096total,522openedges. No broad/global reducer; no source mutation. Future cut changes require a NEW experiment/checkpoint and actual4view inspection before binding.
- Receiver alternative is Bcleanconstruction new307body-yoke boundary `.../B-local-volume/clean-construction/trial01/fresh-wholehood-exclusion.npz` and nativebody-sourceNPZ; never retired142/194/43/23collar loops. Retain40386original protected triangleUV/material/nativeweights and exact bodySHA.
- Currentnativeheadgray anatomy is sizingcontrolonly; human WHITE freshH21buzz head cleanup belongs to parent/A. Never promote nativepalette as finished identity. No player/physics/bike changes permitted by this donor task.
''')
files={str(p.relative_to(O)):sha(p) for p in sorted(O.rglob('*')) if p.is_file()};(O/'freeze-manifest.json').write_text(json.dumps({'freezeUTC':rep['freezeUTC'],'sourceHashesUnchanged':True,'files':files},indent=2)+'\n');print(json.dumps(rep,indent=2))
