"""Source-only true-clipped hood nativePBR/gray; inspect before integration."""
import bpy,numpy as np,json,hashlib,datetime,math
from pathlib import Path
from mathutils import Vector
R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');O=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');D=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/hunyuan21/01/working-display2.glb');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();before=sha(D)
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(D));obj=next(o for o in bpy.context.scene.objects if o.type=='MESH');material=obj.data.materials[0];d=np.load(R/'true-clipped-hood.npz');mesh=bpy.data.meshes.new('NEW donor01 anatomical true-clipped wholehood');mesh.from_pydata(d['vertices'].tolist(),[],d['faces'].tolist());mesh.update();mesh.materials.append(material);u=mesh.uv_layers.new(name='NativeDonorSourceUV')
for p,uv in zip(mesh.polygons,d['uv']):
 p.material_index=0;p.use_smooth=True
 for li,co in zip(p.loop_indices,uv):u.data[li].uv=co
obj.data=mesh;obj.parent=None;obj.matrix_world.identity();obj.name='UNACCEPTED NEW donor01 hood anatomical source-only';bpy.ops.object.select_all(action='DESELECT');obj.select_set(True);bpy.context.view_layer.objects.active=obj;bpy.ops.wm.save_as_mainfile(filepath=str(R/'anatomical-source-hood.blend'));bpy.ops.export_scene.gltf(filepath=str(R/'anatomical-source-hood.glb'),export_format='GLB',use_selection=True,export_yup=True,export_animations=False,export_apply=False,export_materials='EXPORT',export_texcoords=True,export_normals=True)
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(R/'anatomical-source-hood.glb'));scene=bpy.context.scene;objects=[o for o in scene.objects if o.type=='MESH'];report={'status':'UNACCEPTED actual GLB reimport source-only hood','sourceSHA':before,'sourceSHAAfter':sha(D),'sourceUntouched':before==sha(D),'GLBSHA':sha(R/'anatomical-source-hood.glb'),'masterSHA':sha(R/'anatomical-source-hood.blend'),'actualImportedObjects':[{'name':o.name,'vertices':len(o.data.vertices),'faces':len(o.data.polygons),'UVLayers':[u.name for u in o.data.uv_layers],'materialSlots':[m.name for m in o.data.materials]} for o in objects],'views':[]}
world=bpy.data.worlds.new('Matched source studio');world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.16,.16,.16,1);world.node_tree.nodes['Background'].inputs[1].default_value=.65;scene.world=world
for name,pos,power in [('Key',(3,-4,4),600),('Fill',(-3,-2,2.5),350),('Rim',(1,3,3),450)]:
 ld=bpy.data.lights.new(name,'AREA');ld.energy=power;ld.shape='DISK';ld.size=4;o=bpy.data.objects.new(name,ld);scene.collection.objects.link(o);o.location=pos;o.rotation_euler=(Vector((0,0,1.46))-o.location).to_track_quat('-Z','Y').to_euler()
gray=bpy.data.materials.new('Matched neutral gray');gray.use_nodes=True;p=gray.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(.42,.42,.42,1);p.inputs['Roughness'].default_value=.65;cd=bpy.data.cameras.new('Anatomical source-only hood');cam=bpy.data.objects.new(cd.name,cd);scene.collection.objects.link(cam);scene.camera=cam;cd.type='ORTHO';cd.ortho_scale=.50;scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=16;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=scene.render.resolution_y=640;scene.render.resolution_percentage=100;scene.view_settings.view_transform='AgX';scene.render.image_settings.file_format='PNG'
for mode in ['pbr','gray']:
 for name,yaw in [('front',0),('profile',90),('rear',180),('three-quarter',45)]:
  target=Vector((0,.010,1.48));a=math.radians(yaw);cam.location=target+Vector((4*math.sin(a),-4*math.cos(a),.025));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();scene.view_layers[0].material_override=gray if mode=='gray' else None;p=O/f'isolated-{mode}-hood-{name}.png';assert not p.exists();scene.render.filepath=str(p);bpy.ops.render.render(write_still=True);report['views'].append({'path':str(p),'SHA':sha(p),'yaw':yaw,'mode':mode})
report['finishedUTC']=datetime.datetime.now(datetime.timezone.utc).isoformat();report['recipeSHA']=sha(__file__);(O/'isolated-render-report.json').write_text(json.dumps(report,indent=2)+'\n')
