"""Read-only exact pixel350,246 and original full-source profile witness."""
import bpy,numpy as np,json,math,hashlib,datetime
from pathlib import Path
from mathutils import Vector,Matrix
B=Path('/Users/raynos/projects/games/rockhop');O=B/'docs/evidence/hero-remaster/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02';R=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/autonomous-lanes/C-garment-pattern/wholehood01-anatomical-trial02');D=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/hunyuan21/01/working-display2.glb');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();before=sha(D)
bpy.ops.wm.open_mainfile(filepath=str(R/'anatomical-source-hood.blend'));obj=next(o for o in bpy.context.scene.objects if o.type=='MESH');d=np.load(R/'true-clipped-hood.npz');src=np.load(R.parent/'wholehood01-trial01/donor-source.npz');target=Vector((0,.010,1.48));cloc=target+Vector((0,-4,.025));rot=(target-cloc).to_track_quat('-Z','Y').to_matrix();px,py=350,246;origin=cloc+(rot@Vector((1,0,0)))*((px+.5)/640-.5)*.5+(rot@Vector((0,1,0)))*(.5-(py+.5)/640)*.5;hit,co,normal,idx=obj.ray_cast(origin,rot@Vector((0,0,-1)));assert hit;sid=int(d['sourceFaceOrigins'][idx]);vs=d['vertices'][d['faces'][idx]];a=vs[1]-vs[0];b=vs[2]-vs[0];c=np.array(co)-vs[0];ab=np.linalg.solve([[a@a,a@b],[a@b,b@b]],[c@a,c@b]);bary=np.array([1-ab.sum(),*ab]);uv=bary@d['uv'][idx];mat=obj.data.materials[0];bs=next(n for n in mat.node_tree.nodes if n.type=='BSDF_PRINCIPLED');img=bs.inputs['Base Color'].links[0].from_node.image;W,H=img.size;pixels=np.array(img.pixels[:]).reshape(H,W,4);tx=int(uv[0]*W)%W;ty=int(uv[1]*H)%H;tex=pixels[ty,tx].tolist();tri=src['vertices'][src['faces'][sid]]
report={'status':'Read-only same-finding exact graytongue center/source profile witness; no repair','frontPixel':[px,py],'derivedTriangle':int(idx),'originalSourceTriangle':sid,'XYZ':list(co),'barycentric':bary.tolist(),'nativeUV':uv.tolist(),'atlasPixelBottomUp':[tx,ty],'atlasPixelRGBA':tex,'atlasImageName':img.name,'originalTriangleXYZ':tri.tolist(),'sourceSHA':before,'attribution':'Anatomical attribution unaccepted. Source-profile highlight locates exact originalface and center relative to original hood/head; color/position alone does not prove skin or lining.','recipeSHA':sha(__file__),'views':[]}
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(D));scene=bpy.context.scene;o=next(o for o in scene.objects if o.type=='MESH');norm=json.loads((O.parent/'whole-hood-donor-comparison/manifest.json').read_text())['candidates']['01']['normalization'];world=Matrix(norm['canonicalMatrix'])@o.matrix_world;o.parent=None;o.matrix_world=world
red=bpy.data.materials.new('DIAGNOSTIC ONLY exact sourceface red marker');red.use_nodes=True;pr=red.node_tree.nodes.get('Principled BSDF');pr.inputs['Base Color'].default_value=(1,.005,.005,1);pr.inputs['Roughness'].default_value=.45;pr.inputs['Emission Color'].default_value=(1,.005,.005,1);pr.inputs['Emission Strength'].default_value=2
# Diagnostic marker object only, offset0.5mm toward profilecamera; originalsource mesh/material arrays stay unchanged.
edge=bpy.data.curves.new('Exact originalface outline','CURVE');edge.dimensions='3D';edge.bevel_depth=.0012;sp=edge.splines.new('POLY');sp.points.add(3)
for pt,p in zip(sp.points,list(tri)+[tri[0]]):pt.co=(*((p+np.array([.0005,0,0])).tolist()),1)
mo=bpy.data.objects.new('SOURCE FACE '+str(sid)+' diagnostic outline',edge);scene.collection.objects.link(mo);edge.materials.append(red);bpy.ops.mesh.primitive_uv_sphere_add(segments=12,ring_count=6,radius=.0035,location=co);marker=bpy.context.object;marker.name='SOURCE exact pixel350,246 center';marker.data.materials.append(red)
worldb=bpy.data.worlds.new('Matched source studio');worldb.use_nodes=True;worldb.node_tree.nodes['Background'].inputs[0].default_value=(.16,.16,.16,1);worldb.node_tree.nodes['Background'].inputs[1].default_value=.65;scene.world=worldb
for name,pos,power in [('Key',(3,-4,4),600),('Fill',(-3,-2,2.5),350),('Rim',(1,3,3),450)]:
 l=bpy.data.lights.new(name,'AREA');l.energy=power;l.shape='DISK';l.size=4;z=bpy.data.objects.new(name,l);scene.collection.objects.link(z);z.location=pos;z.rotation_euler=(Vector((0,0,1.46))-z.location).to_track_quat('-Z','Y').to_euler()
camd=bpy.data.cameras.new('Actual source profile');cam=bpy.data.objects.new(camd.name,camd);scene.collection.objects.link(cam);scene.camera=cam;camd.type='ORTHO';camd.ortho_scale=.66;scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=16;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=scene.render.resolution_y=800;scene.render.resolution_percentage=100;scene.view_settings.view_transform='AgX';scene.render.image_settings.file_format='PNG'
for name,yaw in [('profile',90),('three-quarter',45)]:
 t=Vector((0,.010,1.50));angle=math.radians(yaw);cam.location=t+Vector((4*math.sin(angle),-4*math.cos(angle),.025));cam.rotation_euler=(t-cam.location).to_track_quat('-Z','Y').to_euler();out=O/f'original-source-graytongue-witness-{name}.png';assert not out.exists();scene.render.filepath=str(out);bpy.ops.render.render(write_still=True);report['views'].append({'path':str(out),'SHA':sha(out),'marker':'Exact sourceface outline and3.5mm diagnostic center; sourceUV/PBR untouched. Occlusion remains physically honest.'})
report['sourceSHAAfter']=sha(D);assert report['sourceSHAAfter']==before;report['finishedUTC']=datetime.datetime.now(datetime.timezone.utc).isoformat();(O/'tongue-center-source-witness.json').write_text(json.dumps(report,indent=2)+'\n');print('Exact center:',sid,list(co),uv.tolist(),[tx,ty],tex,flush=True)
