"""Read-only archived surface queries and effective skin; no pose or evaluation."""
import bpy,numpy as np,json,hashlib
from pathlib import Path
from mathutils.bvhtree import BVHTree
out=Path(__file__).resolve().parent;qa=out.parent;root=Path.cwd();ev=root/'docs/evidence/hero-remaster/anatomical-foundation-2026-10-03/user-agent1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();prep=json.loads((qa/'hand82/preparation.json').read_text());n=np.load(ev/'hand-grip104/source-fields.npz');f=np.load(ev/'hand-grip106/candidate-fields.npz');w=np.load(ev/'hand-grip107/decoder-recheck/native-replay-witnesses.npz');initial=np.load(ev/'hand-grip107/native-replay-witnesses.npz');owner=json.loads((ev/'hand-grip107/decoder-recheck/measurements.json').read_text());seed=json.loads((ev/'hand-grip107/decoder-recheck/first-physical-seed.json').read_text());author=json.loads((ev/'hand-grip106/authoring.json').read_text());names=n['boneNames'].tolist();gt=n['gloveTriangles'];finite=json.loads((qa/'grip74/finite-grips.json').read_text())['bikes'][0];grips={g['side']:g for g in finite['grips']};scope=json.loads((ev/'hand-grip104/scope.json').read_text());allowed=[names.index(s) for s in scope['scope']['weightBoneNames']];driver=json.loads((ev/'hand-grip105/actual-driver.json').read_text());rows=[]
for case in driver['cases']:
 data=json.loads((root/case['file']).read_text());assert sha(root/case['file'])==case['sha256']
 for row in data['samples']:rows.append((case['id'],row))
assert len(rows)==1065 and set(w.files)==set(initial.files)
for key in w.files:assert np.array_equal(w[key],initial[key]),key
for i,(case,row) in enumerate(rows):
 assert str(w['caseIDs'][i])==case and int(w['inputTicks'][i])==row['inputTick'] and str(w['phases'][i])==row['phase'];assert np.array_equal(w['observedControlBikeFrameWorld'][i],np.array(row['observation']['bikeFrameWorld']).reshape(4,4).T)
qt=(qa/'grip74/measure-grip.py').read_text();env={'np':np};exec(compile(qt[qt.index('def point_query('):qt.index('# Native rest ancestry:')],'independent-finite-point-query','exec'),env);query=env['point_query'];pt=(qa/'neck77/read-endpoints-normals.py').read_text();exec(compile(pt[pt.index('def proper('):pt.index('families=')],'independent-proper-crossing','exec'),env);proper=env['proper'];unit=lambda v:v/np.linalg.norm(v)
# Independently recompute first-seed finite surface and complete proper pairs.
physical={};pairarchive={}
for label,key in [('full','firstFullGloveBikeFrameXYZ'),('four','firstFourGloveBikeFrameXYZ'),('immutableNative26OnSource37ControlDriver','firstControlGloveBikeFrameXYZ')]:
 P=w[key];gv=BVHTree.FromPolygons(P.tolist(),gt.tolist(),all_triangles=True,epsilon=0.);physical[label]={};pairarchive[label]={}
 for side,g in grips.items():
  columns=[j for j,s in enumerate(names) if s.endswith('.'+side) and (s.startswith('hand.') or '_' in s)];other=[j for j,s in enumerate(names) if s.endswith('.'+('R' if side=='L' else 'L')) and (s.startswith('hand.') or '_' in s)];ids=np.flatnonzero(f['fullWeights'][:,columns].sum(1)>f['fullWeights'][:,other].sum(1));tri=np.array(g['trianglesBikeFrame']);d,inside,choose,near=query(P[ids],tri);depth=np.where(inside,d,0);iw=int(depth.argmax());gb=BVHTree.FromPolygons(tri.reshape(-1,3).tolist(),np.arange(len(tri)*3).reshape(-1,3).tolist(),all_triangles=True,epsilon=0.);pairs=sorted([[int(i),int(g['sourceTriangleOrdinals'][j])] for i,j in gv.overlap(gb) if proper(P[gt[i]],tri[j])]);receipt=seed['fields'][label][side];assert int(inside.sum())==receipt['insideVertices'];assert abs(float(depth.max()*1000)-receipt['maximumVertexPenetrationMm'])<1e-9;assert int(ids[iw])==receipt['deepestVertex']['nativeID'];assert pairs==sorted(receipt['properGloveGripTrianglePairs']);pairarchive[label][side]=pairs
  points={}
  for name,point in [('palm',receipt['actualPalmSurfaceWitness'])]+list(receipt['fingerSurfaceWitnesses'].items()):
   p=np.array(point['barycentric'])@P[point['nativeIDs']];dd,inn,wh,nn=query([p],tri);assert np.linalg.norm(p-point['pointBikeFrameM'])<1e-12;assert abs(dd[0]*1000-point['finiteDistanceMm'])<1e-9;assert int(g['sourceTriangleOrdinals'][wh[0]])==point['nearestSourceGripTriangleOrdinal'];assert bool(inn[0])==point['inside'];points[name]={'gloveTriangleID':point['sourceGloveTriangleID'],'nativeIDs':point['nativeIDs'],'barycentric':point['barycentric'],'finiteGapMm':float(dd[0]*1000),'inside':bool(inn[0]),'nearestSourceGripTriangleOrdinal':int(g['sourceTriangleOrdinals'][wh[0]])}
  physical[label][side]={'insideVertices':int(inside.sum()),'maximumPenetrationMm':float(depth.max()*1000),'deepestNativeID':int(ids[iw]),'deepestSourceGripTriangleOrdinal':int(g['sourceTriangleOrdinals'][choose[iw]]),'properCrossings':len(pairs),'surfaceWitnesses':points}
# Normalize independently; archived native matrices only, never assign bone poses.
C=np.array([[1,0,0,0],[0,0,1,0],[0,-1,0,0],[0,0,0,1]],float);H=np.column_stack([n['gloveXYZ'],np.ones(len(gt)*0+len(n['gloveXYZ']))])@(C@n['gloveWorld']).T;rest=f['rigRestFile'];K=w['nativeCandidateBoneFileWorld']@np.linalg.inv(rest);B=w['observedControlBikeFrameWorld'];weights={s:f[s+'Weights'].astype(float) for s in ['full','four']}
for v in weights.values():v/=v.sum(1)[:,None]
def skin(ww,kk,hh):return np.einsum('vj,jab,vb->va',ww,kk,hh)[:,:3]
first={s:(np.column_stack([skin(v,K[0],H),np.ones(len(H))])@np.linalg.inv(B[0]).T)[:,:3] for s,v in weights.items()};firstParity={s:float(np.linalg.norm(first[s]-w['first'+s.title()+'GloveBikeFrameXYZ'],axis=1).max()) for s in first};assert max(firstParity.values())<4e-7
change=weights['full']-weights['four'];changed=np.flatnonzero((change!=0).any(1));diff=np.einsum('vj,njab,vb->nva',change[changed],K,H[changed])[:,:,:3];delta=np.linalg.norm(diff,axis=2);manualmax=delta.max(1);ids=changed[delta.argmax(1)];receipted=np.array([r['maximumMm']/1000 for r in owner['fullFourLossByObservation']]);imax=int(manualmax.argmax());lossResidual=float(np.abs(manualmax-receipted).max());assert lossResidual<1e-6 and int(ids[imax])==owner['maximumFullFourWitness']['nativeVertexID'];assert int(w['inputTicks'][imax])==owner['maximumFullFourWitness']['inputTick']
wrist=[]
for i,(case,row) in enumerate(rows):
 angles={s:float(np.degrees(np.arccos(np.clip(unit(w['nativeCandidateBoneFileWorld'][i,names.index('forearm.'+s),:3,1])@unit(w['nativeCandidateBoneFileWorld'][i,names.index('hand.'+s),:3,1]),-1,1)))) for s in ['L','R']};assert max(abs(angles[s]-owner['wristAxisByObservation'][i]['anglesDeg'][s]) for s in angles)<1e-10;wrist.append({'case':case,'inputTick':row['inputTick'],'phase':row['phase'],'anglesDeg':angles})
phaseSummary={}
for phase in ['riding','crashed']:
 rr=[r for r in wrist if r['phase']==phase];phaseSummary[phase]={'observations':len(rr),'sides':{}}
 for s in ['L','R']:
  minimum=min(rr,key=lambda r:r['anglesDeg'][s]);maximum=max(rr,key=lambda r:r['anglesDeg'][s]);phaseSummary[phase]['sides'][s]={'minimumDeg':minimum['anglesDeg'][s],'maximumDeg':maximum['anglesDeg'][s],'maximumWitness':{k:maximum[k] for k in ['case','inputTick','phase']}}
# The rest palm is mapped by the rigid hand. Compare that with actual skin.
anchor={}
for side in ['L','R']:
 p=author['palms'][side];target=np.array(seed['authoredTargets'][side]['targetBikeFrameM']);actual=np.array(p['barycentric'])@w['firstFullGloveBikeFrameXYZ'][p['nativeVertexIDs']];j=names.index('hand.'+side);restpoint=np.r_[p['sourcePointFileWorldM'],1.];rigid=(np.linalg.inv(B[0])@K[0,j]@restpoint)[:3];anchor[side]={'sourceTriangleID':p['sourceGloveTriangleID'],'nativeIDs':p['nativeVertexIDs'],'barycentric':p['barycentric'],'normalizedMembershipsByCorner':[{names[k]:float(weights['full'][i,k]) for k in np.flatnonzero(weights['full'][i])} for i in p['nativeVertexIDs']],'actualSkinnedPointVsTargetMm':float(np.linalg.norm(actual-target)*1000),'rigidHandRestPointVsTargetMm':float(np.linalg.norm(rigid-target)*1000),'actualSkinVsRigidHandRestPointMm':float(np.linalg.norm(actual-rigid)*1000),'actualSkinBikeFrameM':actual.tolist(),'rigidHandRestPointBikeFrameM':rigid.tolist(),'targetBikeFrameM':target.tolist()}
body={}
for s,g in grips.items():
 dd,inn,wh,nn=query(w['firstBodyHandBikeFrameXYZ'],np.array(g['trianglesBikeFrame']));depth=np.where(inn,dd,0);i=int(depth.argmax());r=seed['underlyingImmutableCanonicalHandOnCandidateBones'][s];assert int(inn.sum())==r['insideVertices'] and abs(depth.max()*1000-r['maximumPenetrationMm'])<1e-9 and int(w['bodyHandNativeIDs'][i])==r['worstNativeBodyID'];body[s]={'insideVertices':int(inn.sum()),'maximumPenetrationMm':float(depth.max()*1000),'worstNativeBodyID':int(w['bodyHandNativeIDs'][i])}
for p,h in prep['pins'].items():assert sha(root/p)==h['sha256'],p
r={'status':'READ_ONLY_FIRST_PHYSICAL_FAILURE_AND_MOTION_WITNESSES_REPRODUCED','recipeSHA256':sha(__file__),'initialVsRecheckArchivedArraysAllExact':True,'all1065CaseTickPhaseAndActualBikeMatrixRecordsExact':True,'physicalSeed':physical,'bodyHandMaskSeed':body,'palmRestAnchorVsActualSkin':anchor,'firstNormalizedManualVsArchivedNativeMaximumM':firstParity,'fullFourManualLoss':{'changedNativeRows':len(changed),'maximumMm':float(manualmax[imax]*1000),'maximumReceiptResidualMm':lossResidual*1000,'nativeVertexID':int(ids[imax]),'case':str(w['caseIDs'][imax]),'inputTick':int(w['inputTicks'][imax]),'notFullNativeParityProof':True},'wristProxyByPhase':phaseSummary,'ownerNormalizedNativeParityMaximumM':owner['nativeEvaluationVsNormalizedLinearSkinMaximumM'],'pinsUnchangedAfter':True,'limits':['No native mesh per observation beyond first seed is archived; all-frame normalized parity maximum is a pinned owner receipt, not independently reproduced from bone matrices. First-seed parity and independent manual full/four loss do not close it.','All proper-crossing pairs, deepest vertices, actual palm and selected finger points independently queried only at archived first seed. Subsequent contact/CCD, closed wrap, physical segmentation and appearance remain unqualified.','Wrist proxy is longitudinal bone-axis angle; not a medical angle or art judgment. Pose recipe applies identical contact construction during crash with no release/reacquisition phase condition.','No source, geometry, weight, normal, pose edit, solve, sweep, native evaluation, new candidate, capture/render/export or admission.']};(out/'contact-motion.json').write_text(json.dumps(r,indent=2)+'\n');(out/'first-proper-pairs.json').write_text(json.dumps(pairarchive)+'\n');print('ALL_FIRST_SURFACE_WITNESSES_AND_PAIRS_EXACT',firstParity,'MANUAL_FULL_FOUR_LOSS',r['fullFourManualLoss'],'WRIST',phaseSummary,flush=True)
