"""Independent conservation and fixed-curve verifier; no model or source edits."""
from pathlib import Path
import copy,hashlib,io,json,struct
import numpy as np
from PIL import Image
from scipy.ndimage import label
np.seterr(all='raise')
ROOT=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/rig-adapter01');SOURCE=ROOT/'body-bind22/skin-field01/rider.glb';RUN=ROOT/'body-bind28/iris-albedo01';OUT=Path('docs/evidence/hero-remaster/one-rider-v2/rig-adapter01/body-bind28')
def sha(b):return hashlib.sha256(b).hexdigest()
def glb(p):
 raw=p.read_bytes();n=struct.unpack_from('<I',raw,12)[0];assert struct.unpack_from('<III',raw,0)==(0x46546c67,2,len(raw));assert struct.unpack_from('<I',raw,16)[0]==0x4e4f534a;assert struct.unpack_from('<I',raw,24+n)[0]==0x004e4942;return raw,json.loads(raw[20:20+n]),raw[28+n:]
def atlas(doc,b,primitive):
 m=doc['materials'][doc['meshes'][1]['primitives'][primitive]['material']];tex=doc['textures'][m['pbrMetallicRoughness']['baseColorTexture']['index']];v=doc['bufferViews'][doc['images'][tex['source']]['bufferView']];raw=b[v.get('byteOffset',0):v.get('byteOffset',0)+v['byteLength']];return np.array(Image.open(io.BytesIO(raw)).convert('RGBA')),raw
oldRaw,old,oldBIN=glb(SOURCE);newRaw,new,newBIN=glb(RUN/'rider.glb');report=json.loads((OUT/'build-report.json').read_text());assert sha(oldRaw)=='cc20ab813669b628c8e5d21596b655188d7188770adc374377cebf40769232ff';assert sha(newRaw)==report['candidateSHA256'];assert newBIN[:len(oldBIN)]==oldBIN;assert new['accessors']==old['accessors'];assert len(new['skins'][0]['joints'])==19
for key in ['bufferViews','images','textures','materials']:assert len(new[key])==len(old[key])+1 and new[key][:-1]==old[key]
expected=copy.deepcopy(old['meshes']);expected[1]['primitives'][4]['material']=len(old['materials']);expected[1]['primitives'][6]['material']=len(old['materials']);assert new['meshes']==expected
restored=copy.deepcopy(new)
for key in ['bufferViews','images','textures','materials']:restored[key]=restored[key][:-1]
restored['meshes']=old['meshes'];restored['buffers']=old['buffers'];assert restored==old,'Undeclared original JSON mutation'
material=copy.deepcopy(old['materials'][6]);material['name']='CC0 eye with fixed iris-annulus albedo28';material['pbrMetallicRoughness']['baseColorTexture']['index']=len(old['textures']);assert new['materials'][-1]==material;assert material['pbrMetallicRoughness']['roughnessFactor']==.35;assert material['alphaMode']=='OPAQUE';texture=copy.deepcopy(old['textures'][old['materials'][6]['pbrMetallicRoughness']['baseColorTexture']['index']]);texture['source']=len(old['images']);assert new['textures'][-1]==texture
pixels,oldPNG=atlas(old,oldBIN,4);newPixels,newPNG=atlas(new,newBIN,4);assert np.array_equal(newPixels,atlas(new,newBIN,6)[0]);assert oldPNG==(RUN/'source-eye-atlas.png').read_bytes();assert newPNG==(RUN/'iris-brown-albedo.png').read_bytes();assert sha(oldPNG)==report['sourcePNG_SHA256'];assert sha(newPNG)==report['candidatePNG_SHA256'];assert np.array_equal(pixels[:,:,3],newPixels[:,:,3]);assert pixels.shape==newPixels.shape==(1024,1024,4)
proposal=json.loads((OUT.parent/'body-bind27/eye-appearance-audit.json').read_text());rgb=pixels[:,:,:3].astype(float)/255;linear=np.where(rgb<=.04045,rgb/12.92,((rgb+.055)/1.055)**2.4);Y=linear[:,:,0]*.2126+linear[:,:,1]*.7152+linear[:,:,2]*.0722;dark=(pixels[:,:,:3].max(2)<20)&(pixels[:,:,3]==255);labels,_=label(dark);pupil=np.isin(labels,[e['pupilAndIris']['pupilTextureComponent'] for e in proposal['eyes']]);yy,xx=np.indices(Y.shape);intent=np.array([.263,.155,.100]);intentLinear=np.where(intent<=.04045,intent/12.92,((intent+.055)/1.055)**2.4);weight=np.zeros(Y.shape);wanted=np.zeros_like(linear);domain=np.zeros(Y.shape,bool);statistics=[]
for eye in proposal['eyes']:
 cx,cy=eye['pupilAndIris']['pupilTextureCentre'];r=np.sqrt((xx-cx)**2+(yy-cy)**2);annulus=(r>=52)&(r<=110);eligible=annulus&~pupil&(pixels[:,:,3]==255);domain|=annulus;median=float(np.median(Y[eligible]));scale=(Y[eligible]/median)**.75;wanted[eligible]=scale[:,None]*intentLinear
 inner=np.clip((r-52)/6,0,1);outer=np.clip((110-r)/6,0,1);feather=(inner*inner*(3-2*inner))*(outer*outer*(3-2*outer));feather[~eligible]=0;weight+=feather;full=feather==1;newrgb=newPixels[:,:,:3].astype(float)/255;oldL=rgb[:,:,0]*.2126+rgb[:,:,1]*.7152+rgb[:,:,2]*.0722;newL=newrgb[:,:,0]*.2126+newrgb[:,:,1]*.7152+newrgb[:,:,2]*.0722
 statistics.append({'eye':eye['eye'],'pupilCentrePixels':[cx,cy],'annularSourceLinearYMedian':median,'fullyWeightedPixels':int(full.sum()),'fullyWeightedOldMedianEncodedRGB':np.median(rgb[full],axis=0).tolist(),'fullyWeightedNewMedianEncodedRGB':np.median(newrgb[full],axis=0).tolist(),'fullyWeightedEncodedLumaP10P50P90BeforeAfter':[np.quantile(oldL[full],[.1,.5,.9]).tolist(),np.quantile(newL[full],[.1,.5,.9]).tolist()],'sourceFibreScaleP0P50P100':np.quantile(scale,[0,.5,1]).tolist(),'originalPupilPixelsExact':bool(np.array_equal(pixels[labels==eye['pupilAndIris']['pupilTextureComponent']],newPixels[labels==eye['pupilAndIris']['pupilTextureComponent']]))})
active=weight>0;expectedPixels=pixels.copy();mapped=(1-weight[active,None])*linear[active]+weight[active,None]*wanted[active];assert mapped.min()>=0 and mapped.max()<1;encoded=np.where(mapped<=.0031308,mapped*12.92,1.055*np.maximum(mapped,1e-300)**(1/2.4)-.055);expectedPixels[active,:3]=np.floor(encoded*255+.5).astype(np.uint8);assert np.array_equal(newPixels,expectedPixels),'Frozen curve or mask differs';assert np.array_equal(pixels[~active],newPixels[~active]);assert np.array_equal(pixels[pupil],newPixels[pupil]);assert np.array_equal(pixels[~domain],newPixels[~domain]);sclera=(rgb.min(2)>.5)&(np.ptp(rgb,axis=2)<.15);assert not np.any(sclera&domain);assert np.array_equal(pixels[sclera],newPixels[sclera]);maskFile=RUN/'exact-mask.npz';assert sha(maskFile.read_bytes())==report['maskNPZ_SHA256'];mask=np.load(maskFile);assert np.array_equal(mask['active'],active);assert np.max(abs(mask['weight']-weight))<1e-13;assert np.array_equal(mask['pupilProtected'],pupil);assert np.array_equal(mask['scleraProtected'],sclera);assert SOURCE.read_bytes()==oldRaw;assert (RUN/'rider.glb').read_bytes()==newRaw
summary={'status':'PASS independent append-only conservation and fixed iris curve correspondence; appearance unaccepted','sourceSHA256':sha(oldRaw),'candidateSHA256':sha(newRaw),'originalBINPrefixExactBytes':len(oldBIN),'accessorListsAndGeometryUVNormalSkin19RigHeadHoodNeckExact':True,'allOriginalNodesSkinsAnimationsSamplersTexturesMaterialsExact':True,'onlyOriginalIndexChanges':'mesh1 opaque eye primitives4/6 material6→new appended material','originalHiddenCorneaPrimitiveMaterialsExact':True,'opaqueRoughness035AndAllOtherMaterialFactorsExact':True,'allProtectedOriginalPixelsAndAlphaExact':True,'pupilComponentsExactPixels':int(pupil.sum()),'brightScleraProtectedPixels':int(sclera.sum()),'outsideActivePixelsExactCount':int((~active).sum()),'activePixels':int(active.sum()),'changedRGBPixels':int(np.any(pixels[:,:,:3]!=newPixels[:,:,:3],axis=2).sum()),'maximumIndependentWeightReconstructionDifference':float(np.max(abs(mask['weight']-weight))),'targetLinearRGBClipping':False,'fixedFibreCurveReproducesEveryOutputPixel':True,'eyeAtlasOriginalAndCandidatePNG_SHA256':[sha(oldPNG),sha(newPNG)],'statistics':statistics,'limits':['CPU atlas conservation and declared intent only, no physical optical or moving visual grade.','Radial mask is the committed proposal, not an anatomical segmentation certificate.','Actual eyelid fit, gaze asymmetry, lighting and mip behavior remain for parent rendered judgment.']}
print(json.dumps(summary,indent=2))
