"""Selected read-only source contract witnesses; reuse pinned audited raw reader."""
from pathlib import Path
import ast,json,struct,hashlib,numpy as np
from scipy.spatial.transform import Rotation
R=Path('/Users/raynos/projects/games/rockhop');B=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2');O=R/'docs/evidence/hero-remaster/one-rider-v2/clean-upper-shell01/rig-contract179';S=B/'clean-upper-shell01/rig-contract179';records={};sha=lambda b:hashlib.sha256(b).hexdigest()
def pin(p,role):
 p=Path(p);b=p.read_bytes();records[str(p)]={'path':str(p),'SHA256':sha(b),'bytes':len(b),'role':role};return b
reader=R/'assets/blender/hero-remaster/rider/one-rider-v2/rig-foundation167/prepare.py';tree=ast.parse(pin(reader,'existing immutable raw GLB reader recipe').decode());cls=next(x for x in tree.body if isinstance(x,ast.ClassDef)and x.name=='GLB');env={'Path':Path,'json':json,'struct':struct,'np':np,'Rotation':Rotation,'sha':sha};exec(compile(ast.Module(body=[cls],type_ignores=[]),str(reader),'exec'),env);GLB=env['GLB']
C=GLB(Path('/Users/raynos/Documents/Codex/2026-10-01/task-3/deliverables/C19.glb'),'186d0f86ae62722689be3c194f7437f623799c837e7ba515358680db12a1382e');G=GLB(B/'rig-adapter01/body-bind34/rider.glb','adbac6f2949cec0f32a8e0cfa4cfabd02cce61e58dab4022209e23a605f31df7');pin(C.p,'actual raw new C19 source');pin(G.p,'actual mapped source34 source')
hand=R/'assets/blender/hero-remaster/rider/one-rider-v2/foundation-repair-task3/hoodie-repair02/shape-lane/volume-lane/source-embedding23';H=json.loads(pin(hand/'continuous-shell-handoff.json','external task3 handoff read before duplication'));pin(hand/'continuous-shell-source-maps.npz','external literal source maps');maps=np.load(hand/'continuous-shell-source-maps.npz');diagnosis=json.loads(pin(hand/'continuous-shell178-readonly-diagnosis.json','external existing shell diagnosis; not repeated'));pins=['rig-foundation167/raw-foundation.json','rig-foundation167/actual-three-foundation.json','rig-foundation167/source34-core-comparison.json','rig-foundation167/freeze.json','basic-pose-seams163/raw-topology.json','basic-pose-seams163/actual-three-seams.json','basic-pose-seams163/incident-edge-coverage.json','rig-adapter01/body-bind34/mapping-report.json','rig-adapter01/body-bind34/rest-axis-verification.json']
for p in pins:pin(R/'docs/evidence/hero-remaster/one-rider-v2'/p,'existing source/adapter evidence; pinned not rerun')
for p in ['harness/hero-remaster/new-rider-fresh-c19-adapter.mts','harness/hero-remaster/new-rider-private-adapter.mts','src/render/hero/gltfRider.ts','src/render/hero/gltfTestUtils.ts']:pin(R/p,'current runtime contract dependency read-only')
rest=G.rest();ib=G.ib();names=[G.d['nodes'][i]['name']for i in G.d['skins'][0]['joints']];idx={n:i for i,n in enumerate(names)};assert len(names)==19;assert [n.removeprefix('fresh.')for n in [C.d['nodes'][i]['name']for i in C.d['skins'][0]['joints']]]==names;assert np.array_equal(rest,C.rest())and np.array_equal(ib,C.ib());assert C.bin==G.bin
primitives=[];rows=[]
for mi,m in enumerate(G.d['meshes']):
 for pi,p in enumerate(m['primitives']):
  attrs,T=G.primitive(mi,pi);ca,ct=C.primitive(mi,pi);assert all(np.array_equal(v,ca[k])for k,v in attrs.items())and np.array_equal(T,ct);primitives.append({'mesh':mi,'primitive':pi,'vertexCount':len(attrs['POSITION']),'triangleCount':len(T),'attributesC19Mapped34Exact':True,'attributeHashes':{k:sha(v.tobytes())for k,v in attrs.items()},'normalizedAccessorFlags':{k:G.d['accessors'][i].get('normalized',False)for k,i in p['attributes'].items()}});rows.append((attrs,T))
body,bodyT=rows[0];glove,gloveT=rows[1];P=body['POSITION'];W=np.zeros((len(P),19))
for k in range(4):np.add.at(W,(np.arange(len(P)),body['JOINTS_0'][:,k]),body['WEIGHTS_0'][:,k])
arm=[i for i,n in enumerate(names)if n.startswith(('shoulder.','upperArm.','forearm.','hand.'))];aw=W[:,arm].sum(1);centres=rest[:,:3,3];mid=(centres[idx['upperArm.L'],2]+centres[idx['upperArm.R'],2])/2;half=.45*min(abs(centres[idx['upperArm.L'],2]-mid),abs(centres[idx['upperArm.R'],2]-mid));low=centres[idx['pelvis'],1]+.05;high=min(centres[idx['neck'],1]-.06,centres[idx['shoulder.L'],1]-.03,centres[idx['shoulder.R'],1]-.03)
masks={'central_core':(P[:,1]>low)&(P[:,1]<high)&(abs(P[:,2]-mid)<half),'lateral_upper_torso_band':(P[:,1]>1.10)&(P[:,1]<high)&(abs(P[:,2]-mid)>=half)&(abs(P[:,2]-mid)<.18)};torso=[]
for label,mask in masks.items():
 ids=np.flatnonzero(mask);witness=ids[np.argsort(aw[ids])[-8:][::-1]];torso.append({'region':label,'definition':{'Ymin':float(low if label=='central_core'else 1.1),'Ymax':float(high),'Zmid':float(mid),'ZabsMin':0 if label=='central_core'else float(half),'ZabsMax':float(half if label=='central_core'else .18),'X':'all source X; geometric diagnostic only, not certified semantic torso segmentation'},'vertices':len(ids),'positiveArmInfluenceVertices':int((aw[ids]>0).sum()),'maxArmInfluence':float(aw[ids].max()),'meanArmInfluence':float(aw[ids].mean()),'literalWitnesses':[{'vertexID':int(i),'P':P[i].tolist(),'canonicalWeights19':W[i].tolist(),'armInfluence':float(aw[i]),'incidentTriangleIDs':np.flatnonzero((bodyT==i).any(1)).tolist()}for i in witness]});np.savez_compressed(S/(label+'.npz'),vertexIDs=ids,canonical19Weights=W[ids])
# Exact position aliases; never use sockets or material numbers for surface identity.
uniqueBody,inverseBody=np.unique(P,axis=0,return_inverse=True);uniqueGlove,inverseGlove=np.unique(glove['POSITION'],axis=0,return_inverse=True);bk={tuple(p):i for i,p in enumerate(uniqueBody)};gk={tuple(p):i for i,p in enumerate(uniqueGlove)};common=sorted(set(bk)&set(gk));assert len(common)==127;cuffs=[]
def canonical(attrs,ids):
 w=np.zeros((len(ids),19))
 for k in range(4):np.add.at(w,(np.arange(len(ids)),attrs['JOINTS_0'][ids,k]),attrs['WEIGHTS_0'][ids,k])
 return w
for side in ['L','R']:
 positions=np.array([p for p in common if (p[2]>0)==(side=='L')]);assert len(positions)==(65 if side=='L'else 62);assert set(map(tuple,positions))==set(map(tuple,maps['cuffPositions'+side]));bids=[];gids=[];witness=[];maxGap=0
 for p in positions:
  bi=np.flatnonzero(inverseBody==bk[tuple(p)]);gi=np.flatnonzero(inverseGlove==gk[tuple(p)]);bids.extend(bi.tolist());gids.extend(gi.tolist());weights=np.r_[canonical(body,bi),canonical(glove,gi)];gap=float(np.ptp(weights,axis=0).max());maxGap=max(maxGap,gap);assert gap==0
  if len(witness)<3:witness.append({'position':p.tolist(),'bodyVertexIDs':bi.tolist(),'gloveVertexIDs':gi.tolist(),'weights19':weights[0].tolist()})
 assert set(bids)==set(maps['cuffVertices'+side+'0'])and set(gids)==set(maps['cuffVertices'+side+'1']);socketID=next(i for i,n in enumerate(G.d['nodes'])if n.get('name')=='gripSocket.'+side);socket=G.world(socketID)[:3,3];cuffs.append({'side':side,'physicalAliasGroups':len(positions),'bodyAliasRows':len(bids),'gloveAliasRows':len(gids),'maximumCanonicalAliasWeightDifference':maxGap,'literalWitnesses':witness,'cuffCentre':positions.mean(0).tolist(),'gripSocketPosition':socket.tolist(),'socketToCuffCentreDistanceM':float(np.linalg.norm(socket-positions.mean(0))),'surfaceWarning':'Socket is a grip target attached to hand, not a cuff endpoint or sewn surface proof. Actual matching source position aliases are independently reproduced.'})
children={'pelvis':'spine','spine':'chest','chest':'neck','neck':'head','shoulder.L':'upperArm.L','upperArm.L':'forearm.L','forearm.L':'hand.L','shoulder.R':'upperArm.R','upperArm.R':'forearm.R','forearm.R':'hand.R'};axes=[]
for n,ch in children.items():
 v=centres[idx[ch]]-centres[idx[n]];direction=v/np.linalg.norm(v);basis=rest[idx[n],:3,:3]@np.array([0,1,0]);basis/=np.linalg.norm(basis);axes.append({'bone':n,'child':ch,'originM':centres[idx[n]].tolist(),'childOriginM':centres[idx[ch]].tolist(),'lengthM':float(np.linalg.norm(v)),'explicitChildDirection':direction.tolist(),'bonePlusYBasis':basis.tolist(),'basisDirectionDot':float(basis@direction)})
handBones=H['rig']['bones'];handoffError=max(np.linalg.norm(centres[idx[x['name']]]-x['restJointCentreM'])for x in handBones);assert handoffError<1e-12
result={'status':'CURRENT_FAILED_SOURCE_BASELINE_CONTRACT_ONLY; NOT CONTINUOUS_SHELL179 WEIGHTS OR STAGE2 PASS','sourceHashes':{'rawC19':C.h,'mapped34':G.h},'sourceBINExact':True,'canonicalJointOrder':names,'rawC19JointNames':[C.d['nodes'][i]['name']for i in C.d['skins'][0]['joints']],'sameRestAndInverseBindsExact':True,'restInverseBindResidual':float(abs(rest@ib-np.eye(4)).max()),'meshAttachments':[{'node':i,'mesh':n['mesh'],'skin':n.get('skin'),'parent':G.parents.get(i),'worldColumnMajor':G.world(i).T.ravel().tolist()}for i,n in enumerate(G.d['nodes'])if 'mesh'in n],'rawPrimitives':primitives,'externalHandoffRestMaximumCentreDifferenceM':float(handoffError),'externalHandoffReadBeforeDuplication':True,'externalOldShellDiagnosis':{'status':diagnosis['status'],'counts':diagnosis['authoredCounts'],'warning':'Prior shell178 diagnostic, not a finding about continuous-sculpt179 or this source rig.'},'coordinateAndBases':{'units':'existing source/game coordinate units metres; raw model no unit scale reset','axes':'Y-up, transverse named L is +Z, anterior +X is source/game convention estimate, not measured anatomy','jointWorldLinearDeterminants':np.linalg.det(rest[:,:3,:3]).tolist(),'sourceMeshWorldScaleIdentity':all(np.array_equal(G.world(i),np.eye(4))for i,n in enumerate(G.d['nodes'])if 'mesh'in n),'adapterRequired':'World-aligned source axes require explicit child directions; keep captured rest/binds and private19 contact adapter, no blind +Y or copied quaternions across different bases.'},'headNeckSpineShoulderAxes':axes,'torsoWitnesses':torso,'actualCuffAliases':cuffs,'limits':['Legal binds/rest agreement and length measurements do not certify natural/anatomical skeleton, pivot positions or moving volume.','Lateral torso band is geometric; weights near shoulders are not forbidden simply because near torso.','Raw source attrs C19↔mapped34 exact. Actual GLTFLoader normalized float32 weights differ up to5.96e-8 as pinned167 evidence; no fresh loader/animation run in this selected audit.','Pinned163 cuff moving QA is mapped static V5; this audit reproduces current34 static cuff positions/weights only. No inferred fullmotion clearance from socket agreement.','External .2/.2 head-neck diagnostic fractions belong to external diagnostic, not an approved physics posing override.','No source changes, skeleton fitting, new weights, paint, LOD, Blender render, GPU, browser or stage2/appearance/gameplay acceptance.'],'pinnedInputs':list(records.values()),'recipeSHA256':sha(Path(__file__).read_bytes())}
for p,r in records.items():assert sha(Path(p).read_bytes())==r['SHA256']
result['privateOutputHashes']=[{'path':str(p),'SHA256':sha(p.read_bytes())}for p in S.glob('*.npz')];result['privateHashesNote']='Full selected ROI IDs/weights retained; compressed archive bytes may differ across runtimes, source input hashes remain asserted.'
(O/'report.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'torso':[{k:t[k]for k in ['region','vertices','positiveArmInfluenceVertices','maxArmInfluence']}for t in torso],'cuffs':[{k:c[k]for k in ['side','physicalAliasGroups','bodyAliasRows','gloveAliasRows','maximumCanonicalAliasWeightDifference']}for c in cuffs],'handoffError':float(handoffError)}))
