"""Encode already-rendered fields; labels/crops never alter the source surfaces."""
import argparse,gzip,hashlib,json,subprocess
from pathlib import Path
import numpy as np
from PIL import Image,ImageDraw,ImageFont
ap=argparse.ArgumentParser();ap.add_argument('--domain',choices=['native','actual47'],required=True);a=ap.parse_args();out=Path(__file__).resolve().parent;qa=out.parent;work=out/'tmp'/a.domain;render=json.loads((work/'render.json').read_text());prep=json.loads((work/'preparation.json').read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert render['domain']==a.domain and not render['pilot'] and render['originalSourceAnd51RigPreserved'];assert render['recipeSHA256']==sha(qa/'body55/direct-field-review.py');assert render['preparationSHA256']==sha(work/'preparation.json');rows=render['frames'];local=json.loads((qa/'body53/local-witnesses.json').read_text())['witnesses'];font_path=Path('/System/Library/Fonts/Supplemental/Arial.ttf');bold_path=Path('/System/Library/Fonts/Supplemental/Arial Bold.ttf');font=ImageFont.truetype(str(font_path),24);small=ImageFont.truetype(str(font_path),20);bold=ImageFont.truetype(str(bold_path),26);prepared=work/'encoded-frames';prepared.mkdir(exist_ok=True);fps=60;sequence=[];receipt=[];time_s=0.
settings=prep['settings'];cm=np.array(settings['cameraWorldRows']);width=settings['orthoWidthM'];height=width*1280/1920;title='NATIVE SYNTHETIC FK' if a.domain=='native' else 'ACTUAL47 RECORDED BODY FIELDS';limit=528 if a.domain=='native' else 703;field_key='syntheticFour' if a.domain=='native' else 'actual47Four'
def projected(point,view):
 xyz=np.array(point)@np.array(view['displayFromSourceRotationRows']).T+view['displayTranslationM'];cam=(xyz-cm[:3,3])@cm[:3,:3];return [float((.5+cam[0]/width)*1920),float((.5-cam[1]/height)*1280)]
def text(draw,xy,value,font=small,fill='#ffffff'):draw.text(xy,value,font=font,fill=fill)
def header(image,row,section):
 draw=ImageDraw.Draw(image);draw.rectangle((0,0,1920,36),fill='#15222c');index=row['sourceIndex'];state='MOVING SAMPLES' if row['kind']=='moving' else 'PAUSED EXACT SOURCE WITNESS';text(draw,(14,4),f'{title} | source {index}/{limit} | t={row["sourceTimeS"]:.6f}s | {state}',small);draw.rectangle((0,1245,1920,1280),fill='#15222c');text(draw,(14,1250),'UNACCEPTED | protected head + opaque fitting boxers | source scale1 | CPU geometric normals | parent judges',small)
 if section=='full':
  draw.rectangle((0,624,1920,660),fill='#15222c');text(draw,(14,631),f'TOP: FULL reference | BOTTOM: FOUR normalized | front / left side / rear | strict pairs: {row["body53"]["full"]["strictCrossingPairs"]} / {row["body53"]["four"]["strictCrossingPairs"]}',small)
 else:
  text(draw,(15,44),'FOUR ONLY | SHOULDERS | front / left side / rear',bold);text(draw,(15,680),'FOUR ONLY | HIPS | opaque underwear can hide the numerical crossing',bold)
  if row['kind']!='moving':text(draw,(15,630),'Blue/orange: projected numeric triangles; depth occlusion untested. These guides are not a visible defect verdict.',small)
 return image
for section in ['full','focus']:
 selected=rows
 for row in selected:
  src=work/'frames'/f'{row["number"]:04d}.png';assert sha(src)==row['PNG_SHA256'];raw=Image.open(src).convert('RGB');assert raw.size==(1920,1280)
  image=raw.copy() if section=='full' else Image.new('RGB',(1920,1280),'#353535');crop_receipt=[]
  if section=='focus':
   views=sorted([v for v in row['views'] if v['weight']=='four'],key=lambda x:x['column'])
   for region,y in [('shoulders',88),('hips',735)]:
    for view in views:
     rect=view['focusCrops'][region]['pixelXYWH'];x0,y0,w,h=rect;tile=raw.crop((x0,y0,x0+w,y0+h));scale=min(600/w,450/h);dw,dh=int(round(w*scale)),int(round(h*scale));tile=tile.resize((dw,dh),Image.Resampling.LANCZOS);x=view['column']*640+(640-dw)//2
     if row['kind']!='moving':
      draw=ImageDraw.Draw(tile)
      for witness in local:
       if witness['domain']!=field_key or witness['frameOrInputTick']!=row['sourceIndex'] or not witness['region'].startswith('shoulder' if region=='shoulders' else 'hip'):continue
       for part,color in [('A','#47b5f1'),('B','#ff8f4d')]:
        points=[projected(point,view) for point in witness['XYZ_'+part]];points=[((p[0]-x0)*dw/w,(p[1]-y0)*dh/h) for p in points];draw.line([*points,points[0]],fill=color,width=3)
     image.paste(tile,(x,y));crop_receipt.append({'region':region,'view':view['column'],'sourcePixelXYWH':rect,'outputPixelXYWH':[x,y,dw,dh],'projectedNumericalGuides':row['kind']!='moving'})
  image=header(image,row,section);file=prepared/f'{section}-{row["number"]:04d}.png';image.save(file);copies=int(round(row['durationS']*fps));assert abs(copies/fps-row['durationS'])<1e-12;sequence.extend([file]*copies);receipt.append({'section':section,'sourceDomain':a.domain,'sourceIndex':row['sourceIndex'],'sourceTimeS':row['sourceTimeS'],'kind':row['kind'],'movieStartS':time_s,'movieEndS':time_s+copies/fps,'copiesAt60FPS':copies,'sourcePNG_SHA256':row['PNG_SHA256'],'labelledPNG_SHA256':sha(file),'crops':crop_receipt});time_s+=copies/fps
listfile=work/'movie-frames.txt';listfile.write_text(''.join(f"file '{p}'\nduration {1/fps:.15f}\n" for p in sequence)+f"file '{sequence[-1]}'\n");movie=out/('native-full-four-exposed.mp4' if a.domain=='native' else 'actual47-full-four-exposed.mp4');cmd=['ffmpeg','-v','error','-n','-f','concat','-safe','0','-i',str(listfile),'-r',str(fps),'-frames:v',str(len(sequence)),'-c:v','libx264','-threads','2','-crf','18','-pix_fmt','yuv420p','-an','-movflags','+faststart',str(movie)];subprocess.run(cmd,check=True);probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-show_streams','-show_format','-of','json',str(movie)],text=True));stream=probe['streams'][0];assert len(probe['streams'])==1 and stream['codec_type']=='video' and int(stream['nb_read_frames'])==len(sequence);decode=subprocess.run(['ffmpeg','-v','error','-i',str(movie),'-f','null','-'],capture_output=True,text=True);assert decode.returncode==0 and not decode.stderr
report={'status':'UNACCEPTED_EXACT_EXISTING_BODY_FIELD_MOVIE_ENCODED','domain':a.domain,'movie':str(movie.relative_to(Path.cwd())),'sha256':sha(movie),'bytes':movie.stat().st_size,'dimensions':[1920,1280],'fps':fps,'frames':len(sequence),'durationS':len(sequence)/fps,'sourceRenderSHA256':sha(work/'render.json'),'sourcePreparationSHA256':sha(work/'preparation.json'),'recipeSHA256':sha(Path(__file__)),'fontPins':{str(p):sha(p) for p in [font_path,bold_path]},'sections':['Full/Four paired full-body moving samples and labelled exact witness holds','FOUR-only shoulders/hips moving samples, then labelled paused exact witnesses'],'rows':receipt,'ffmpegFullDecodeExit':decode.returncode,'audioStreams':0,'maximumDisplayFloat32ResidualM':max(v['displayFloat32MaximumResidualM'] for row in rows for v in row['views']),'cameraViewLabelCorrection':'Preparation label side +Y was incorrect: display yaw90 and fixed +X camera give source-native -Y / glTF +Z, anatomical left side. Geometry and camera unchanged. Final labels front / left side / rear.', 'timing':'Original sampled motion cadence: native12source frames/s or actual30source frames/s; encoded60fps by exact repeats only. Separate focus repeats same source sequence. Native final sample pads83.333ms; actual final sample pads8.333ms. Exact witness holds explicitly pause already sampled fields; no controller or pose interpolation.','limits':['Native synthetic FK and actual47 retain separate films/source identities. Actual50 is never used/synchronized.','Full means original full-native body weight reference; Four means normalized primary-four body field. Head remains existing primary field, same in both rows.','Fitting underwear is opaque; numerical triangle guides are projections with untested depth occlusion, not proof of visible defects.','Source body/head/51bind/weights/UV/materials unchanged; geometric-normal CPU presentation only. Parent judges; all M0-M5 remain open.']};(out/(a.domain+'-movie.json')).write_text(json.dumps(report,indent=2)+'\n')
with gzip.open(out/(a.domain+'-render.json.gz'),'wt') as f:json.dump(render,f,separators=(',',':'))
(out/(a.domain+'-preparation.json')).write_bytes((work/'preparation.json').read_bytes());print(json.dumps({k:v for k,v in report.items() if k not in ['rows','fontPins']}))
