"""Literal affected triangles at retained actual frame39; read-only artifact."""
from pathlib import Path
import hashlib,json,numpy as np
ROOT=Path('/Users/raynos/projects/localai/runtime/rockhop-rider-search-v1/one-rider-v2/garment-rebuild01');OUT=Path('/Users/raynos/projects/games/rockhop/docs/evidence/hero-remaster/one-rider-v2/garment-rebuild01/cuff-ankle-transition155');f=np.load(ROOT/'cuff-ankle-transition155/transition155.npz');P=f['native_positions'];W=f['native_weights19'];old=f['native_weights19_before'];Q=f['native_retained_quads'];T=np.concatenate([Q[:,[0,1,2]],Q[:,[0,2,3]]]);raw=(ROOT/'full-motion155/body0-joint-matrices.f64').read_bytes();M=np.frombuffer(raw,dtype='<f8').reshape(480,19,4,4).transpose(0,1,3,2)[39]
def posed(w):return np.einsum('vj,jab,vb->va',w,M[:,:3,:],np.c_[P,np.ones(len(P))])
def area(p):return np.linalg.norm(np.cross(p[T[:,1]]-p[T[:,0]],p[T[:,2]]-p[T[:,0]]),axis=1)
after=posed(W);before=posed(old);rat=area(after)/area(P);oldrat=area(before)/area(P);affected=np.flatnonzero(np.any(W!=old,axis=1));mask=np.isin(T,affected).any(1);ids=np.flatnonzero(mask&(rat<.25));rows=[]
for i in ids:
 vertices=T[i];rows.append({'retainedTriangleID':int(i),'sourceNativeQuadID':int(f['native_retained_quad_ids'][i%len(Q)]),'quadTriangleHalf':int(i//len(Q)),'nativeVertexIDs':vertices.tolist(),'restPositions':P[vertices].tolist(),'oldPosedPositions':before[vertices].tolist(),'newPosedPositions':after[vertices].tolist(),'oldAreaRatio':float(oldrat[i]),'newAreaRatio':float(rat[i]),'nativeWeights19Before':old[vertices].tolist(),'nativeWeights19After':W[vertices].tolist(),'blendAlphaL':f['native_cuff_L_blend_alpha'][vertices].tolist(),'blendAlphaR':f['native_cuff_R_blend_alpha'][vertices].tolist()})
(OUT/'frame39-offenders.json').write_text(json.dumps({'kind':'Full480expansion exposed two new native transition collapses, not a second art attempt','frame':39,'actualFullMatrixSHA256':hashlib.sha256(raw).hexdigest(),'offenders':rows,'limits':'Do not promote solely because rigid cuff bridges pass. Parent should render frame39 and contiguous played window; remaining native deformation is unresolved.'},indent=2)+'\n');print([(r['sourceNativeQuadID'],r['nativeVertexIDs'],r['oldAreaRatio'],r['newAreaRatio']) for r in rows])
